#!/usr/bin/env python3
"""Generate the narrow UTS wire contract used by the native upgrade module."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT.parents[1] / "server/openapi/openapi.yaml"
VERSION_OUTPUT = ROOT / "src/generated/api/mobile-app-version.uts"
PUBLIC_CONFIG_OUTPUT = ROOT / "src/generated/api/mobile-public-config.uts"


def render_version() -> str:
    source = OPENAPI.read_text(encoding="utf-8")
    required = (
        "MobileAppVersion:",
        "delivery_mode:",
        "MobileAppVersionStore:",
        "store_list:",
        "internal_package",
        "external_link",
    )
    missing = [value for value in required if value not in source]
    if missing:
        raise SystemExit(f"OpenAPI mobile upgrade contract is incomplete: {missing}")
    return """// Generated from server/openapi/openapi.yaml by scripts/generate-mobile-client.py.
// Do not edit this file directly.

export type MobileAppVersionStoreWire = {
  readonly id: string
  readonly name: string
  readonly scheme: string
  readonly priority: number
}

export type MobileAppVersionWire = {
  readonly platform: string
  readonly package_type: string
  readonly delivery_mode: 'internal_package' | 'external_link'
  readonly current_version: string
  readonly minimum_version: string
  readonly upgrade_url: string | null
  readonly store_list: Array<MobileAppVersionStoreWire>
  readonly title: string
  readonly release_notes: string
  readonly is_silently: boolean
  readonly is_mandatory: boolean
  readonly published_at: string | null
}
"""


def render_public_config() -> str:
    source = OPENAPI.read_text(encoding="utf-8")
    required = (
        "AppPublicStartup:",
        "AppPublicStartupSlide:",
        "published_version:",
        "accessibility_label:",
        "/api/v1/public/startup-assets/{file_id}:",
        "PublicShareProvider:",
        "fallback_mode:",
        "PublicPushRuntime:",
        "build_variants:",
    )
    missing = [value for value in required if value not in source]
    if missing:
        raise SystemExit(f"OpenAPI mobile startup contract is incomplete: {missing}")
    return """// Generated from server/openapi/openapi.yaml by scripts/generate-mobile-client.py.
// Do not edit this file directly.

export type PublicStartupSlideWire = {
  readonly position: number
  readonly image_url: string
  readonly accessibility_label: string
}

export type PublicStartupWire = {
  readonly display_name: string
  readonly subtitle: string
  readonly icon_url: string | null
  readonly onboarding_enabled: boolean
  readonly published_version: number
  readonly slides: Array<PublicStartupSlideWire>
}

export type PublicConfigWire = {
  readonly app_id: string
  readonly appid: string
  readonly app_type: string
  readonly name: string
  readonly default_locale: string
  readonly registration_enabled: boolean
  readonly registration_verification_mode: string
  readonly startup: PublicStartupWire
  readonly share: PublicShareRuntimeWire
  readonly push: PublicPushRuntimeWire
}

export type PublicShareProviderWire = {
  readonly provider_code: 'wechat'
  readonly enabled: boolean
  readonly scenes: Array<'session' | 'timeline' | 'favorite'>
  readonly fallback_mode: 'system'
}

export type PublicShareRuntimeWire = {
  readonly providers: Array<PublicShareProviderWire>
}

export type PublicPushRuntimeWire = {
  readonly enabled: boolean
  readonly environment: 'development' | 'test' | 'staging' | 'production'
  readonly providers: Array<'apns' | 'fcm' | 'huawei_android' | 'honor' | 'xiaomi' | 'oppo' | 'vivo' | 'meizu' | 'harmony'>
  readonly build_variants: Array<'ios' | 'android_google' | 'android_china' | 'harmony'>
}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    outputs = {VERSION_OUTPUT: render_version(), PUBLIC_CONFIG_OUTPUT: render_public_config()}
    if args.write:
        for output, expected in outputs.items():
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(expected, encoding="utf-8")
            print(f"updated {output.relative_to(ROOT)}")
        return
    stale = [str(output.relative_to(ROOT)) for output, expected in outputs.items() if (output.read_text(encoding="utf-8") if output.exists() else "") != expected]
    if stale:
        raise SystemExit(f"generated mobile API client is stale ({', '.join(stale)}); run python3 scripts/generate-mobile-client.py --write")
    print("mobile generated API client is current")


if __name__ == "__main__":
    main()
