#!/usr/bin/env python3
"""Generate the narrow UTS wire contract used by the native upgrade module."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT.parents[1] / "server/openapi/openapi.yaml"
OUTPUT = ROOT / "src/generated/api/mobile-app-version.uts"


def render() -> str:
    source = OPENAPI.read_text(encoding="utf-8")
    required = (
        "MobileAppVersion:",
        "delivery_mode:",
        "MobileAppVersionStore:",
        "store_list:",
        "internal_package",
        "external_link",
    )
    missing = [value for value in required if value not in source]
    if missing:
        raise SystemExit(f"OpenAPI mobile upgrade contract is incomplete: {missing}")
    return """// Generated from server/openapi/openapi.yaml by scripts/generate-mobile-client.py.
// Do not edit this file directly.

export type MobileAppVersionStoreWire = {
  readonly id: string
  readonly name: string
  readonly scheme: string
  readonly priority: number
}

export type MobileAppVersionWire = {
  readonly platform: string
  readonly package_type: string
  readonly delivery_mode: 'internal_package' | 'external_link'
  readonly current_version: string
  readonly minimum_version: string
  readonly upgrade_url: string | null
  readonly store_list: Array<MobileAppVersionStoreWire>
  readonly title: string
  readonly release_notes: string
  readonly is_silently: boolean
  readonly is_mandatory: boolean
  readonly published_at: string | null
}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"updated {OUTPUT.relative_to(ROOT)}")
        return
    actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if actual != expected:
        raise SystemExit("generated mobile API client is stale; run python3 scripts/generate-mobile-client.py --write")
    print("mobile generated API client is current")


if __name__ == "__main__":
    main()
