#!/usr/bin/env python3
"""Generate the narrow UTS wire contract used by the native upgrade module."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT.parents[1] / "server/openapi/openapi.yaml"
VERSION_OUTPUT = ROOT / "src/generated/api/mobile-app-version.uts"
PUBLIC_CONFIG_OUTPUT = ROOT / "src/generated/api/mobile-public-config.uts"
ACCOUNT_DELETION_OUTPUT = ROOT / "src/generated/api/mobile-account-deletion.uts"
MOBILE_IDENTITY_OUTPUT = ROOT / "src/generated/api/mobile-identity.uts"


def openapi_schemas() -> dict:
    import yaml

    return yaml.safe_load(OPENAPI.read_text(encoding="utf-8"))["components"]["schemas"]


def require_schema_fields(schemas: dict, schema_name: str, fields: tuple[str, ...]) -> None:
    schema = schemas.get(schema_name)
    if not isinstance(schema, dict):
        raise SystemExit(f"OpenAPI schema is missing: {schema_name}")
    properties = schema.get("properties", {})
    missing = [field for field in fields if field not in properties]
    if missing:
        raise SystemExit(f"OpenAPI schema {schema_name} is incomplete: {missing}")


def render_version() -> str:
    source = OPENAPI.read_text(encoding="utf-8")
    required = (
        "MobileAppVersion:",
        "delivery_mode:",
        "MobileAppVersionStore:",
        "store_list:",
        "internal_package",
        "external_link",
    )
    missing = [value for value in required if value not in source]
    if missing:
        raise SystemExit(f"OpenAPI mobile upgrade contract is incomplete: {missing}")
    return """// Generated from server/openapi/openapi.yaml by scripts/generate-mobile-client.py.
// Do not edit this file directly.

export type MobileAppVersionStoreWire = {
  readonly id: string
  readonly name: string
  readonly scheme: string
  readonly priority: number
}

export type MobileAppVersionWire = {
  readonly platform: string
  readonly package_type: string
  readonly delivery_mode: 'internal_package' | 'external_link'
  readonly current_version: string
  readonly minimum_version: string
  readonly upgrade_url: string | null
  readonly store_list: Array<MobileAppVersionStoreWire>
  readonly title: string
  readonly release_notes: string
  readonly is_silently: boolean
  readonly is_mandatory: boolean
  readonly published_at: string | null
}
"""


def render_public_config() -> str:
    source = OPENAPI.read_text(encoding="utf-8")
    required = (
        "AppPublicStartup:",
        "AppPublicStartupSlide:",
        "published_version:",
        "accessibility_label:",
        "/api/v1/public/startup-assets/{file_id}:",
        "PublicShareProvider:",
        "fallback_mode:",
        "PublicPushRuntime:",
        "build_variants:",
        "PublicScannerConfig:",
        "allowed_host_patterns:",
        "PublicLoginMethods:",
    )
    missing = [value for value in required if value not in source]
    if missing:
        raise SystemExit(f"OpenAPI mobile startup contract is incomplete: {missing}")
    return """// Generated from server/openapi/openapi.yaml by scripts/generate-mobile-client.py.
// Do not edit this file directly.

export type PublicStartupSlideWire = {
  readonly position: number
  readonly image_url: string
  readonly accessibility_label: string
}

export type PublicStartupWire = {
  readonly display_name: string
  readonly subtitle: string
  readonly icon_url: string | null
  readonly onboarding_enabled: boolean
  readonly published_version: number
  readonly slides: Array<PublicStartupSlideWire>
}

export type PublicConfigWire = {
  readonly app_id: string
  readonly appid: string
  readonly app_type: string
  readonly name: string
  readonly default_locale: string
  readonly registration_enabled: boolean
  readonly registration_verification_mode: string
  readonly startup: PublicStartupWire
  readonly share: PublicShareRuntimeWire
  readonly push: PublicPushRuntimeWire
  readonly scanner: PublicScannerRuntimeWire | null
  readonly login_methods: PublicLoginMethodsWire
}

export type PublicShareProviderWire = {
  readonly provider_code: 'wechat'
  readonly enabled: boolean
  readonly scenes: Array<'session' | 'timeline' | 'favorite'>
  readonly fallback_mode: 'system'
}

export type PublicShareRuntimeWire = {
  readonly providers: Array<PublicShareProviderWire>
}

export type PublicPushRuntimeWire = {
  readonly enabled: boolean
  readonly environment: 'development' | 'test' | 'staging' | 'production'
  readonly providers: Array<'apns' | 'fcm' | 'huawei_android' | 'honor' | 'xiaomi' | 'oppo' | 'vivo' | 'meizu' | 'harmony'>
  readonly build_variants: Array<'ios' | 'android_google' | 'android_china' | 'harmony'>
}

export type PublicScannerWebViewWire = {
  readonly enabled: boolean
  readonly allowed_host_patterns: Array<string>
}

export type PublicScannerRuntimeWire = {
  readonly webview: PublicScannerWebViewWire | null
}

export type PublicPasswordLoginWire = { readonly enabled: true }
export type PublicOTPLoginWire = { readonly enabled: boolean; readonly email_enabled: boolean; readonly sms_enabled: boolean }
export type PublicOAuthLoginWire = { readonly enabled: boolean }

export type PublicLoginMethodsWire = {
  readonly password: PublicPasswordLoginWire
  readonly otp: PublicOTPLoginWire
  readonly oauth: PublicOAuthLoginWire
}
"""


def render_account_deletion() -> str:
    source = OPENAPI.read_text(encoding="utf-8")
    required = (
        "/api/v1/me/account-deletion/verification-code:",
        "/api/v1/me/account-deletion/confirm:",
        "AccountDeletionVerificationCode:",
        "verification_code:",
        "acknowledged:",
        "AccountDeletionResult:",
    )
    missing = [value for value in required if value not in source]
    if missing:
        raise SystemExit(f"OpenAPI account deletion contract is incomplete: {missing}")
    schemas = openapi_schemas()
    require_schema_fields(
        schemas,
        "AccountDeletionVerificationCode",
        (
            "accepted",
            "verification_required",
            "reauth_required",
            "reauth_provider",
            "reauth_account_id",
            "target_hint",
            "expires_in_seconds",
            "retry_after_seconds",
        ),
    )
    require_schema_fields(
        schemas,
        "AccountDeletionConfirmRequest",
        ("verification_code", "step_up_token", "acknowledged"),
    )
    return """// Generated from server/openapi/openapi.yaml by scripts/generate-mobile-client.py.
// Do not edit this file directly.

export type AccountDeletionVerificationCodeWire = {
  readonly accepted: boolean
  readonly verification_required: boolean
  readonly reauth_required: boolean
  readonly reauth_provider: string | null
  readonly reauth_account_id: string | null
  readonly target_hint: string
  readonly expires_in_seconds: number
  readonly retry_after_seconds: number
}

export type AccountDeletionConfirmWire = {
  readonly verification_code: string
  readonly step_up_token: string
  readonly acknowledged: boolean
}

export type AccountDeletionResultWire = {
  readonly deleted: boolean
}
"""


def render_mobile_identity() -> str:
    schemas = openapi_schemas()
    requirements = {
        "MobileLoginProvider": (
            "provider_code", "display_name_key", "icon_key", "authorization_kind",
            "supported_platforms", "build_variants", "login_enabled", "binding_enabled",
            "sort_order", "config_schema_version", "build_config_hash", "build_config",
        ),
        "MobileOAuthAuthorizeRequest": (
            "mode", "platform", "build_variant", "build_config_hash", "step_up_token",
            "reauth_purpose", "account_id",
        ),
        "MobileOAuthAuthorizeResult": (
            "flow_id", "provider_code", "mode", "authorization_kind", "authorization_url",
            "state", "nonce", "expires_at",
        ),
        "MobileOAuthCallbackRequest": (
            "flow_id", "state", "authorization_code", "id_token", "one_time_ticket",
            "display_name",
        ),
        "MobileOAuthCallbackResult": (
            "mode", "oauth_account", "session", "step_up_token", "step_up_expires_at",
        ),
        "MobileOAuthAccount": (
            "id", "provider_code", "display_name_key", "provider_username_hint", "status",
            "login_enabled", "login_capable", "can_bind", "can_change", "bound_at",
            "last_authenticated_at", "can_unbind", "block_reason",
        ),
        "MobileLoginIdentifier": (
            "id", "identifier_type", "display_hint", "verified", "status", "login_capable",
            "can_bind", "can_change", "can_unbind", "block_reason",
        ),
        "MobilePasswordMethod": (
            "present", "login_capable", "can_bind", "can_change", "can_unbind", "block_reason",
        ),
        "MobileLoginMethods": ("password", "identifiers", "oauth_accounts", "remaining_login_methods"),
        "LoginIdentifierChallengeRequest": ("identifier", "captcha"),
        "LoginIdentifierVerifyRequest": ("identifier", "challenge_id", "verification_code", "step_up_token"),
        "MobileStepUpCodeRequest": ("identifier_id", "purpose", "resource", "captcha"),
        "MobileStepUpRequest": (
            "method", "purpose", "resource", "password", "identifier_id", "challenge_id",
            "verification_code",
        ),
        "MobileStepUpResult": ("step_up_token", "expires_at"),
        "OTPChallenge": ("challenge_id", "accepted", "retry_after_seconds", "expires_at"),
        "MobileOTPLoginRequest": ("identifier_type", "identifier", "challenge_id", "verification_code"),
        "AppIdentifierRequest": ("identifier_type", "identifier", "captcha"),
        "MobileLoginCodeRequest": ("mobile", "captcha"),
        "MobileSMSCaptchaTargetRequest": ("scene", "mobile"),
        "MobileSMSCaptchaStepUpRequest": ("scene", "identifier_id", "purpose", "resource"),
        "MobileInteractiveCaptchaSubmission": ("id", "token", "response"),
        "AppOTPRegistrationRequest": ("identifier_type", "identifier", "challenge_id", "verification_code", "display_name", "locale", "accept_terms"),
        "MobilePasswordResetRequest": ("identifier_type", "identifier", "challenge_id", "verification_code", "new_password"),
        "MobileSetPasswordRequest": ("new_password", "step_up_token"),
        "MobileToken": (
            "access_token", "token_type", "expires_in", "refresh_token",
            "refresh_token_expires_in", "session_id", "app_id",
        ),
    }
    for schema_name, fields in requirements.items():
        require_schema_fields(schemas, schema_name, fields)
    captcha_request_refs = {item.get("$ref") for item in schemas.get("MobileSMSCaptchaRequest", {}).get("oneOf", [])}
    if captcha_request_refs != {
        "#/components/schemas/MobileSMSCaptchaTargetRequest",
        "#/components/schemas/MobileSMSCaptchaStepUpRequest",
    }:
        raise SystemExit("OpenAPI MobileSMSCaptchaRequest must discriminate target and step-up inputs")
    return """// Generated from server/openapi/openapi.yaml by scripts/generate-mobile-client.py.
// Do not edit this file directly.

export type MobileOAuthBuildConfigWire = {
  readonly app_id: string | null
  readonly client_id: string | null
  readonly callback_uri: string | null
  readonly app_return_uri: string | null
  readonly server_client_id: string | null
  readonly android_package_name: string | null
  readonly android_app_signature: string | null
  readonly android_certificate_sha256: Array<string> | null
  readonly ios_bundle_id: string | null
  readonly ios_universal_link: string | null
  readonly harmony_bundle_name: string | null
}

export type MobileLoginProviderWire = {
  readonly provider_code: string
  readonly display_name_key: string
  readonly icon_key: string
  readonly authorization_kind: string
  readonly supported_platforms: Array<string>
  readonly build_variants: Array<string>
  readonly login_enabled: boolean
  readonly binding_enabled: boolean
  readonly sort_order: number
  readonly config_schema_version: number
  readonly build_config_hash: string
  readonly build_config: MobileOAuthBuildConfigWire
}

export type MobileLoginProviderListWire = { readonly items: Array<MobileLoginProviderWire> }

export type MobileOAuthAuthorizeWire = {
  readonly mode: string
  readonly platform: string
  readonly build_variant: string
  readonly build_config_hash: string
}

export type MobileOAuthAuthorizeBindWire = { readonly mode: string; readonly platform: string; readonly build_variant: string; readonly build_config_hash: string; readonly step_up_token: string }
export type MobileOAuthReauthorizeWire = { readonly mode: string; readonly platform: string; readonly build_variant: string; readonly build_config_hash: string; readonly reauth_purpose: string; readonly account_id: string }

export type MobileOAuthFlowWire = {
  readonly flow_id: string
  readonly provider_code: string
  readonly mode: string
  readonly authorization_kind: string
  readonly authorization_url: string | null
  readonly state: string
  readonly nonce: string | null
  readonly expires_at: string
}

export type MobileOAuthCodeCallbackWire = { readonly flow_id: string; readonly state: string; readonly authorization_code: string }
export type MobileOAuthIDTokenCallbackWire = { readonly flow_id: string; readonly state: string; readonly id_token: string }
export type MobileOAuthAppleCallbackWire = { readonly flow_id: string; readonly state: string; readonly id_token: string; readonly authorization_code: string }
export type MobileOAuthAppleProfileCallbackWire = { readonly flow_id: string; readonly state: string; readonly id_token: string; readonly authorization_code: string; readonly display_name: string }
export type MobileOAuthTicketCallbackWire = { readonly flow_id: string; readonly one_time_ticket: string }

export type MobileSessionTokenWire = {
  readonly access_token: string
  readonly token_type: string
  readonly expires_in: number
  readonly refresh_token: string
  readonly refresh_token_expires_in: number
  readonly session_id: string
  readonly app_id: string
}

export type MobileOAuthAccountWire = {
  readonly id: string
  readonly provider_code: string
  readonly display_name_key: string
  readonly provider_username_hint: string | null
  readonly status: string
  readonly login_enabled: boolean
  readonly login_capable: boolean
  readonly can_bind: boolean
  readonly can_change: boolean
  readonly bound_at: string
  readonly last_authenticated_at: string | null
  readonly can_unbind: boolean
  readonly block_reason: string | null
}

export type MobileOAuthCallbackWire = {
  readonly mode: string
  readonly session: MobileSessionTokenWire | null
  readonly oauth_account: MobileOAuthAccountWire | null
  readonly step_up_token: string | null
  readonly step_up_expires_at: string | null
}

export type MobileOAuthAccountListWire = { readonly items: Array<MobileOAuthAccountWire> }
export type MobileStepUpTokenWire = { readonly step_up_token: string }
export type MobileUnboundWire = { readonly unbound: boolean }

export type MobilePasswordMethodWire = {
  readonly present: boolean
  readonly login_capable: boolean
  readonly can_bind: boolean
  readonly can_change: boolean
  readonly can_unbind: boolean
  readonly block_reason: string | null
}

export type MobileLoginIdentifierWire = {
  readonly id: string
  readonly identifier_type: string
  readonly display_hint: string
  readonly verified: boolean
  readonly status: string
  readonly login_capable: boolean
  readonly can_bind: boolean
  readonly can_change: boolean
  readonly can_unbind: boolean
  readonly block_reason: string | null
}

export type MobileLoginMethodsWire = {
  readonly password: MobilePasswordMethodWire
  readonly identifiers: Array<MobileLoginIdentifierWire>
  readonly oauth_accounts: Array<MobileOAuthAccountWire>
  readonly remaining_login_methods: number
}

export type MobileCaptchaTypeWire = 'click' | 'slide' | 'drag' | 'rotate'
export type MobileCaptchaPointWire = { readonly x: number; readonly y: number }
export type MobileCaptchaImageWire = { readonly base64: string; readonly mime_type: string; readonly width: number; readonly height: number }
export type MobileCaptchaClickResponseWire = { readonly type: 'click'; readonly points: Array<MobileCaptchaPointWire> }
export type MobileCaptchaPointResponseWire = { readonly type: 'slide' | 'drag'; readonly point: MobileCaptchaPointWire }
export type MobileCaptchaRotateResponseWire = { readonly type: 'rotate'; readonly angle: number }
export type MobileCaptchaResponseWire = MobileCaptchaClickResponseWire | MobileCaptchaPointResponseWire | MobileCaptchaRotateResponseWire
export type MobileCaptchaSubmissionWire = { readonly id: string; readonly token: string; readonly response: MobileCaptchaResponseWire }
export type MobileCaptchaChallengeWire = {
  readonly captcha_id: string
  readonly captcha_token: string
  readonly type: MobileCaptchaTypeWire
  readonly expires_in_seconds: number
  readonly image: MobileCaptchaImageWire
  readonly prompt_image: MobileCaptchaImageWire | null
  readonly required_points: number | null
  readonly tile_image: MobileCaptchaImageWire | null
  readonly initial_point: MobileCaptchaPointWire | null
  readonly thumb_image: MobileCaptchaImageWire | null
}
export type MobileSMSCaptchaPublicRequestWire = { readonly scene: 'login' | 'registration' | 'password_reset' | 'identifier_verify'; readonly mobile: string }
export type MobileSMSCaptchaStepUpRequestWire = { readonly scene: 'step_up'; readonly identifier_id: string; readonly purpose: string; readonly resource: string }
export type MobileSMSCaptchaRequestWire = MobileSMSCaptchaPublicRequestWire | MobileSMSCaptchaStepUpRequestWire

export type MobileIdentifierChallengeRequestWire = { readonly identifier: string; readonly captcha: MobileCaptchaSubmissionWire | null }
export type MobileIdentifierBindWire = { readonly identifier: string; readonly challenge_id: string; readonly verification_code: string }
export type MobileIdentifierChangeWire = { readonly identifier: string; readonly challenge_id: string; readonly verification_code: string; readonly step_up_token: string }
export type MobileIdentifierMutationWire = { readonly identifier: MobileLoginIdentifierWire }
export type MobileStepUpCodeWire = { readonly identifier_id: string; readonly purpose: string; readonly resource: string; readonly captcha: MobileCaptchaSubmissionWire | null }
export type MobileStepUpPasswordWire = { readonly method: string; readonly purpose: string; readonly resource: string; readonly password: string }
export type MobileStepUpOTPWire = { readonly method: string; readonly purpose: string; readonly resource: string; readonly identifier_id: string; readonly challenge_id: string; readonly verification_code: string }
export type MobileOTPChallengeWire = { readonly challenge_id: string; readonly accepted: boolean; readonly retry_after_seconds: number; readonly expires_at: string }
export type MobileStepUpProofWire = { readonly step_up_token: string; readonly expires_at: string }

export type MobileEmailOTPSendWire = { readonly email: string }
export type MobileSMSOTPSendWire = { readonly mobile: string; readonly captcha: MobileCaptchaSubmissionWire }
export type MobileOTPLoginWire = { readonly identifier_type: string; readonly identifier: string; readonly challenge_id: string; readonly verification_code: string }
export type MobileOTPRegistrationCodeWire = { readonly identifier_type: string; readonly identifier: string; readonly captcha: MobileCaptchaSubmissionWire | null }
export type MobileOTPRegistrationWire = { readonly identifier_type: string; readonly identifier: string; readonly challenge_id: string; readonly verification_code: string; readonly display_name: string; readonly locale: string; readonly accept_terms: boolean }
export type MobilePasswordForgotWire = { readonly identifier_type: string; readonly identifier: string; readonly captcha: MobileCaptchaSubmissionWire | null }
export type MobilePasswordResetWire = { readonly identifier_type: string; readonly identifier: string; readonly challenge_id: string; readonly verification_code: string; readonly new_password: string }
export type MobileSetPasswordWire = { readonly new_password: string; readonly step_up_token: string }
"""



def render_feedback() -> str:
    import yaml
    schemas = yaml.safe_load(OPENAPI.read_text(encoding="utf-8"))["components"]["schemas"]
    names = ["FeedbackStatus", "FeedbackAttachment", "FeedbackReply", "FeedbackEvent", "Feedback", "FeedbackInput", "FeedbackReplyInput", "FeedbackStatusInput", "FeedbackUploadInput", "FeedbackUpload"]
    def type_name(schema):
        if "$ref" in schema:
            return schema["$ref"].split("/")[-1] + "Wire"
        kind = schema.get("type")
        if isinstance(kind, list):
            return " | ".join("null" if k == "null" else type_name({**schema, "type": k}) for k in kind)
        if kind == "array":
            return "Array<" + type_name(schema["items"]) + ">"
        return {"string": "string", "integer": "number", "boolean": "boolean"}[kind]
    lines = ["// Generated from server/openapi/openapi.yaml. Do not edit."]
    for name in names:
        schema = schemas[name]
        if schema["type"] != "object":
            lines.append("export type " + name + "Wire = " + type_name(schema))
            continue
        lines.append("export type " + name + "Wire = {")
        for key, prop in schema["properties"].items():
            # Kotlin reactive proxies need mutable DTO properties, even when callers only read them.
            lines.append("  " + key + ": " + type_name(prop))
        lines.append("}")
    return "\n".join(lines) + "\n"

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    outputs = {
        VERSION_OUTPUT: render_version(),
        ROOT / "src/generated/api/mobile-feedback.uts": render_feedback(),
        PUBLIC_CONFIG_OUTPUT: render_public_config(),
        ACCOUNT_DELETION_OUTPUT: render_account_deletion(),
        MOBILE_IDENTITY_OUTPUT: render_mobile_identity(),
    }
    if args.write:
        for output, expected in outputs.items():
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(expected, encoding="utf-8")
            print(f"updated {output.relative_to(ROOT)}")
        return
    stale = [str(output.relative_to(ROOT)) for output, expected in outputs.items() if (output.read_text(encoding="utf-8") if output.exists() else "") != expected]
    if stale:
        raise SystemExit(f"generated mobile API client is stale ({', '.join(stale)}); run python3 scripts/generate-mobile-client.py --write")
    print("mobile generated API client is current")


if __name__ == "__main__":
    main()
