from __future__ import annotations
import json, os, shutil
from pathlib import Path
from playwright.sync_api import Route, sync_playwright

ROOT=Path(__file__).resolve().parents[3]; BASE=os.environ.get("AK_E2E_BASE_URL","http://127.0.0.1:4173"); AXE=ROOT/"apps/ak-admin/node_modules/axe-core/axe.min.js"; OUT=ROOT/"apps/ak-admin/artifacts/ui-ux-pro-max/AKADM-content-management/screenshots"; OUT.mkdir(parents=True,exist_ok=True)
PERMS=["content.article.read","content.article.create","content.article.update","content.article.delete","content.article.publish","content.article.archive","content.category.read","content.category.create","content.category.update","content.category.delete","storage.file.read"]
CAT={"id":"123e4567-e89b-12d3-a456-426614174000","slug":"news","status":"active","sort_order":1,"lock_version":1,"created_at":"2026-08-05T00:00:00Z","updated_at":"2026-08-05T00:00:00Z","translations":{"zh-CN":{"name":"新闻","description":""},"en-US":{"name":"News","description":""}}}
ARTICLE={"id":"223e4567-e89b-12d3-a456-426614174000","content_type":"article","category_id":CAT["id"],"category_ids":[CAT["id"]],"topic_id":None,"tag_ids":[],"tags":[],"media":[],"slug":"welcome","status":"draft","cover_file_id":None,"cover_url":None,"reading_minutes":5,"allow_comments":True,"pinned":False,"featured":True,"latest":False,"video_source_type":None,"video_file_id":None,"video_external_url":None,"video_duration_seconds":None,"sort_order":1,"lock_version":1,"published_at":None,"created_at":"2026-08-05T00:00:00Z","updated_at":"2026-08-05T00:00:00Z","translations":{"zh-CN":{"title":"欢迎使用","summary":"欢迎","body_format":"markdown","body":"正文"},"en-US":{"title":"Welcome","summary":"Welcome","body_format":"markdown","body":"Body"}}}
FILE={"id":"523e4567-e89b-12d3-a456-426614174000","original_name":"article-cover.jpg","media_type":"image/jpeg","extension":"jpg","size_bytes":17837,"provider":"local","status":"ready","scan_status":"skipped","usage_count":0,"created_at":"2026-08-28T00:00:00Z","updated_at":"2026-08-28T00:00:00Z"}
FILE_SVG="""<svg xmlns="http://www.w3.org/2000/svg" width="640" height="420" viewBox="0 0 640 420"><rect width="640" height="420" fill="#e8f2ff"/><rect x="42" y="42" width="556" height="336" rx="28" fill="#175cd3"/><circle cx="210" cy="180" r="72" fill="#6ce5e8"/><path d="M110 330 255 205l82 77 67-58 126 106Z" fill="#fff"/><text x="320" y="100" text-anchor="middle" font-family="Arial" font-size="34" fill="#fff">AppKernia</text></svg>"""
def respond(route:Route,status:int,data:object): route.fulfill(status=status,content_type="application/json",body=json.dumps({"code":"OK","message":"OK","data":data,"request_id":"content-e2e"}))
def handler(route:Route):
 u=route.request.url
 if u.endswith("/auth/public-config"): return respond(route,200,{"locale":"zh-CN","default_locale":"zh-CN","supported_locales":["zh-CN","en-US"],"feature_flags":{},"settings":{}})
 if u.endswith("/auth/login"): return respond(route,200,{"access_token":"e2e","token_type":"Bearer","expires_in":900,"csrf_token":"csrf-e2e-value-long-enough"})
 if u.endswith("/auth/context"): return respond(route,200,{"user":{"id":"323e4567-e89b-12d3-a456-426614174000","email":"e2e@app.test","display_name":"E2E","locale":"zh-CN","time_zone":"UTC","avatar_url":None},"active_tenant":{"id":"423e4567-e89b-12d3-a456-426614174000","name":"E2E","code":"e2e"},"available_tenants":[],"roles":[],"permissions":PERMS,"menus":[],"feature_flags":{},"menu_revision":"1","permission_revision":"1","server_time":"2026-08-05T00:00:00Z"})
 if "/dashboard/summary" in u: return respond(route,200,{"range":"7d","start_at":"2026-08-22T00:00:00Z","end_at":"2026-08-29T00:00:00Z","metrics":[]})
 if "/dashboard/trends" in u: return respond(route,200,{"range":"7d","start_at":"2026-08-22T00:00:00Z","end_at":"2026-08-29T00:00:00Z","series":[]})
 if "/dashboard/activity" in u: return respond(route,200,{"range":"7d","start_at":"2026-08-22T00:00:00Z","end_at":"2026-08-29T00:00:00Z","operations":[],"failed_jobs":[],"security_events":[]})
 if u.endswith("/me") and route.request.method == "PATCH": return respond(route,200,{"id":"323e4567-e89b-12d3-a456-426614174000","email":"e2e@app.test","display_name":"E2E","locale":"en-US","time_zone":"UTC","avatar_url":None})
 if u.endswith("/dictionaries/system.language"):
  english=route.request.headers.get("accept-language","").startswith("en-US")
  return respond(route,200,{"code":"system.language","locale":"en-US" if english else "zh-CN","extension_policy":"fixed","items":[{"value":"zh-CN","label":"Simplified Chinese" if english else "简体中文","is_default":True,"extra":{}},{"value":"en-US","label":"English","is_default":False,"extra":{}}]})
 if "/content/categories" in u: return respond(route,200,{"items":[CAT],"page":1,"page_size":50,"total":1})
 if "/content/items" in u: return respond(route,200,{"items":[ARTICLE],"page":1,"page_size":20,"total":1})
 if any(segment in u for segment in ["/content/topics","/content/tags","/content/comments","/content/comment-reports"]): return respond(route,200,{"items":[],"page":1,"page_size":100,"total":0})
 if "/files?" in u: return respond(route,200,{"items":[FILE],"page":1,"page_size":80,"total":1})
 if u.endswith(f"/files/{FILE['id']}"): return respond(route,200,FILE)
 if u.endswith(f"/files/{FILE['id']}/presign-download"): return respond(route,200,{"download_url":f"/files/{FILE['id']}/content"})
 if u.endswith(f"/files/{FILE['id']}/content"): return route.fulfill(status=200,content_type="image/svg+xml",body=FILE_SVG)
 return respond(route,200,{})
def axe(page,name,evidence,include=None):
 page.add_script_tag(path=str(AXE)); context={"exclude":[[".ant-table-measure-row"]]};
 if include: context["include"]=[[include]]
 result=page.evaluate("async context=>await axe.run(context,{resultTypes:['violations']})",context); severe=[v for v in result["violations"] if v["impact"] in("serious","critical")]; evidence[name]={"serious_critical":len(severe)}; assert not severe,severe
def main():
 print("content-e2e:start",flush=True)
 evidence={}
 with sync_playwright() as p:
  b=p.chromium.launch(); c=b.new_context(locale="zh-CN",viewport={"width":1440,"height":900}); page=c.new_page(); page.route("**/admin-api/**",handler)
  page.on("console",lambda m: print(f"browser:{m.type}:{m.text}",flush=True) if m.type=="error" else None)
  page.on("requestfailed",lambda r: print(f"requestfailed:{r.url}:{r.failure}",flush=True))
  page.set_default_timeout(10_000)
  print("content-e2e:login-load",flush=True); page.goto(BASE+"/login",wait_until="domcontentloaded"); print("content-e2e:login-fill",flush=True); page.get_by_label("账号").fill("e2e@app.test"); page.get_by_label("密码").fill("password"); print("content-e2e:login-submit",flush=True); page.locator('button[type="submit"]').click(); page.wait_for_url("**/dashboard**"); print("content-e2e:dashboard",flush=True)
  print("content-e2e:articles-load",flush=True); page.evaluate("window.history.pushState({}, '', '/system/content/articles'); window.dispatchEvent(new PopStateEvent('popstate'))"); page.get_by_role("heading",name="资讯工作台").wait_for(); page.get_by_text("欢迎使用").wait_for(); print(f"content-e2e:articles-url:{page.url}",flush=True); assert "sort=updated_desc" in page.url; axe(page,"zh-CN.1440",evidence); page.screenshot(path=OUT/"1440x900-light.png",full_page=True)
  print("content-e2e:article-drawer",flush=True); page.locator("button:has-text('编 辑')").click(); drawer=page.get_by_role("dialog"); drawer.wait_for(); drawer.get_by_role("tab",name="Meta 信息",exact=True).wait_for(); page.screenshot(path=OUT/"drawer-zh-CN-1440.png",full_page=True)
  print("content-e2e:file-picker",flush=True); drawer.get_by_role("button",name="选择封面文件").click(); picker=page.get_by_role("dialog",name="选择文件"); picker.wait_for(); picker.get_by_text("article-cover.jpg").first.wait_for(); page.wait_for_timeout(250); axe(page,"zh-CN.file-picker.thumbnail.1440",evidence,".ak-file-picker-modal")
  last_header=picker.locator(".ak-file-picker-thumbnail-table thead th").last; header_radius=last_header.evaluate("element=>getComputedStyle(element).borderTopRightRadius"); evidence["file-picker-table-header"]={"top_right_radius":header_radius}; assert header_radius=="0px",header_radius
  picker.get_by_role("combobox",name="文件类型").click(); select_popup=page.locator(".ant-select-dropdown:visible"); selected_option=select_popup.locator(".ant-select-item-option-selected"); selected_option.wait_for(); option_colors=selected_option.evaluate("element=>{const style=getComputedStyle(element);return {background:style.backgroundColor,color:style.color}}"); evidence["file-picker-type-option"] = option_colors; assert option_colors["background"] in ("rgb(234, 242, 255)","rgb(220, 234, 255)"),option_colors; assert option_colors["color"]=="rgb(23, 62, 122)",option_colors; select_popup.screenshot(path=OUT/"file-picker-select-menu-zh-CN.png"); page.screenshot(path=OUT/"file-picker-select-open-zh-CN-1440.png"); page.keyboard.press("Escape")
  resize_handle=picker.get_by_role("button",name="调整对话框大小"); resize_handle.hover(); page.wait_for_timeout(200); handle_opacity=resize_handle.evaluate("element=>getComputedStyle(element,'::after').opacity"); assert handle_opacity=="1",handle_opacity; before_resize=picker.bounding_box(); handle_box=resize_handle.bounding_box(); assert before_resize and handle_box; page.mouse.move(handle_box["x"]+handle_box["width"]-5,handle_box["y"]+handle_box["height"]-5); page.mouse.down(); assert resize_handle.get_attribute("data-resizing")=="true"; page.mouse.move(handle_box["x"]+handle_box["width"]+35,handle_box["y"]+handle_box["height"]+19); page.wait_for_timeout(100); active_corner=resize_handle.evaluate("element=>getComputedStyle(element,'::after').borderBottomColor"); page.screenshot(path=OUT/"file-picker-resize-active-zh-CN-1440.png",full_page=True); page.mouse.up(); after_resize=picker.bounding_box(); assert after_resize; evidence["file-picker-resize"]={"hover_opacity":handle_opacity,"active_corner":active_corner,"before":{"width":before_resize["width"],"height":before_resize["height"]},"after":{"width":after_resize["width"],"height":after_resize["height"]}}; assert after_resize["width"]>before_resize["width"] and after_resize["height"]>before_resize["height"],evidence["file-picker-resize"]
  page.screenshot(path=OUT/"file-picker-thumbnail-zh-CN-1440.png",full_page=True)
  picker.get_by_role("button",name="切换文件视图").click(); page.get_by_role("menuitem",name="网格视图").click(); grid_item=picker.locator(".ak-file-picker-grid-item"); grid_item.hover(); picker.locator(".ak-file-picker-grid-meta").wait_for(); page.wait_for_timeout(250); page.screenshot(path=OUT/"file-picker-grid-hover-zh-CN-1440.png",full_page=True)
  picker.get_by_role("button",name="切换文件视图").click(); page.get_by_role("menuitem",name="表格视图").click(); compact_row=picker.locator(".ak-file-picker-compact-table tbody tr").filter(has_text="article-cover.jpg"); page.wait_for_timeout(200); row_height=compact_row.bounding_box()["height"]; evidence["file-picker-compact-row"]={"height":row_height}; assert row_height <= 25,row_height; compact_row.click(); picker.get_by_text("已选择：article-cover.jpg").wait_for(); page.wait_for_timeout(200); page.screenshot(path=OUT/"file-picker-table-zh-CN-1440.png",full_page=True)
  picker.get_by_role("button",name="关闭文件预览").click(); preview_open=picker.get_by_role("button",name="展开文件预览"); preview_open.wait_for(); box=preview_open.bounding_box(); browser_box=picker.locator(".ak-file-picker-browser").bounding_box(); assert box and browser_box; evidence["file-picker-preview-open"]={"button_width":box["width"],"vertical_offset":abs((box["y"]+box["height"]/2)-(browser_box["y"]+browser_box["height"]/2))}; assert box["width"] <= 26; assert evidence["file-picker-preview-open"]["vertical_offset"] <= 2
  window_actions=picker.locator(".ak-file-picker-window-actions"); assert window_actions.get_by_role("button").count()==2; page.screenshot(path=OUT/"file-picker-preview-collapsed-zh-CN-1440.png",full_page=True); window_actions.get_by_role("button",name="关闭").click(); picker.wait_for(state="hidden"); page.keyboard.press("Escape"); drawer.wait_for(state="hidden")
  if os.environ.get("AK_E2E_FILE_PICKER_ONLY")=="1":
   (OUT/"axe-results.json").write_text(json.dumps(evidence,indent=2),encoding="utf-8"); b.close(); print("content-e2e:file-picker-done",flush=True); return
  print("content-e2e:categories-load",flush=True); page.evaluate("window.history.pushState({}, '', '/system/content/categories'); window.dispatchEvent(new PopStateEvent('popstate'))"); page.get_by_role("heading",name="分类管理").wait_for(); page.get_by_text("新闻").wait_for(); axe(page,"zh-CN.categories.1440",evidence); page.locator("button:has-text('编 辑')").click(); category_drawer=page.get_by_role("dialog"); category_drawer.wait_for(); assert category_drawer.get_by_role("tab",name="简体中文").count()==1; assert category_drawer.get_by_role("tab",name="English").count()==1; page.screenshot(path=OUT/"category-drawer-zh-CN-1440.png",full_page=True); page.keyboard.press("Escape"); category_drawer.wait_for(state="hidden")
  print("content-e2e:english-mobile",flush=True); page.get_by_label("显示语言").click(); page.get_by_role("menuitem",name="English").click(); page.get_by_role("heading",name="Category management").wait_for(); page.get_by_role("heading",name="Category management").click(); page.wait_for_timeout(200); page.set_viewport_size({"width":375,"height":812}); axe(page,"en-US.categories.375",evidence); page.screenshot(path=OUT/"375x812-en-US.png",full_page=True)
  (OUT/"axe-results.json").write_text(json.dumps(evidence,indent=2),encoding="utf-8"); b.close(); print("content-e2e:done",flush=True)
if __name__=="__main__": main()
