// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const auditCountLogins = `-- name: AuditCountLogins :one
SELECT count(*)
FROM audit.login_events
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND occurred_at <= $3
  AND ($4::text = '' OR result = $4)
  AND ($5::text = '' OR audience = $5)
  AND ($6::text = '' OR auth_method = $6)
  AND ($7::text = '' OR COALESCE(request_id, '') ILIKE '%' || $7 || '%'
       OR COALESCE(login_identifier_hint, '') ILIKE '%' || $7 || '%')
`

type AuditCountLoginsParams struct {
	TenantID   *uuid.UUID         `json:"tenant_id"`
	FromAt     pgtype.Timestamptz `json:"from_at"`
	ToAt       pgtype.Timestamptz `json:"to_at"`
	Result     string             `json:"result"`
	Audience   string             `json:"audience"`
	AuthMethod string             `json:"auth_method"`
	Query      string             `json:"query"`
}

func (q *Queries) AuditCountLogins(ctx context.Context, arg AuditCountLoginsParams) (int64, error) {
	row := q.db.QueryRow(ctx, auditCountLogins,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Result,
		arg.Audience,
		arg.AuthMethod,
		arg.Query,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const auditCountOperations = `-- name: AuditCountOperations :one
SELECT count(*)
FROM audit.operation_logs
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND occurred_at <= $3
  AND ($4::text = '' OR request_id ILIKE '%' || $4 || '%'
       OR action_name ILIKE '%' || $4 || '%'
       OR COALESCE(resource_id, '') ILIKE '%' || $4 || '%')
  AND ($5::text = '' OR module_code = $5)
  AND ($6::text = '' OR ($6 = 'success' AND succeeded)
       OR ($6 = 'failure' AND NOT succeeded))
`

type AuditCountOperationsParams struct {
	TenantID   *uuid.UUID         `json:"tenant_id"`
	FromAt     pgtype.Timestamptz `json:"from_at"`
	ToAt       pgtype.Timestamptz `json:"to_at"`
	Query      string             `json:"query"`
	ModuleCode string             `json:"module_code"`
	Result     string             `json:"result"`
}

func (q *Queries) AuditCountOperations(ctx context.Context, arg AuditCountOperationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, auditCountOperations,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Query,
		arg.ModuleCode,
		arg.Result,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const auditCountSecurityEvents = `-- name: AuditCountSecurityEvents :one
SELECT count(*)
FROM audit.security_events
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND occurred_at <= $3
  AND ($4::text = '' OR event_type ILIKE '%' || $4 || '%'
       OR source ILIKE '%' || $4 || '%')
  AND ($5::text = '' OR severity = $5)
  AND ($6::text = '' OR source = $6)
  AND ($7::text = '' OR ($7 = 'open' AND resolved_at IS NULL)
       OR ($7 = 'resolved' AND resolved_at IS NOT NULL))
`

type AuditCountSecurityEventsParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
	Query    string             `json:"query"`
	Severity string             `json:"severity"`
	Source   string             `json:"source"`
	Status   string             `json:"status"`
}

func (q *Queries) AuditCountSecurityEvents(ctx context.Context, arg AuditCountSecurityEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, auditCountSecurityEvents,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Query,
		arg.Severity,
		arg.Source,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const auditGetSecurityEvent = `-- name: AuditGetSecurityEvent :one
SELECT id, user_id, session_id, event_type, severity, source,
       COALESCE(client_ip::text, '') AS client_ip, details, resolved_at, resolved_by, occurred_at
FROM audit.security_events
WHERE tenant_id = $1 AND id = $2
`

type AuditGetSecurityEventParams struct {
	TenantID *uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID  `json:"id"`
}

type AuditGetSecurityEventRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     *uuid.UUID         `json:"user_id"`
	SessionID  *uuid.UUID         `json:"session_id"`
	EventType  string             `json:"event_type"`
	Severity   string             `json:"severity"`
	Source     string             `json:"source"`
	ClientIp   interface{}        `json:"client_ip"`
	Details    []byte             `json:"details"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy *uuid.UUID         `json:"resolved_by"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) AuditGetSecurityEvent(ctx context.Context, arg AuditGetSecurityEventParams) (AuditGetSecurityEventRow, error) {
	row := q.db.QueryRow(ctx, auditGetSecurityEvent, arg.TenantID, arg.ID)
	var i AuditGetSecurityEventRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.EventType,
		&i.Severity,
		&i.Source,
		&i.ClientIp,
		&i.Details,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.OccurredAt,
	)
	return i, err
}

const auditListLogins = `-- name: AuditListLogins :many
SELECT id, user_id, session_id, COALESCE(request_id, '') AS request_id,
       COALESCE(login_identifier_hint, '') AS login_identifier_hint,
       auth_method, audience, result, COALESCE(failure_reason, '') AS failure_reason,
       COALESCE(client_ip::text, '') AS client_ip, occurred_at
FROM audit.login_events
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND occurred_at <= $3
  AND ($4::text = '' OR result = $4)
  AND ($5::text = '' OR audience = $5)
  AND ($6::text = '' OR auth_method = $6)
  AND ($7::text = '' OR COALESCE(request_id, '') ILIKE '%' || $7 || '%'
       OR COALESCE(login_identifier_hint, '') ILIKE '%' || $7 || '%')
ORDER BY occurred_at DESC, id DESC
LIMIT $9 OFFSET $8
`

type AuditListLoginsParams struct {
	TenantID   *uuid.UUID         `json:"tenant_id"`
	FromAt     pgtype.Timestamptz `json:"from_at"`
	ToAt       pgtype.Timestamptz `json:"to_at"`
	Result     string             `json:"result"`
	Audience   string             `json:"audience"`
	AuthMethod string             `json:"auth_method"`
	Query      string             `json:"query"`
	PageOffset int32              `json:"page_offset"`
	PageSize   int32              `json:"page_size"`
}

type AuditListLoginsRow struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              *uuid.UUID         `json:"user_id"`
	SessionID           *uuid.UUID         `json:"session_id"`
	RequestID           string             `json:"request_id"`
	LoginIdentifierHint string             `json:"login_identifier_hint"`
	AuthMethod          string             `json:"auth_method"`
	Audience            string             `json:"audience"`
	Result              string             `json:"result"`
	FailureReason       string             `json:"failure_reason"`
	ClientIp            interface{}        `json:"client_ip"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) AuditListLogins(ctx context.Context, arg AuditListLoginsParams) ([]AuditListLoginsRow, error) {
	rows, err := q.db.Query(ctx, auditListLogins,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Result,
		arg.Audience,
		arg.AuthMethod,
		arg.Query,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditListLoginsRow{}
	for rows.Next() {
		var i AuditListLoginsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.RequestID,
			&i.LoginIdentifierHint,
			&i.AuthMethod,
			&i.Audience,
			&i.Result,
			&i.FailureReason,
			&i.ClientIp,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const auditListOperations = `-- name: AuditListOperations :many
SELECT id, user_id, session_id, request_id, COALESCE(trace_id, '') AS trace_id,
       module_code, action_name, COALESCE(permission_code, '') AS permission_code,
       COALESCE(resource_type, '') AS resource_type, COALESCE(resource_id, '') AS resource_id,
       COALESCE(http_method, '') AS http_method, COALESCE(request_path, '') AS request_path,
       response_status, COALESCE(client_ip::text, '') AS client_ip,
       COALESCE(request_summary, '{}'::jsonb) AS request_summary,
       COALESCE(before_data, '{}'::jsonb) AS before_data,
       COALESCE(after_data, '{}'::jsonb) AS after_data,
       duration_ms, succeeded, COALESCE(error_code, '') AS error_code, occurred_at
FROM audit.operation_logs
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND occurred_at <= $3
  AND ($4::text = '' OR request_id ILIKE '%' || $4 || '%'
       OR action_name ILIKE '%' || $4 || '%'
       OR COALESCE(resource_id, '') ILIKE '%' || $4 || '%')
  AND ($5::text = '' OR module_code = $5)
  AND ($6::text = '' OR ($6 = 'success' AND succeeded)
       OR ($6 = 'failure' AND NOT succeeded))
ORDER BY occurred_at DESC, id DESC
LIMIT $8 OFFSET $7
`

type AuditListOperationsParams struct {
	TenantID   *uuid.UUID         `json:"tenant_id"`
	FromAt     pgtype.Timestamptz `json:"from_at"`
	ToAt       pgtype.Timestamptz `json:"to_at"`
	Query      string             `json:"query"`
	ModuleCode string             `json:"module_code"`
	Result     string             `json:"result"`
	PageOffset int32              `json:"page_offset"`
	PageSize   int32              `json:"page_size"`
}

type AuditListOperationsRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         *uuid.UUID         `json:"user_id"`
	SessionID      *uuid.UUID         `json:"session_id"`
	RequestID      string             `json:"request_id"`
	TraceID        string             `json:"trace_id"`
	ModuleCode     string             `json:"module_code"`
	ActionName     string             `json:"action_name"`
	PermissionCode string             `json:"permission_code"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     string             `json:"resource_id"`
	HttpMethod     string             `json:"http_method"`
	RequestPath    string             `json:"request_path"`
	ResponseStatus *int32             `json:"response_status"`
	ClientIp       interface{}        `json:"client_ip"`
	RequestSummary []byte             `json:"request_summary"`
	BeforeData     []byte             `json:"before_data"`
	AfterData      []byte             `json:"after_data"`
	DurationMs     *int32             `json:"duration_ms"`
	Succeeded      bool               `json:"succeeded"`
	ErrorCode      string             `json:"error_code"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) AuditListOperations(ctx context.Context, arg AuditListOperationsParams) ([]AuditListOperationsRow, error) {
	rows, err := q.db.Query(ctx, auditListOperations,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Query,
		arg.ModuleCode,
		arg.Result,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditListOperationsRow{}
	for rows.Next() {
		var i AuditListOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.RequestID,
			&i.TraceID,
			&i.ModuleCode,
			&i.ActionName,
			&i.PermissionCode,
			&i.ResourceType,
			&i.ResourceID,
			&i.HttpMethod,
			&i.RequestPath,
			&i.ResponseStatus,
			&i.ClientIp,
			&i.RequestSummary,
			&i.BeforeData,
			&i.AfterData,
			&i.DurationMs,
			&i.Succeeded,
			&i.ErrorCode,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const auditListSecurityEvents = `-- name: AuditListSecurityEvents :many
SELECT id, user_id, session_id, event_type, severity, source,
       COALESCE(client_ip::text, '') AS client_ip, resolved_at, resolved_by, occurred_at
FROM audit.security_events
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND occurred_at <= $3
  AND ($4::text = '' OR event_type ILIKE '%' || $4 || '%'
       OR source ILIKE '%' || $4 || '%')
  AND ($5::text = '' OR severity = $5)
  AND ($6::text = '' OR source = $6)
  AND ($7::text = '' OR ($7 = 'open' AND resolved_at IS NULL)
       OR ($7 = 'resolved' AND resolved_at IS NOT NULL))
ORDER BY occurred_at DESC, id DESC
LIMIT $9 OFFSET $8
`

type AuditListSecurityEventsParams struct {
	TenantID   *uuid.UUID         `json:"tenant_id"`
	FromAt     pgtype.Timestamptz `json:"from_at"`
	ToAt       pgtype.Timestamptz `json:"to_at"`
	Query      string             `json:"query"`
	Severity   string             `json:"severity"`
	Source     string             `json:"source"`
	Status     string             `json:"status"`
	PageOffset int32              `json:"page_offset"`
	PageSize   int32              `json:"page_size"`
}

type AuditListSecurityEventsRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     *uuid.UUID         `json:"user_id"`
	SessionID  *uuid.UUID         `json:"session_id"`
	EventType  string             `json:"event_type"`
	Severity   string             `json:"severity"`
	Source     string             `json:"source"`
	ClientIp   interface{}        `json:"client_ip"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy *uuid.UUID         `json:"resolved_by"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) AuditListSecurityEvents(ctx context.Context, arg AuditListSecurityEventsParams) ([]AuditListSecurityEventsRow, error) {
	rows, err := q.db.Query(ctx, auditListSecurityEvents,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Query,
		arg.Severity,
		arg.Source,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditListSecurityEventsRow{}
	for rows.Next() {
		var i AuditListSecurityEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.EventType,
			&i.Severity,
			&i.Source,
			&i.ClientIp,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
