// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardActiveSessionCount = `-- name: DashboardActiveSessionCount :one
SELECT count(*)
FROM iam.sessions
WHERE tenant_id = $1
  AND status = 'active'
  AND revoked_at IS NULL
  AND absolute_expires_at > $2
`

type DashboardActiveSessionCountParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) DashboardActiveSessionCount(ctx context.Context, arg DashboardActiveSessionCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardActiveSessionCount, arg.TenantID, arg.EndAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardFailedJobCount = `-- name: DashboardFailedJobCount :one
SELECT count(*)
FROM jobs.schedule_runs run
JOIN jobs.schedules schedule ON schedule.id = run.schedule_id
WHERE schedule.tenant_id = $1
  AND run.status = 'failed'
  AND run.scheduled_at >= $2
  AND run.scheduled_at <= $3
`

type DashboardFailedJobCountParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) DashboardFailedJobCount(ctx context.Context, arg DashboardFailedJobCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardFailedJobCount, arg.TenantID, arg.StartAt, arg.EndAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardFailedJobTrend = `-- name: DashboardFailedJobTrend :many
WITH days AS (
    SELECT generate_series(
        date_trunc('day', $2::timestamptz),
        date_trunc('day', $3::timestamptz),
        interval '1 day'
    ) AS day
)
SELECT days.day::timestamptz AS day, count(run.id) AS value
FROM days
LEFT JOIN jobs.schedules schedule ON schedule.tenant_id = $1
LEFT JOIN jobs.schedule_runs run
  ON run.schedule_id = schedule.id
 AND run.status = 'failed'
 AND run.scheduled_at >= days.day
 AND run.scheduled_at < days.day + interval '1 day'
GROUP BY days.day
ORDER BY days.day
`

type DashboardFailedJobTrendParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

type DashboardFailedJobTrendRow struct {
	Day   pgtype.Timestamptz `json:"day"`
	Value int64              `json:"value"`
}

func (q *Queries) DashboardFailedJobTrend(ctx context.Context, arg DashboardFailedJobTrendParams) ([]DashboardFailedJobTrendRow, error) {
	rows, err := q.db.Query(ctx, dashboardFailedJobTrend, arg.TenantID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardFailedJobTrendRow{}
	for rows.Next() {
		var i DashboardFailedJobTrendRow
		if err := rows.Scan(&i.Day, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardLoginTrend = `-- name: DashboardLoginTrend :many
WITH days AS (
    SELECT generate_series(
        date_trunc('day', $2::timestamptz),
        date_trunc('day', $3::timestamptz),
        interval '1 day'
    ) AS day
)
SELECT days.day::timestamptz AS day,
       count(event.id) FILTER (WHERE event.result = 'success') AS success_count,
       count(event.id) FILTER (WHERE event.result IN ('failure', 'blocked')) AS failure_count
FROM days
LEFT JOIN audit.login_events event
  ON event.tenant_id = $1
 AND event.audience = 'ak-admin'
 AND event.occurred_at >= days.day
 AND event.occurred_at < days.day + interval '1 day'
GROUP BY days.day
ORDER BY days.day
`

type DashboardLoginTrendParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

type DashboardLoginTrendRow struct {
	Day          pgtype.Timestamptz `json:"day"`
	SuccessCount int64              `json:"success_count"`
	FailureCount int64              `json:"failure_count"`
}

func (q *Queries) DashboardLoginTrend(ctx context.Context, arg DashboardLoginTrendParams) ([]DashboardLoginTrendRow, error) {
	rows, err := q.db.Query(ctx, dashboardLoginTrend, arg.TenantID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardLoginTrendRow{}
	for rows.Next() {
		var i DashboardLoginTrendRow
		if err := rows.Scan(&i.Day, &i.SuccessCount, &i.FailureCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardOpenSecurityEventCount = `-- name: DashboardOpenSecurityEventCount :one
SELECT count(*)
FROM audit.security_events
WHERE tenant_id = $1
  AND resolved_at IS NULL
`

func (q *Queries) DashboardOpenSecurityEventCount(ctx context.Context, tenantID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardOpenSecurityEventCount, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardPublishedMessageCount = `-- name: DashboardPublishedMessageCount :one
SELECT count(*)
FROM notify.messages
WHERE tenant_id = $1
  AND status = 'published'
  AND deleted_at IS NULL
  AND published_at >= $2
  AND published_at <= $3
`

type DashboardPublishedMessageCountParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) DashboardPublishedMessageCount(ctx context.Context, arg DashboardPublishedMessageCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardPublishedMessageCount, arg.TenantID, arg.StartAt, arg.EndAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardRecentFailedJobs = `-- name: DashboardRecentFailedJobs :many
SELECT run.id, schedule.code AS schedule_code, schedule.name AS schedule_name,
       run.error_code, run.scheduled_at
FROM jobs.schedule_runs run
JOIN jobs.schedules schedule ON schedule.id = run.schedule_id
WHERE schedule.tenant_id = $1
  AND run.status = 'failed'
  AND run.scheduled_at >= $2
  AND run.scheduled_at <= $3
ORDER BY run.scheduled_at DESC, run.id DESC
LIMIT 10
`

type DashboardRecentFailedJobsParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

type DashboardRecentFailedJobsRow struct {
	ID           uuid.UUID          `json:"id"`
	ScheduleCode string             `json:"schedule_code"`
	ScheduleName string             `json:"schedule_name"`
	ErrorCode    *string            `json:"error_code"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) DashboardRecentFailedJobs(ctx context.Context, arg DashboardRecentFailedJobsParams) ([]DashboardRecentFailedJobsRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentFailedJobs, arg.TenantID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentFailedJobsRow{}
	for rows.Next() {
		var i DashboardRecentFailedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleCode,
			&i.ScheduleName,
			&i.ErrorCode,
			&i.ScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentOperations = `-- name: DashboardRecentOperations :many
SELECT id, module_code, action_name, resource_type, succeeded, error_code, occurred_at
FROM audit.operation_logs
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND occurred_at <= $3
ORDER BY occurred_at DESC, id DESC
LIMIT 10
`

type DashboardRecentOperationsParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

type DashboardRecentOperationsRow struct {
	ID           uuid.UUID          `json:"id"`
	ModuleCode   string             `json:"module_code"`
	ActionName   string             `json:"action_name"`
	ResourceType *string            `json:"resource_type"`
	Succeeded    bool               `json:"succeeded"`
	ErrorCode    *string            `json:"error_code"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) DashboardRecentOperations(ctx context.Context, arg DashboardRecentOperationsParams) ([]DashboardRecentOperationsRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentOperations, arg.TenantID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentOperationsRow{}
	for rows.Next() {
		var i DashboardRecentOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ModuleCode,
			&i.ActionName,
			&i.ResourceType,
			&i.Succeeded,
			&i.ErrorCode,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentSecurityEvents = `-- name: DashboardRecentSecurityEvents :many
SELECT id, event_type, severity, source, occurred_at
FROM audit.security_events
WHERE tenant_id = $1
  AND occurred_at >= $2
  AND occurred_at <= $3
ORDER BY occurred_at DESC, id DESC
LIMIT 10
`

type DashboardRecentSecurityEventsParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

type DashboardRecentSecurityEventsRow struct {
	ID         uuid.UUID          `json:"id"`
	EventType  string             `json:"event_type"`
	Severity   string             `json:"severity"`
	Source     string             `json:"source"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) DashboardRecentSecurityEvents(ctx context.Context, arg DashboardRecentSecurityEventsParams) ([]DashboardRecentSecurityEventsRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentSecurityEvents, arg.TenantID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentSecurityEventsRow{}
	for rows.Next() {
		var i DashboardRecentSecurityEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Severity,
			&i.Source,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardSecurityTrend = `-- name: DashboardSecurityTrend :many
WITH days AS (
    SELECT generate_series(
        date_trunc('day', $2::timestamptz),
        date_trunc('day', $3::timestamptz),
        interval '1 day'
    ) AS day
)
SELECT days.day::timestamptz AS day, count(event.id) AS value
FROM days
LEFT JOIN audit.security_events event
  ON event.tenant_id = $1
 AND event.occurred_at >= days.day
 AND event.occurred_at < days.day + interval '1 day'
GROUP BY days.day
ORDER BY days.day
`

type DashboardSecurityTrendParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

type DashboardSecurityTrendRow struct {
	Day   pgtype.Timestamptz `json:"day"`
	Value int64              `json:"value"`
}

func (q *Queries) DashboardSecurityTrend(ctx context.Context, arg DashboardSecurityTrendParams) ([]DashboardSecurityTrendRow, error) {
	rows, err := q.db.Query(ctx, dashboardSecurityTrend, arg.TenantID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardSecurityTrendRow{}
	for rows.Next() {
		var i DashboardSecurityTrendRow
		if err := rows.Scan(&i.Day, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardUserSummary = `-- name: DashboardUserSummary :one
SELECT count(*) AS total_users,
       count(*) FILTER (WHERE u.created_at >= $1) AS new_users
FROM iam.tenant_members tm
JOIN iam.users u ON u.id = tm.user_id AND u.deleted_at IS NULL
WHERE tm.tenant_id = $2
  AND tm.status = 'active'
`

type DashboardUserSummaryParams struct {
	StartAt  pgtype.Timestamptz `json:"start_at"`
	TenantID uuid.UUID          `json:"tenant_id"`
}

type DashboardUserSummaryRow struct {
	TotalUsers int64 `json:"total_users"`
	NewUsers   int64 `json:"new_users"`
}

func (q *Queries) DashboardUserSummary(ctx context.Context, arg DashboardUserSummaryParams) (DashboardUserSummaryRow, error) {
	row := q.db.QueryRow(ctx, dashboardUserSummary, arg.StartAt, arg.TenantID)
	var i DashboardUserSummaryRow
	err := row.Scan(&i.TotalUsers, &i.NewUsers)
	return i, err
}

const dashboardUserTrend = `-- name: DashboardUserTrend :many
WITH days AS (
    SELECT generate_series(
        date_trunc('day', $2::timestamptz),
        date_trunc('day', $3::timestamptz),
        interval '1 day'
    ) AS day
)
SELECT days.day::timestamptz AS day, count(DISTINCT u.id) AS value
FROM days
LEFT JOIN iam.tenant_members tm ON tm.tenant_id = $1 AND tm.status = 'active'
LEFT JOIN iam.users u
  ON u.id = tm.user_id
 AND u.deleted_at IS NULL
 AND u.created_at >= days.day
 AND u.created_at < days.day + interval '1 day'
GROUP BY days.day
ORDER BY days.day
`

type DashboardUserTrendParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
}

type DashboardUserTrendRow struct {
	Day   pgtype.Timestamptz `json:"day"`
	Value int64              `json:"value"`
}

func (q *Queries) DashboardUserTrend(ctx context.Context, arg DashboardUserTrendParams) ([]DashboardUserTrendRow, error) {
	rows, err := q.db.Query(ctx, dashboardUserTrend, arg.TenantID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardUserTrendRow{}
	for rows.Next() {
		var i DashboardUserTrendRow
		if err := rows.Scan(&i.Day, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
