// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: iam.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO iam.user_roles (tenant_id, user_id, role_id, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, user_id, role_id) DO NOTHING
`

type AssignUserRoleParams struct {
	TenantID  uuid.UUID  `json:"tenant_id"`
	UserID    uuid.UUID  `json:"user_id"`
	RoleID    uuid.UUID  `json:"role_id"`
	GrantedBy *uuid.UUID `json:"granted_by"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole,
		arg.TenantID,
		arg.UserID,
		arg.RoleID,
		arg.GrantedBy,
	)
	return err
}

const consumePasswordResetChallenges = `-- name: ConsumePasswordResetChallenges :exec
UPDATE iam.verification_challenges
SET consumed_at = COALESCE(consumed_at, now())
WHERE user_id = $1
  AND challenge_type = 'password_reset'
  AND consumed_at IS NULL
`

func (q *Queries) ConsumePasswordResetChallenges(ctx context.Context, userID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumePasswordResetChallenges, userID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO iam.roles (tenant_id, code, name, description, role_type, data_scope, is_default, is_system, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, parent_id, code, name, description, role_type, data_scope, sort_order, is_default, is_system, status, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	RoleType    string    `json:"role_type"`
	DataScope   string    `json:"data_scope"`
	IsDefault   bool      `json:"is_default"`
	IsSystem    bool      `json:"is_system"`
	Status      string    `json:"status"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (IamRole, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.RoleType,
		arg.DataScope,
		arg.IsDefault,
		arg.IsSystem,
		arg.Status,
	)
	var i IamRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.RoleType,
		&i.DataScope,
		&i.SortOrder,
		&i.IsDefault,
		&i.IsSystem,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO iam.tenants (code, name, status, settings)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, status, plan_code, settings, created_at, updated_at, deleted_at
`

type CreateTenantParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	Status   string `json:"status"`
	Settings []byte `json:"settings"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (IamTenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.Settings,
	)
	var i IamTenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.PlanCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTenantMember = `-- name: CreateTenantMember :one
INSERT INTO iam.tenant_members (tenant_id, user_id, member_number, display_name, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING tenant_id, user_id, member_number, display_name, status, invited_by, invited_at, joined_at, left_at, created_at, updated_at
`

type CreateTenantMemberParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	UserID       uuid.UUID `json:"user_id"`
	MemberNumber *string   `json:"member_number"`
	DisplayName  *string   `json:"display_name"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateTenantMember(ctx context.Context, arg CreateTenantMemberParams) (IamTenantMember, error) {
	row := q.db.QueryRow(ctx, createTenantMember,
		arg.TenantID,
		arg.UserID,
		arg.MemberNumber,
		arg.DisplayName,
		arg.Status,
	)
	var i IamTenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.MemberNumber,
		&i.DisplayName,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO iam.users (username, email, mobile, display_name, locale, time_zone, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, mobile, display_name, real_name, avatar_file_id, gender, birthday, bio, locale, time_zone, status, email_verified_at, mobile_verified_at, last_login_at, last_active_at, lock_version, is_system, metadata, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username    *string `json:"username"`
	Email       *string `json:"email"`
	Mobile      *string `json:"mobile"`
	DisplayName string  `json:"display_name"`
	Locale      string  `json:"locale"`
	TimeZone    string  `json:"time_zone"`
	Status      string  `json:"status"`
	Metadata    []byte  `json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IamUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Mobile,
		arg.DisplayName,
		arg.Locale,
		arg.TimeZone,
		arg.Status,
		arg.Metadata,
	)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.DisplayName,
		&i.RealName,
		&i.AvatarFileID,
		&i.Gender,
		&i.Birthday,
		&i.Bio,
		&i.Locale,
		&i.TimeZone,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.MobileVerifiedAt,
		&i.LastLoginAt,
		&i.LastActiveAt,
		&i.LockVersion,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUserCredential = `-- name: CreateUserCredential :one
INSERT INTO iam.user_credentials (user_id, password_hash, password_algorithm)
VALUES ($1, $2, 'argon2id')
RETURNING user_id, password_hash, password_algorithm, password_version, password_changed_at, force_password_change, failed_attempts, locked_until, updated_at
`

type CreateUserCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) (IamUserCredential, error) {
	row := q.db.QueryRow(ctx, createUserCredential, arg.UserID, arg.PasswordHash)
	var i IamUserCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordAlgorithm,
		&i.PasswordVersion,
		&i.PasswordChangedAt,
		&i.ForcePasswordChange,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTenantByCode = `-- name: GetActiveTenantByCode :one
SELECT id, code, name, status, plan_code, settings, created_at, updated_at, deleted_at FROM iam.tenants
WHERE code = $1 AND status = 'active' AND deleted_at IS NULL
`

func (q *Queries) GetActiveTenantByCode(ctx context.Context, code string) (IamTenant, error) {
	row := q.db.QueryRow(ctx, getActiveTenantByCode, code)
	var i IamTenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.PlanCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveTenantMember = `-- name: GetActiveTenantMember :one
SELECT tenant_id, user_id, member_number, display_name, status, invited_by, invited_at, joined_at, left_at, created_at, updated_at
FROM iam.tenant_members
WHERE tenant_id = $1 AND user_id = $2 AND status = 'active'
`

type GetActiveTenantMemberParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActiveTenantMember(ctx context.Context, arg GetActiveTenantMemberParams) (IamTenantMember, error) {
	row := q.db.QueryRow(ctx, getActiveTenantMember, arg.TenantID, arg.UserID)
	var i IamTenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.MemberNumber,
		&i.DisplayName,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByEmail = `-- name: GetCredentialByEmail :one
SELECT u.id AS user_id,
       u.email,
       u.display_name,
       u.locale,
       u.status,
       c.password_hash,
       c.password_version,
       c.failed_attempts,
       c.locked_until
FROM iam.users u
JOIN iam.user_credentials c ON c.user_id = u.id
WHERE u.email = $1 AND u.deleted_at IS NULL
`

type GetCredentialByEmailRow struct {
	UserID          uuid.UUID          `json:"user_id"`
	Email           *string            `json:"email"`
	DisplayName     string             `json:"display_name"`
	Locale          string             `json:"locale"`
	Status          string             `json:"status"`
	PasswordHash    string             `json:"password_hash"`
	PasswordVersion int32              `json:"password_version"`
	FailedAttempts  int32              `json:"failed_attempts"`
	LockedUntil     pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) GetCredentialByEmail(ctx context.Context, email *string) (GetCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByEmail, email)
	var i GetCredentialByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.FailedAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getDefaultMemberRole = `-- name: GetDefaultMemberRole :one
SELECT id
FROM iam.roles
WHERE tenant_id = $1
  AND code = 'member'
  AND status = 'active'
  AND deleted_at IS NULL
ORDER BY is_default DESC, id
LIMIT 1
`

func (q *Queries) GetDefaultMemberRole(ctx context.Context, tenantID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDefaultMemberRole, tenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPasswordResetState = `-- name: GetPasswordResetState :one
SELECT vc.user_id,
       c.password_hash,
       c.password_version
FROM iam.verification_challenges AS vc
JOIN iam.user_credentials AS c ON c.user_id = vc.user_id
JOIN iam.users AS u ON u.id = vc.user_id
WHERE vc.secret_hash = $1
  AND vc.challenge_type = 'password_reset'
  AND vc.consumed_at IS NULL
  AND vc.expires_at > now()
  AND vc.attempts < vc.max_attempts
  AND u.status = 'active'
  AND u.deleted_at IS NULL
ORDER BY vc.created_at DESC
LIMIT 1
`

type GetPasswordResetStateRow struct {
	UserID          *uuid.UUID `json:"user_id"`
	PasswordHash    string     `json:"password_hash"`
	PasswordVersion int32      `json:"password_version"`
}

func (q *Queries) GetPasswordResetState(ctx context.Context, secretHash []byte) (GetPasswordResetStateRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetState, secretHash)
	var i GetPasswordResetStateRow
	err := row.Scan(&i.UserID, &i.PasswordHash, &i.PasswordVersion)
	return i, err
}

const getSelfPasswordState = `-- name: GetSelfPasswordState :one
SELECT password_hash, password_version
FROM iam.user_credentials
WHERE user_id = $1
`

type GetSelfPasswordStateRow struct {
	PasswordHash    string `json:"password_hash"`
	PasswordVersion int32  `json:"password_version"`
}

func (q *Queries) GetSelfPasswordState(ctx context.Context, userID uuid.UUID) (GetSelfPasswordStateRow, error) {
	row := q.db.QueryRow(ctx, getSelfPasswordState, userID)
	var i GetSelfPasswordStateRow
	err := row.Scan(&i.PasswordHash, &i.PasswordVersion)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, code, name, status, plan_code, settings, created_at, updated_at, deleted_at FROM iam.tenants
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (IamTenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i IamTenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.PlanCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, mobile, display_name, real_name, avatar_file_id, gender, birthday, bio, locale, time_zone, status, email_verified_at, mobile_verified_at, last_login_at, last_active_at, lock_version, is_system, metadata, created_at, updated_at, deleted_at FROM iam.users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (IamUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.DisplayName,
		&i.RealName,
		&i.AvatarFileID,
		&i.Gender,
		&i.Birthday,
		&i.Bio,
		&i.Locale,
		&i.TimeZone,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.MobileVerifiedAt,
		&i.LastLoginAt,
		&i.LastActiveAt,
		&i.LockVersion,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, mobile, display_name, real_name, avatar_file_id, gender, birthday, bio, locale, time_zone, status, email_verified_at, mobile_verified_at, last_login_at, last_active_at, lock_version, is_system, metadata, created_at, updated_at, deleted_at FROM iam.users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IamUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.DisplayName,
		&i.RealName,
		&i.AvatarFileID,
		&i.Gender,
		&i.Birthday,
		&i.Bio,
		&i.Locale,
		&i.TimeZone,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.MobileVerifiedAt,
		&i.LastLoginAt,
		&i.LastActiveAt,
		&i.LockVersion,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAdminRegistrationAudit = `-- name: InsertAdminRegistrationAudit :exec
INSERT INTO audit.operation_logs (
    tenant_id, user_id, request_id, module_code, action_name, resource_type,
    resource_id, http_method, request_path, response_status, client_ip,
    user_agent, before_data, after_data, succeeded
)
VALUES (
    $1, $2, $3,
    'iam', 'iam.auth.register', 'iam.user', $4, 'POST',
    '/admin-api/v1/auth/register', 202, $5, $6,
    '{}'::jsonb, jsonb_build_object('registered', true, 'role', 'member'), true
)
`

type InsertAdminRegistrationAuditParams struct {
	TenantID   *uuid.UUID  `json:"tenant_id"`
	UserID     *uuid.UUID  `json:"user_id"`
	RequestID  *string     `json:"request_id"`
	ResourceID *string     `json:"resource_id"`
	ClientIp   *netip.Addr `json:"client_ip"`
	UserAgent  *string     `json:"user_agent"`
}

func (q *Queries) InsertAdminRegistrationAudit(ctx context.Context, arg InsertAdminRegistrationAuditParams) error {
	_, err := q.db.Exec(ctx, insertAdminRegistrationAudit,
		arg.TenantID,
		arg.UserID,
		arg.RequestID,
		arg.ResourceID,
		arg.ClientIp,
		arg.UserAgent,
	)
	return err
}

const insertPasswordHistory = `-- name: InsertPasswordHistory :exec
INSERT INTO iam.password_history (user_id, password_hash, password_algorithm)
VALUES ($1, $2, 'argon2id')
`

type InsertPasswordHistoryParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) InsertPasswordHistory(ctx context.Context, arg InsertPasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPasswordHistory, arg.UserID, arg.PasswordHash)
	return err
}

const insertPasswordResetAudit = `-- name: InsertPasswordResetAudit :exec
INSERT INTO audit.operation_logs (
    tenant_id, user_id, request_id, module_code, action_name, resource_type,
    resource_id, http_method, request_path, response_status, client_ip,
    user_agent, before_data, after_data, succeeded
)
VALUES (
    (
      SELECT tm.tenant_id FROM iam.tenant_members AS tm
      WHERE tm.user_id = $1 AND tm.status = 'active'
      ORDER BY tm.created_at, tm.tenant_id LIMIT 1
    ),
    $1, $2, 'iam', 'iam.auth.password.reset',
    'iam.user_credential', $3, 'POST',
    '/admin-api/v1/auth/password/reset', 200, $4,
    $5,
    jsonb_build_object('password_version', $6::integer),
    jsonb_build_object(
      'password_version', $7::integer,
      'sessions_revoked', $8::bigint
    ), true
)
`

type InsertPasswordResetAuditParams struct {
	UserID              *uuid.UUID  `json:"user_id"`
	RequestID           *string     `json:"request_id"`
	ResourceID          *string     `json:"resource_id"`
	ClientIp            *netip.Addr `json:"client_ip"`
	UserAgent           *string     `json:"user_agent"`
	BeforeVersion       int32       `json:"before_version"`
	AfterVersion        int32       `json:"after_version"`
	RevokedSessionCount int64       `json:"revoked_session_count"`
}

func (q *Queries) InsertPasswordResetAudit(ctx context.Context, arg InsertPasswordResetAuditParams) error {
	_, err := q.db.Exec(ctx, insertPasswordResetAudit,
		arg.UserID,
		arg.RequestID,
		arg.ResourceID,
		arg.ClientIp,
		arg.UserAgent,
		arg.BeforeVersion,
		arg.AfterVersion,
		arg.RevokedSessionCount,
	)
	return err
}

const insertPasswordResetChallenge = `-- name: InsertPasswordResetChallenge :one
INSERT INTO iam.verification_challenges (
    user_id, challenge_type, target_hash, secret_hash, expires_at, created_ip,
    metadata
)
SELECT $1, 'password_reset', $2,
       $3, $4, $5,
       jsonb_build_object('channel', 'email')
WHERE NOT EXISTS (
    SELECT 1
    FROM iam.verification_challenges
    WHERE target_hash = $2
      AND challenge_type = 'password_reset'
      AND consumed_at IS NULL
      AND expires_at > now()
      AND created_at > now() - interval '60 seconds'
)
RETURNING id
`

type InsertPasswordResetChallengeParams struct {
	UserID     *uuid.UUID         `json:"user_id"`
	TargetHash []byte             `json:"target_hash"`
	SecretHash []byte             `json:"secret_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedIp  *netip.Addr        `json:"created_ip"`
}

func (q *Queries) InsertPasswordResetChallenge(ctx context.Context, arg InsertPasswordResetChallengeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPasswordResetChallenge,
		arg.UserID,
		arg.TargetHash,
		arg.SecretHash,
		arg.ExpiresAt,
		arg.CreatedIp,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSelfPasswordChangeAudit = `-- name: InsertSelfPasswordChangeAudit :exec
INSERT INTO audit.operation_logs (
    tenant_id, user_id, session_id, request_id, module_code, action_name,
    resource_type, resource_id, http_method, request_path, response_status,
    client_ip, user_agent, before_data, after_data, succeeded
)
VALUES (
    $1, $2, $3, $4,
    'iam', 'iam.me.password.change', 'iam.user_credential', $5, 'POST',
    '/admin-api/v1/me/password/change', 200, $6, $7,
    jsonb_build_object('password_version', $8::integer),
    jsonb_build_object(
      'password_version', $9::integer,
      'other_sessions_revoked', $10::bigint
    ),
    true
)
`

type InsertSelfPasswordChangeAuditParams struct {
	TenantID            *uuid.UUID  `json:"tenant_id"`
	UserID              *uuid.UUID  `json:"user_id"`
	SessionID           *uuid.UUID  `json:"session_id"`
	RequestID           string      `json:"request_id"`
	ResourceID          *string     `json:"resource_id"`
	ClientIp            *netip.Addr `json:"client_ip"`
	UserAgent           *string     `json:"user_agent"`
	BeforeVersion       int32       `json:"before_version"`
	AfterVersion        int32       `json:"after_version"`
	RevokedSessionCount int64       `json:"revoked_session_count"`
}

func (q *Queries) InsertSelfPasswordChangeAudit(ctx context.Context, arg InsertSelfPasswordChangeAuditParams) error {
	_, err := q.db.Exec(ctx, insertSelfPasswordChangeAudit,
		arg.TenantID,
		arg.UserID,
		arg.SessionID,
		arg.RequestID,
		arg.ResourceID,
		arg.ClientIp,
		arg.UserAgent,
		arg.BeforeVersion,
		arg.AfterVersion,
		arg.RevokedSessionCount,
	)
	return err
}

const insertSelfProfileAudit = `-- name: InsertSelfProfileAudit :exec
INSERT INTO audit.operation_logs (
    tenant_id, user_id, session_id, request_id, module_code, action_name,
    resource_type, resource_id, http_method, request_path, response_status,
    client_ip, user_agent, before_data, after_data, succeeded
)
VALUES (
    $1, $2, $3, $4,
    'iam', 'iam.me.update', 'iam.user', $5, 'PATCH',
    '/admin-api/v1/me', 200, $6, $7,
    $8, $9, true
)
`

type InsertSelfProfileAuditParams struct {
	TenantID   *uuid.UUID  `json:"tenant_id"`
	UserID     *uuid.UUID  `json:"user_id"`
	SessionID  *uuid.UUID  `json:"session_id"`
	RequestID  string      `json:"request_id"`
	ResourceID *string     `json:"resource_id"`
	ClientIp   *netip.Addr `json:"client_ip"`
	UserAgent  *string     `json:"user_agent"`
	BeforeData []byte      `json:"before_data"`
	AfterData  []byte      `json:"after_data"`
}

func (q *Queries) InsertSelfProfileAudit(ctx context.Context, arg InsertSelfProfileAuditParams) error {
	_, err := q.db.Exec(ctx, insertSelfProfileAudit,
		arg.TenantID,
		arg.UserID,
		arg.SessionID,
		arg.RequestID,
		arg.ResourceID,
		arg.ClientIp,
		arg.UserAgent,
		arg.BeforeData,
		arg.AfterData,
	)
	return err
}

const listEffectivePermissionCodes = `-- name: ListEffectivePermissionCodes :many
SELECT DISTINCT p.code::text
FROM iam.user_roles ur
JOIN iam.roles r
  ON r.tenant_id = ur.tenant_id
 AND r.id = ur.role_id
 AND r.deleted_at IS NULL
JOIN iam.role_permissions rp
  ON rp.tenant_id = ur.tenant_id
 AND rp.role_id = ur.role_id
JOIN iam.permissions p
  ON p.id = rp.permission_id
 AND p.status = 'active'
WHERE ur.tenant_id = $1
  AND ur.user_id = $2
  AND r.status = 'active'
  AND ur.valid_from <= now()
  AND (ur.valid_until IS NULL OR ur.valid_until > now())
ORDER BY p.code::text
`

type ListEffectivePermissionCodesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) ListEffectivePermissionCodes(ctx context.Context, arg ListEffectivePermissionCodesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listEffectivePermissionCodes, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var p_code string
		if err := rows.Scan(&p_code); err != nil {
			return nil, err
		}
		items = append(items, p_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveRoleCodes = `-- name: ListEffectiveRoleCodes :many
SELECT r.code::text
FROM iam.user_roles ur
JOIN iam.roles r
  ON r.tenant_id = ur.tenant_id
 AND r.id = ur.role_id
 AND r.deleted_at IS NULL
WHERE ur.tenant_id = $1
  AND ur.user_id = $2
  AND r.status = 'active'
  AND ur.valid_from <= now()
  AND (ur.valid_until IS NULL OR ur.valid_until > now())
ORDER BY r.code
`

type ListEffectiveRoleCodesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) ListEffectiveRoleCodes(ctx context.Context, arg ListEffectiveRoleCodesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listEffectiveRoleCodes, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var r_code string
		if err := rows.Scan(&r_code); err != nil {
			return nil, err
		}
		items = append(items, r_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPasswordHashes = `-- name: ListRecentPasswordHashes :many
SELECT password_hash
FROM iam.password_history
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 5
`

func (q *Queries) ListRecentPasswordHashes(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRecentPasswordHashes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var password_hash string
		if err := rows.Scan(&password_hash); err != nil {
			return nil, err
		}
		items = append(items, password_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTenants = `-- name: ListUserTenants :many
SELECT t.id, t.code, t.name, tm.status, tm.joined_at
FROM iam.tenant_members tm
JOIN iam.tenants t ON t.id = tm.tenant_id AND t.deleted_at IS NULL
WHERE tm.user_id = $1 AND tm.status = 'active'
ORDER BY t.name, t.id
`

type ListUserTenantsRow struct {
	ID       uuid.UUID          `json:"id"`
	Code     string             `json:"code"`
	Name     string             `json:"name"`
	Status   string             `json:"status"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListUserTenants(ctx context.Context, userID uuid.UUID) ([]ListUserTenantsRow, error) {
	rows, err := q.db.Query(ctx, listUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTenantsRow{}
	for rows.Next() {
		var i ListUserTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPasswordResetChallenge = `-- name: LockPasswordResetChallenge :one
SELECT id, user_id
FROM iam.verification_challenges
WHERE secret_hash = $1
  AND challenge_type = 'password_reset'
  AND consumed_at IS NULL
  AND expires_at > now()
  AND attempts < max_attempts
FOR UPDATE
`

type LockPasswordResetChallengeRow struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) LockPasswordResetChallenge(ctx context.Context, secretHash []byte) (LockPasswordResetChallengeRow, error) {
	row := q.db.QueryRow(ctx, lockPasswordResetChallenge, secretHash)
	var i LockPasswordResetChallengeRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE iam.refresh_tokens
SET revoked_at = COALESCE(revoked_at, now())
WHERE revoked_at IS NULL
  AND session_id IN (SELECT id FROM iam.sessions WHERE user_id = $1)
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :execrows
UPDATE iam.sessions
SET status = 'revoked',
    revoked_at = COALESCE(revoked_at, now()),
    revoke_reason = 'password_reset',
    access_token_version = access_token_version + 1
WHERE user_id = $1
  AND status = 'active'
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherSessionRefreshTokens = `-- name: RevokeOtherSessionRefreshTokens :exec
UPDATE iam.refresh_tokens
SET revoked_at = COALESCE(revoked_at, now())
WHERE revoked_at IS NULL
  AND session_id IN (
    SELECT s.id FROM iam.sessions AS s
    WHERE s.user_id = $1 AND s.id <> $2
  )
`

type RevokeOtherSessionRefreshTokensParams struct {
	UserID           uuid.UUID `json:"user_id"`
	CurrentSessionID uuid.UUID `json:"current_session_id"`
}

func (q *Queries) RevokeOtherSessionRefreshTokens(ctx context.Context, arg RevokeOtherSessionRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeOtherSessionRefreshTokens, arg.UserID, arg.CurrentSessionID)
	return err
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :execrows
UPDATE iam.sessions
SET status = 'revoked', revoked_at = COALESCE(revoked_at, now()),
    revoke_reason = 'password_changed', access_token_version = access_token_version + 1
WHERE user_id = $1
  AND id <> $2
  AND status = 'active'
  AND revoked_at IS NULL
`

type RevokeOtherSessionsParams struct {
	UserID           uuid.UUID `json:"user_id"`
	CurrentSessionID uuid.UUID `json:"current_session_id"`
}

func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOtherSessions, arg.UserID, arg.CurrentSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordAfterReset = `-- name: UpdatePasswordAfterReset :one
UPDATE iam.user_credentials
SET password_hash = $1,
    password_algorithm = 'argon2id',
    password_version = password_version + 1,
    password_changed_at = now(),
    force_password_change = false,
    failed_attempts = 0,
    locked_until = NULL
WHERE user_id = $2
  AND password_hash = $3
  AND password_version = $4
RETURNING password_version
`

type UpdatePasswordAfterResetParams struct {
	NewHash         string    `json:"new_hash"`
	UserID          uuid.UUID `json:"user_id"`
	ExpectedHash    string    `json:"expected_hash"`
	ExpectedVersion int32     `json:"expected_version"`
}

func (q *Queries) UpdatePasswordAfterReset(ctx context.Context, arg UpdatePasswordAfterResetParams) (int32, error) {
	row := q.db.QueryRow(ctx, updatePasswordAfterReset,
		arg.NewHash,
		arg.UserID,
		arg.ExpectedHash,
		arg.ExpectedVersion,
	)
	var password_version int32
	err := row.Scan(&password_version)
	return password_version, err
}

const updateSelfPasswordConditional = `-- name: UpdateSelfPasswordConditional :one
UPDATE iam.user_credentials
SET password_hash = $1,
    password_algorithm = 'argon2id',
    password_version = password_version + 1,
    password_changed_at = now(),
    force_password_change = false,
    failed_attempts = 0,
    locked_until = NULL
WHERE user_id = $2
  AND password_hash = $3
  AND password_version = $4
RETURNING password_version
`

type UpdateSelfPasswordConditionalParams struct {
	NewHash         string    `json:"new_hash"`
	UserID          uuid.UUID `json:"user_id"`
	ExpectedHash    string    `json:"expected_hash"`
	ExpectedVersion int32     `json:"expected_version"`
}

func (q *Queries) UpdateSelfPasswordConditional(ctx context.Context, arg UpdateSelfPasswordConditionalParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateSelfPasswordConditional,
		arg.NewHash,
		arg.UserID,
		arg.ExpectedHash,
		arg.ExpectedVersion,
	)
	var password_version int32
	err := row.Scan(&password_version)
	return password_version, err
}

const updateSelfProfile = `-- name: UpdateSelfProfile :one
UPDATE iam.users
SET display_name = COALESCE($1::varchar, display_name),
    locale = COALESCE($2::varchar, locale),
    time_zone = COALESCE($3::varchar, time_zone)
WHERE id = $4 AND deleted_at IS NULL AND status = 'active'
RETURNING id, username, email, mobile, display_name, real_name, avatar_file_id, gender, birthday, bio, locale, time_zone, status, email_verified_at, mobile_verified_at, last_login_at, last_active_at, lock_version, is_system, metadata, created_at, updated_at, deleted_at
`

type UpdateSelfProfileParams struct {
	DisplayName *string   `json:"display_name"`
	Locale      *string   `json:"locale"`
	TimeZone    *string   `json:"time_zone"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSelfProfile(ctx context.Context, arg UpdateSelfProfileParams) (IamUser, error) {
	row := q.db.QueryRow(ctx, updateSelfProfile,
		arg.DisplayName,
		arg.Locale,
		arg.TimeZone,
		arg.ID,
	)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Mobile,
		&i.DisplayName,
		&i.RealName,
		&i.AvatarFileID,
		&i.Gender,
		&i.Birthday,
		&i.Bio,
		&i.Locale,
		&i.TimeZone,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.MobileVerifiedAt,
		&i.LastLoginAt,
		&i.LastActiveAt,
		&i.LockVersion,
		&i.IsSystem,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
