// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_providers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAppLoginIdentifierTarget = `-- name: GetAppLoginIdentifierTarget :one
SELECT i.id,i.tenant_id,i.app_id,i.user_id,i.identifier_type,i.normalized_value::text AS normalized_value,
       i.display_hint,i.verified_at,i.status,u.locale
FROM app.user_login_identifiers i
JOIN app.user_memberships m
  ON m.tenant_id=i.tenant_id AND m.app_id=i.app_id AND m.user_id=i.user_id
JOIN iam.users u ON u.id=i.user_id
WHERE i.id=$1 AND i.app_id=$2 AND i.user_id=$3
  AND i.status='active' AND i.verified_at IS NOT NULL AND m.status='active'
  AND u.status='active' AND u.deleted_at IS NULL
`

type GetAppLoginIdentifierTargetParams struct {
	ID     uuid.UUID `json:"id"`
	AppID  uuid.UUID `json:"app_id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetAppLoginIdentifierTargetRow struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	AppID           uuid.UUID          `json:"app_id"`
	UserID          uuid.UUID          `json:"user_id"`
	IdentifierType  string             `json:"identifier_type"`
	NormalizedValue string             `json:"normalized_value"`
	DisplayHint     string             `json:"display_hint"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	Status          string             `json:"status"`
	Locale          string             `json:"locale"`
}

func (q *Queries) GetAppLoginIdentifierTarget(ctx context.Context, arg GetAppLoginIdentifierTargetParams) (GetAppLoginIdentifierTargetRow, error) {
	row := q.db.QueryRow(ctx, getAppLoginIdentifierTarget, arg.ID, arg.AppID, arg.UserID)
	var i GetAppLoginIdentifierTargetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AppID,
		&i.UserID,
		&i.IdentifierType,
		&i.NormalizedValue,
		&i.DisplayHint,
		&i.VerifiedAt,
		&i.Status,
		&i.Locale,
	)
	return i, err
}

const getLoginProviderConfigPublic = `-- name: GetLoginProviderConfigPublic :one
SELECT id,tenant_id,name,description,provider_code,external_client_id,
       config_schema_version,public_config,secret_field_names,
       secret_ciphertext IS NOT NULL AS has_secret,
       credential_fingerprint,status,last_preflight_at,last_preflight_status,
       last_preflight_issues,lock_version,created_at,updated_at
FROM sys.login_provider_configs
WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL
`

type GetLoginProviderConfigPublicParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

type GetLoginProviderConfigPublicRow struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	Name                  string             `json:"name"`
	Description           string             `json:"description"`
	ProviderCode          string             `json:"provider_code"`
	ExternalClientID      string             `json:"external_client_id"`
	ConfigSchemaVersion   int32              `json:"config_schema_version"`
	PublicConfig          []byte             `json:"public_config"`
	SecretFieldNames      []string           `json:"secret_field_names"`
	HasSecret             interface{}        `json:"has_secret"`
	CredentialFingerprint *string            `json:"credential_fingerprint"`
	Status                string             `json:"status"`
	LastPreflightAt       pgtype.Timestamptz `json:"last_preflight_at"`
	LastPreflightStatus   *string            `json:"last_preflight_status"`
	LastPreflightIssues   []byte             `json:"last_preflight_issues"`
	LockVersion           int32              `json:"lock_version"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLoginProviderConfigPublic(ctx context.Context, arg GetLoginProviderConfigPublicParams) (GetLoginProviderConfigPublicRow, error) {
	row := q.db.QueryRow(ctx, getLoginProviderConfigPublic, arg.TenantID, arg.ID)
	var i GetLoginProviderConfigPublicRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ProviderCode,
		&i.ExternalClientID,
		&i.ConfigSchemaVersion,
		&i.PublicConfig,
		&i.SecretFieldNames,
		&i.HasSecret,
		&i.CredentialFingerprint,
		&i.Status,
		&i.LastPreflightAt,
		&i.LastPreflightStatus,
		&i.LastPreflightIssues,
		&i.LockVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppProfileIdentifiers = `-- name: ListAppProfileIdentifiers :many
SELECT identifier_type,normalized_value::text AS normalized_value
FROM app.user_login_identifiers
WHERE app_id=$1 AND user_id=$2
  AND status='active' AND verified_at IS NOT NULL
  AND identifier_type IN ('email','mobile')
ORDER BY identifier_type
`

type ListAppProfileIdentifiersParams struct {
	AppID  uuid.UUID `json:"app_id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListAppProfileIdentifiersRow struct {
	IdentifierType  string `json:"identifier_type"`
	NormalizedValue string `json:"normalized_value"`
}

func (q *Queries) ListAppProfileIdentifiers(ctx context.Context, arg ListAppProfileIdentifiersParams) ([]ListAppProfileIdentifiersRow, error) {
	rows, err := q.db.Query(ctx, listAppProfileIdentifiers, arg.AppID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppProfileIdentifiersRow{}
	for rows.Next() {
		var i ListAppProfileIdentifiersRow
		if err := rows.Scan(&i.IdentifierType, &i.NormalizedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeLoginProviders = `-- name: ListRuntimeLoginProviders :many
SELECT b.tenant_id,b.app_id,b.login_provider_config_id,b.provider_code,b.enabled,b.sort_order,
       c.external_client_id,c.config_schema_version,c.public_config,c.secret_ciphertext,
       c.secret_key_version,c.secret_field_names,c.status,c.last_preflight_status
FROM app.application_login_provider_bindings b
JOIN sys.login_provider_configs c
  ON c.tenant_id=b.tenant_id AND c.id=b.login_provider_config_id AND c.provider_code=b.provider_code
WHERE b.app_id=$1 AND c.deleted_at IS NULL
ORDER BY b.sort_order,b.provider_code
`

type ListRuntimeLoginProvidersRow struct {
	TenantID              uuid.UUID `json:"tenant_id"`
	AppID                 uuid.UUID `json:"app_id"`
	LoginProviderConfigID uuid.UUID `json:"login_provider_config_id"`
	ProviderCode          string    `json:"provider_code"`
	Enabled               bool      `json:"enabled"`
	SortOrder             int32     `json:"sort_order"`
	ExternalClientID      string    `json:"external_client_id"`
	ConfigSchemaVersion   int32     `json:"config_schema_version"`
	PublicConfig          []byte    `json:"public_config"`
	SecretCiphertext      []byte    `json:"secret_ciphertext"`
	SecretKeyVersion      *int32    `json:"secret_key_version"`
	SecretFieldNames      []string  `json:"secret_field_names"`
	Status                string    `json:"status"`
	LastPreflightStatus   *string   `json:"last_preflight_status"`
}

func (q *Queries) ListRuntimeLoginProviders(ctx context.Context, appID uuid.UUID) ([]ListRuntimeLoginProvidersRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeLoginProviders, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeLoginProvidersRow{}
	for rows.Next() {
		var i ListRuntimeLoginProvidersRow
		if err := rows.Scan(
			&i.TenantID,
			&i.AppID,
			&i.LoginProviderConfigID,
			&i.ProviderCode,
			&i.Enabled,
			&i.SortOrder,
			&i.ExternalClientID,
			&i.ConfigSchemaVersion,
			&i.PublicConfig,
			&i.SecretCiphertext,
			&i.SecretKeyVersion,
			&i.SecretFieldNames,
			&i.Status,
			&i.LastPreflightStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
