// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getActivePermissionIDByCode = `-- name: GetActivePermissionIDByCode :one
SELECT id FROM iam.permissions WHERE code::text = $1 AND status = 'active'
`

func (q *Queries) GetActivePermissionIDByCode(ctx context.Context, code string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getActivePermissionIDByCode, code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const grantAllCoreMenusToRole = `-- name: GrantAllCoreMenusToRole :execrows
INSERT INTO sys.role_menus (tenant_id, role_id, menu_id)
SELECT $1, $2, menu.id
FROM sys.menus menu
WHERE menu.tenant_id IS NULL AND menu.deleted_at IS NULL AND menu.status = 'active'
ON CONFLICT (tenant_id, role_id, menu_id) DO NOTHING
`

type GrantAllCoreMenusToRoleParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	RoleID   uuid.UUID `json:"role_id"`
}

func (q *Queries) GrantAllCoreMenusToRole(ctx context.Context, arg GrantAllCoreMenusToRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantAllCoreMenusToRole, arg.TenantID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEffectiveMenus = `-- name: ListEffectiveMenus :many
SELECT DISTINCT menu.id, menu.parent_id, menu.code::text AS code, menu.title,
       menu.menu_type, menu.route_path, menu.component_key, menu.icon,
       menu.affix, menu.sort_order, menu.metadata
FROM iam.user_roles user_role
JOIN iam.roles role
  ON role.tenant_id = user_role.tenant_id
 AND role.id = user_role.role_id
 AND role.status = 'active'
 AND role.deleted_at IS NULL
JOIN sys.role_menus role_menu
  ON role_menu.tenant_id = user_role.tenant_id
 AND role_menu.role_id = user_role.role_id
JOIN sys.menus menu
  ON menu.id = role_menu.menu_id
 AND menu.status = 'active'
 AND menu.deleted_at IS NULL
LEFT JOIN iam.role_permissions role_permission
  ON role_permission.tenant_id = user_role.tenant_id
 AND role_permission.role_id = user_role.role_id
 AND role_permission.permission_id = menu.permission_id
WHERE user_role.tenant_id = $1
  AND user_role.user_id = $2
  AND user_role.valid_from <= now()
  AND (user_role.valid_until IS NULL OR user_role.valid_until > now())
  AND (menu.permission_id IS NULL OR role_permission.permission_id IS NOT NULL)
ORDER BY menu.sort_order, menu.code::text
`

type ListEffectiveMenusParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type ListEffectiveMenusRow struct {
	ID           uuid.UUID  `json:"id"`
	ParentID     *uuid.UUID `json:"parent_id"`
	Code         string     `json:"code"`
	Title        string     `json:"title"`
	MenuType     string     `json:"menu_type"`
	RoutePath    *string    `json:"route_path"`
	ComponentKey *string    `json:"component_key"`
	Icon         *string    `json:"icon"`
	Affix        bool       `json:"affix"`
	SortOrder    int32      `json:"sort_order"`
	Metadata     []byte     `json:"metadata"`
}

func (q *Queries) ListEffectiveMenus(ctx context.Context, arg ListEffectiveMenusParams) ([]ListEffectiveMenusRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveMenus, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectiveMenusRow{}
	for rows.Next() {
		var i ListEffectiveMenusRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Code,
			&i.Title,
			&i.MenuType,
			&i.RoutePath,
			&i.ComponentKey,
			&i.Icon,
			&i.Affix,
			&i.SortOrder,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncSystemAdminMenus = `-- name: SyncSystemAdminMenus :execrows
INSERT INTO sys.role_menus (tenant_id, role_id, menu_id)
SELECT role.tenant_id, role.id, menu.id
FROM iam.roles role
CROSS JOIN sys.menus menu
WHERE role.code = 'super-admin'
  AND role.is_system
  AND role.status = 'active'
  AND role.deleted_at IS NULL
  AND menu.tenant_id IS NULL
  AND menu.status = 'active'
  AND menu.deleted_at IS NULL
ON CONFLICT (tenant_id, role_id, menu_id) DO NOTHING
`

func (q *Queries) SyncSystemAdminMenus(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, syncSystemAdminMenus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCoreMenu = `-- name: UpsertCoreMenu :one
INSERT INTO sys.menus (
    tenant_id, parent_id, permission_id, code, title, menu_type,
    route_path, component_key, icon, affix, sort_order, metadata, status
)
VALUES (
    NULL, $1, $2,
    $3, $4, $5, $6, $7, $8, $9, $10, $11, 'active'
)
ON CONFLICT (code) WHERE tenant_id IS NULL AND deleted_at IS NULL DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    permission_id = EXCLUDED.permission_id,
    title = EXCLUDED.title,
    menu_type = EXCLUDED.menu_type,
    route_path = EXCLUDED.route_path,
    component_key = EXCLUDED.component_key,
    icon = EXCLUDED.icon,
    affix = EXCLUDED.affix,
    sort_order = EXCLUDED.sort_order,
    metadata = EXCLUDED.metadata,
    status = 'active',
    updated_at = now()
RETURNING id, permission_id
`

type UpsertCoreMenuParams struct {
	ParentID     *uuid.UUID `json:"parent_id"`
	PermissionID *uuid.UUID `json:"permission_id"`
	Code         string     `json:"code"`
	Title        string     `json:"title"`
	MenuType     string     `json:"menu_type"`
	RoutePath    *string    `json:"route_path"`
	ComponentKey *string    `json:"component_key"`
	Icon         *string    `json:"icon"`
	Affix        bool       `json:"affix"`
	SortOrder    int32      `json:"sort_order"`
	Metadata     []byte     `json:"metadata"`
}

type UpsertCoreMenuRow struct {
	ID           uuid.UUID  `json:"id"`
	PermissionID *uuid.UUID `json:"permission_id"`
}

func (q *Queries) UpsertCoreMenu(ctx context.Context, arg UpsertCoreMenuParams) (UpsertCoreMenuRow, error) {
	row := q.db.QueryRow(ctx, upsertCoreMenu,
		arg.ParentID,
		arg.PermissionID,
		arg.Code,
		arg.Title,
		arg.MenuType,
		arg.RoutePath,
		arg.ComponentKey,
		arg.Icon,
		arg.Affix,
		arg.SortOrder,
		arg.Metadata,
	)
	var i UpsertCoreMenuRow
	err := row.Scan(&i.ID, &i.PermissionID)
	return i, err
}
