// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mobile_profile.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMobileUnreadNotifications = `-- name: CountMobileUnreadNotifications :one
SELECT count(*)
FROM notify.recipients r
JOIN notify.messages m ON m.tenant_id = r.tenant_id AND m.id = r.message_id
WHERE r.tenant_id = $1
  AND r.app_id = $2
  AND r.user_id = $3
  AND r.delivery_status = 'delivered'
  AND r.read_at IS NULL
  AND r.archived_at IS NULL
  AND m.status = 'published'
  AND m.app_id = $2
  AND m.deleted_at IS NULL
  AND (m.expires_at IS NULL OR m.expires_at > now())
`

type CountMobileUnreadNotificationsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	AppID    uuid.UUID `json:"app_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) CountMobileUnreadNotifications(ctx context.Context, arg CountMobileUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMobileUnreadNotifications, arg.TenantID, arg.AppID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMobilePreferences = `-- name: GetMobilePreferences :one
SELECT COALESCE(p.locale, u.locale) AS locale,
       COALESCE(p.appearance, 'system') AS appearance,
       COALESCE(p.notification_preferences, '{"in_app":true,"push":false,"email":true}'::jsonb) AS notification_preferences
FROM iam.users u
LEFT JOIN iam.user_preferences p ON p.user_id = u.id AND p.app_id = $1
WHERE u.id = $2 AND u.deleted_at IS NULL
`

type GetMobilePreferencesParams struct {
	AppID  uuid.UUID `json:"app_id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetMobilePreferencesRow struct {
	Locale                  string `json:"locale"`
	Appearance              string `json:"appearance"`
	NotificationPreferences []byte `json:"notification_preferences"`
}

func (q *Queries) GetMobilePreferences(ctx context.Context, arg GetMobilePreferencesParams) (GetMobilePreferencesRow, error) {
	row := q.db.QueryRow(ctx, getMobilePreferences, arg.AppID, arg.UserID)
	var i GetMobilePreferencesRow
	err := row.Scan(&i.Locale, &i.Appearance, &i.NotificationPreferences)
	return i, err
}

const listMobileLoginEvents = `-- name: ListMobileLoginEvents :many
SELECT id, auth_method, result, occurred_at, client_ip
FROM audit.login_events
WHERE user_id = $1 AND app_id = $2 AND audience = 'ak-mobile'
ORDER BY occurred_at DESC, id DESC
LIMIT 100
`

type ListMobileLoginEventsParams struct {
	UserID *uuid.UUID `json:"user_id"`
	AppID  *uuid.UUID `json:"app_id"`
}

type ListMobileLoginEventsRow struct {
	ID         uuid.UUID          `json:"id"`
	AuthMethod string             `json:"auth_method"`
	Result     string             `json:"result"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ClientIp   *netip.Addr        `json:"client_ip"`
}

func (q *Queries) ListMobileLoginEvents(ctx context.Context, arg ListMobileLoginEventsParams) ([]ListMobileLoginEventsRow, error) {
	rows, err := q.db.Query(ctx, listMobileLoginEvents, arg.UserID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMobileLoginEventsRow{}
	for rows.Next() {
		var i ListMobileLoginEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthMethod,
			&i.Result,
			&i.OccurredAt,
			&i.ClientIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMobileNotifications = `-- name: ListMobileNotifications :many
SELECT m.id, m.title, m.body, m.body_format, m.message_type, m.created_at, r.read_at
FROM notify.recipients r
JOIN notify.messages m ON m.tenant_id = r.tenant_id AND m.id = r.message_id
WHERE r.tenant_id = $1
  AND r.app_id = $2
  AND r.user_id = $3
  AND r.archived_at IS NULL
  AND r.delivery_status = 'delivered'
  AND m.status = 'published'
  AND m.app_id = $2
  AND m.deleted_at IS NULL
  AND (m.expires_at IS NULL OR m.expires_at > now())
  AND (m.created_at, m.id) < ($4, $5::uuid)
ORDER BY m.created_at DESC, m.id DESC
LIMIT $6
`

type ListMobileNotificationsParams struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	AppID           uuid.UUID          `json:"app_id"`
	UserID          uuid.UUID          `json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListMobileNotificationsRow struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	BodyFormat  string             `json:"body_format"`
	MessageType string             `json:"message_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ReadAt      pgtype.Timestamptz `json:"read_at"`
}

func (q *Queries) ListMobileNotifications(ctx context.Context, arg ListMobileNotificationsParams) ([]ListMobileNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listMobileNotifications,
		arg.TenantID,
		arg.AppID,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMobileNotificationsRow{}
	for rows.Next() {
		var i ListMobileNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.BodyFormat,
			&i.MessageType,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMobileSecurityEvents = `-- name: ListMobileSecurityEvents :many
SELECT id, event_type, severity, occurred_at
FROM audit.security_events
WHERE user_id = $1 AND app_id = $2
ORDER BY occurred_at DESC, id DESC
LIMIT 100
`

type ListMobileSecurityEventsParams struct {
	UserID *uuid.UUID `json:"user_id"`
	AppID  *uuid.UUID `json:"app_id"`
}

type ListMobileSecurityEventsRow struct {
	ID         uuid.UUID          `json:"id"`
	EventType  string             `json:"event_type"`
	Severity   string             `json:"severity"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListMobileSecurityEvents(ctx context.Context, arg ListMobileSecurityEventsParams) ([]ListMobileSecurityEventsRow, error) {
	rows, err := q.db.Query(ctx, listMobileSecurityEvents, arg.UserID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMobileSecurityEventsRow{}
	for rows.Next() {
		var i ListMobileSecurityEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Severity,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMobileNotificationRead = `-- name: MarkMobileNotificationRead :execrows
UPDATE notify.recipients
SET read_at = COALESCE(read_at, now())
WHERE tenant_id = $1
  AND app_id = $2
  AND user_id = $3
  AND message_id = $4
  AND delivery_status = 'delivered'
  AND archived_at IS NULL
`

type MarkMobileNotificationReadParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	AppID     uuid.UUID `json:"app_id"`
	UserID    uuid.UUID `json:"user_id"`
	MessageID uuid.UUID `json:"message_id"`
}

func (q *Queries) MarkMobileNotificationRead(ctx context.Context, arg MarkMobileNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMobileNotificationRead,
		arg.TenantID,
		arg.AppID,
		arg.UserID,
		arg.MessageID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertMobilePreferences = `-- name: UpsertMobilePreferences :exec
INSERT INTO iam.user_preferences (app_id, user_id, locale, appearance, notification_preferences)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (app_id, user_id) DO UPDATE
SET locale = EXCLUDED.locale,
    appearance = EXCLUDED.appearance,
    notification_preferences = EXCLUDED.notification_preferences
`

type UpsertMobilePreferencesParams struct {
	AppID                   uuid.UUID `json:"app_id"`
	UserID                  uuid.UUID `json:"user_id"`
	Locale                  string    `json:"locale"`
	Appearance              string    `json:"appearance"`
	NotificationPreferences []byte    `json:"notification_preferences"`
}

func (q *Queries) UpsertMobilePreferences(ctx context.Context, arg UpsertMobilePreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertMobilePreferences,
		arg.AppID,
		arg.UserID,
		arg.Locale,
		arg.Appearance,
		arg.NotificationPreferences,
	)
	return err
}
