// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppApplication struct {
	ID                       uuid.UUID          `json:"id"`
	TenantID                 uuid.UUID          `json:"tenant_id"`
	Code                     string             `json:"code"`
	Name                     string             `json:"name"`
	Status                   string             `json:"status"`
	DefaultLocale            string             `json:"default_locale"`
	RegistrationEnabled      bool               `json:"registration_enabled"`
	RegistrationVerification string             `json:"registration_verification"`
	IsDefault                bool               `json:"is_default"`
	LockVersion              int32              `json:"lock_version"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	Appid                    *string            `json:"appid"`
	AppidConfiguredAt        pgtype.Timestamptz `json:"appid_configured_at"`
	AppType                  string             `json:"app_type"`
	Description              string             `json:"description"`
	Introduction             string             `json:"introduction"`
	Remark                   string             `json:"remark"`
	CreatorUserID            *uuid.UUID         `json:"creator_user_id"`
	OwnerType                string             `json:"owner_type"`
	OwnerUserID              *uuid.UUID         `json:"owner_user_id"`
	OwnerTenantID            *uuid.UUID         `json:"owner_tenant_id"`
	IconFileID               *uuid.UUID         `json:"icon_file_id"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
}

type AppApplicationAsset struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	AppID     uuid.UUID          `json:"app_id"`
	FileID    uuid.UUID          `json:"file_id"`
	AssetType string             `json:"asset_type"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AppApplicationChannel struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	AppID        uuid.UUID          `json:"app_id"`
	ChannelCode  string             `json:"channel_code"`
	Name         string             `json:"name"`
	Url          *string            `json:"url"`
	AbmUrl       *string            `json:"abm_url"`
	QrcodeFileID *uuid.UUID         `json:"qrcode_file_id"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// App selection and runtime enablement of tenant login-provider configurations.
type AppApplicationLoginProviderBinding struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	AppID                 uuid.UUID          `json:"app_id"`
	ProviderCode          string             `json:"provider_code"`
	LoginProviderConfigID uuid.UUID          `json:"login_provider_config_id"`
	Enabled               bool               `json:"enabled"`
	SortOrder             int32              `json:"sort_order"`
	LockVersion           int32              `json:"lock_version"`
	CreatedBy             *uuid.UUID         `json:"created_by"`
	UpdatedBy             *uuid.UUID         `json:"updated_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AppApplicationLoginSetting struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	AppID           uuid.UUID          `json:"app_id"`
	OtpLoginEnabled bool               `json:"otp_login_enabled"`
	EmailOtpEnabled bool               `json:"email_otp_enabled"`
	SmsOtpEnabled   bool               `json:"sms_otp_enabled"`
	LockVersion     int32              `json:"lock_version"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	UpdatedBy       *uuid.UUID         `json:"updated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AppApplicationOnboardingDraftAsset struct {
	TenantID           uuid.UUID          `json:"tenant_id"`
	AppID              uuid.UUID          `json:"app_id"`
	SlideID            uuid.UUID          `json:"slide_id"`
	Locale             string             `json:"locale"`
	FileID             uuid.UUID          `json:"file_id"`
	AccessibilityLabel string             `json:"accessibility_label"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AppApplicationOnboardingDraftSlide struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	AppID     uuid.UUID          `json:"app_id"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AppApplicationOnboardingRevision struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	AppID            uuid.UUID          `json:"app_id"`
	Version          int32              `json:"version"`
	SourceGeneration int32              `json:"source_generation"`
	PublishedBy      *uuid.UUID         `json:"published_by"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
}

type AppApplicationOnboardingRevisionAsset struct {
	TenantID           uuid.UUID          `json:"tenant_id"`
	AppID              uuid.UUID          `json:"app_id"`
	RevisionID         uuid.UUID          `json:"revision_id"`
	SlideID            uuid.UUID          `json:"slide_id"`
	Locale             string             `json:"locale"`
	FileID             uuid.UUID          `json:"file_id"`
	AccessibilityLabel string             `json:"accessibility_label"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AppApplicationOnboardingRevisionSlide struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	AppID      uuid.UUID          `json:"app_id"`
	RevisionID uuid.UUID          `json:"revision_id"`
	Position   int32              `json:"position"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AppApplicationPublicWebConfig struct {
	TenantID         uuid.UUID          `json:"tenant_id"`
	AppID            uuid.UUID          `json:"app_id"`
	Enabled          bool               `json:"enabled"`
	ApkEnabled       bool               `json:"apk_enabled"`
	LockVersion      int32              `json:"lock_version"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	PromotionEnabled bool               `json:"promotion_enabled"`
}

type AppApplicationPublicWebTranslation struct {
	TenantID             uuid.UUID `json:"tenant_id"`
	AppID                uuid.UUID `json:"app_id"`
	Locale               string    `json:"locale"`
	Name                 string    `json:"name"`
	Introduction         string    `json:"introduction"`
	PromotionTitle       string    `json:"promotion_title"`
	PromotionDescription string    `json:"promotion_description"`
	PromotionButtonLabel string    `json:"promotion_button_label"`
}

type AppApplicationScannerConfig struct {
	TenantID            uuid.UUID          `json:"tenant_id"`
	AppID               uuid.UUID          `json:"app_id"`
	WebviewEnabled      bool               `json:"webview_enabled"`
	AllowedHostPatterns []string           `json:"allowed_host_patterns"`
	LockVersion         int32              `json:"lock_version"`
	CreatedBy           *uuid.UUID         `json:"created_by"`
	UpdatedBy           *uuid.UUID         `json:"updated_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AppApplicationShareBinding struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	AppID         uuid.UUID          `json:"app_id"`
	ProviderCode  string             `json:"provider_code"`
	ShareConfigID uuid.UUID          `json:"share_config_id"`
	Enabled       bool               `json:"enabled"`
	Scenes        []string           `json:"scenes"`
	ShareOrigin   string             `json:"share_origin"`
	FallbackMode  string             `json:"fallback_mode"`
	LockVersion   int32              `json:"lock_version"`
	CreatedBy     *uuid.UUID         `json:"created_by"`
	UpdatedBy     *uuid.UUID         `json:"updated_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AppApplicationStartupConfig struct {
	TenantID            uuid.UUID          `json:"tenant_id"`
	AppID               uuid.UUID          `json:"app_id"`
	OnboardingEnabled   bool               `json:"onboarding_enabled"`
	DraftGeneration     int32              `json:"draft_generation"`
	PublishedVersion    int32              `json:"published_version"`
	PublishedRevisionID *uuid.UUID         `json:"published_revision_id"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	PublishedBy         *uuid.UUID         `json:"published_by"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AppApplicationStartupTranslation struct {
	TenantID    uuid.UUID          `json:"tenant_id"`
	AppID       uuid.UUID          `json:"app_id"`
	Locale      string             `json:"locale"`
	DisplayName string             `json:"display_name"`
	Subtitle    string             `json:"subtitle"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AppApplicationStoreListing struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	AppID     uuid.UUID          `json:"app_id"`
	Name      string             `json:"name"`
	Scheme    string             `json:"scheme"`
	Enabled   bool               `json:"enabled"`
	Priority  int32              `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Platform  *string            `json:"platform"`
	WebUrl    string             `json:"web_url"`
}

type AppApplicationTeamMember struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	AppID     uuid.UUID          `json:"app_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AppFeedback struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	AppID          uuid.UUID          `json:"app_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Description    string             `json:"description"`
	Contact        string             `json:"contact"`
	Platform       string             `json:"platform"`
	AppVersion     string             `json:"app_version"`
	Status         string             `json:"status"`
	IdempotencyKey uuid.UUID          `json:"idempotency_key"`
	RequestHash    []byte             `json:"request_hash"`
	LockVersion    int32              `json:"lock_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AppFeedbackAttachment struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	AppID      uuid.UUID `json:"app_id"`
	FeedbackID uuid.UUID `json:"feedback_id"`
	FileID     uuid.UUID `json:"file_id"`
	Position   int32     `json:"position"`
}

type AppFeedbackEvent struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	AppID      uuid.UUID          `json:"app_id"`
	FeedbackID uuid.UUID          `json:"feedback_id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	FromStatus string             `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AppFeedbackReply struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	AppID          uuid.UUID          `json:"app_id"`
	FeedbackID     uuid.UUID          `json:"feedback_id"`
	AuthorID       *uuid.UUID         `json:"author_id"`
	Body           string             `json:"body"`
	IdempotencyKey uuid.UUID          `json:"idempotency_key"`
	RequestHash    []byte             `json:"request_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AppLegalConsent struct {
	ID           uuid.UUID          `json:"id"`
	AppID        uuid.UUID          `json:"app_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	UserID       *uuid.UUID         `json:"user_id"`
	PageType     string             `json:"page_type"`
	RevisionID   uuid.UUID          `json:"revision_id"`
	ContentHash  []byte             `json:"content_hash"`
	Locale       string             `json:"locale"`
	AcceptedAt   pgtype.Timestamptz `json:"accepted_at"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    *string            `json:"user_agent"`
	AnonymizedAt pgtype.Timestamptz `json:"anonymized_at"`
}

// App-scoped email/mobile identifiers used by Mobile login and account binding.
type AppUserLoginIdentifier struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	AppID           uuid.UUID          `json:"app_id"`
	UserID          uuid.UUID          `json:"user_id"`
	IdentifierType  string             `json:"identifier_type"`
	NormalizedValue string             `json:"normalized_value"`
	DisplayHint     string             `json:"display_hint"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	Status          string             `json:"status"`
	LockVersion     int32              `json:"lock_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AppUserMembership struct {
	AppID       uuid.UUID          `json:"app_id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Source      string             `json:"source"`
	Status      string             `json:"status"`
	InvitedBy   *uuid.UUID         `json:"invited_by"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	LockVersion int32              `json:"lock_version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Authentication success/failure/block events for security review.
type AuditLoginEvent struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            *uuid.UUID         `json:"tenant_id"`
	UserID              *uuid.UUID         `json:"user_id"`
	SessionID           *uuid.UUID         `json:"session_id"`
	RequestID           *string            `json:"request_id"`
	LoginIdentifierHash []byte             `json:"login_identifier_hash"`
	LoginIdentifierHint *string            `json:"login_identifier_hint"`
	AuthMethod          string             `json:"auth_method"`
	Audience            string             `json:"audience"`
	Result              string             `json:"result"`
	FailureReason       *string            `json:"failure_reason"`
	ClientIp            *netip.Addr        `json:"client_ip"`
	UserAgent           *string            `json:"user_agent"`
	DeviceInfo          []byte             `json:"device_info"`
	GeoInfo             []byte             `json:"geo_info"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	AppID               *uuid.UUID         `json:"app_id"`
}

// Immutable, redacted business-operation audit log; not a replacement for application logs in an observability backend.
type AuditOperationLog struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       *uuid.UUID         `json:"tenant_id"`
	UserID         *uuid.UUID         `json:"user_id"`
	SessionID      *uuid.UUID         `json:"session_id"`
	RequestID      string             `json:"request_id"`
	TraceID        *string            `json:"trace_id"`
	ModuleCode     string             `json:"module_code"`
	ActionName     string             `json:"action_name"`
	PermissionCode *string            `json:"permission_code"`
	ResourceType   *string            `json:"resource_type"`
	ResourceID     *string            `json:"resource_id"`
	HttpMethod     *string            `json:"http_method"`
	RequestPath    *string            `json:"request_path"`
	ResponseStatus *int32             `json:"response_status"`
	ClientIp       *netip.Addr        `json:"client_ip"`
	UserAgent      *string            `json:"user_agent"`
	RequestSummary []byte             `json:"request_summary"`
	BeforeData     []byte             `json:"before_data"`
	AfterData      []byte             `json:"after_data"`
	DurationMs     *int32             `json:"duration_ms"`
	Succeeded      bool               `json:"succeeded"`
	ErrorCode      *string            `json:"error_code"`
	ErrorMessage   *string            `json:"error_message"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	AppID          *uuid.UUID         `json:"app_id"`
}

type AuditPrivacyErasureEvent struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	AppID                 uuid.UUID          `json:"app_id"`
	ActionCode            string             `json:"action_code"`
	Scope                 string             `json:"scope"`
	Status                string             `json:"status"`
	GlobalIdentityDeleted bool               `json:"global_identity_deleted"`
	ErasedCounts          []byte             `json:"erased_counts"`
	RequestedAt           pgtype.Timestamptz `json:"requested_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
}

type AuditPrivacyErasureObject struct {
	ID            uuid.UUID          `json:"id"`
	EventID       uuid.UUID          `json:"event_id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	Provider      string             `json:"provider"`
	BucketName    string             `json:"bucket_name"`
	ObjectKey     string             `json:"object_key"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	LastErrorCode *string            `json:"last_error_code"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuditSecurityEvent struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   *uuid.UUID         `json:"tenant_id"`
	UserID     *uuid.UUID         `json:"user_id"`
	SessionID  *uuid.UUID         `json:"session_id"`
	EventType  string             `json:"event_type"`
	Severity   string             `json:"severity"`
	Source     string             `json:"source"`
	ClientIp   *netip.Addr        `json:"client_ip"`
	Details    []byte             `json:"details"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy *uuid.UUID         `json:"resolved_by"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	AppID      *uuid.UUID         `json:"app_id"`
}

type BillingPaymentOrder struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	UserID       *uuid.UUID         `json:"user_id"`
	OrderNumber  string             `json:"order_number"`
	BusinessType string             `json:"business_type"`
	BusinessID   *uuid.UUID         `json:"business_id"`
	Subject      string             `json:"subject"`
	Description  *string            `json:"description"`
	Currency     string             `json:"currency"`
	AmountMinor  int64              `json:"amount_minor"`
	Status       string             `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	PaidAt       pgtype.Timestamptz `json:"paid_at"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type BillingPaymentTransaction struct {
	ID                    uuid.UUID          `json:"id"`
	PaymentOrderID        uuid.UUID          `json:"payment_order_id"`
	TransactionNumber     string             `json:"transaction_number"`
	Gateway               string             `json:"gateway"`
	Channel               string             `json:"channel"`
	ProviderAccount       *string            `json:"provider_account"`
	ProviderTransactionID *string            `json:"provider_transaction_id"`
	Currency              string             `json:"currency"`
	AmountMinor           int64              `json:"amount_minor"`
	Status                string             `json:"status"`
	RequestPayload        []byte             `json:"request_payload"`
	ResponsePayload       []byte             `json:"response_payload"`
	CallbackPayload       []byte             `json:"callback_payload"`
	ClientIp              *netip.Addr        `json:"client_ip"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type BillingRefund struct {
	ID                   uuid.UUID          `json:"id"`
	PaymentOrderID       uuid.UUID          `json:"payment_order_id"`
	PaymentTransactionID *uuid.UUID         `json:"payment_transaction_id"`
	RefundNumber         string             `json:"refund_number"`
	ProviderRefundID     *string            `json:"provider_refund_id"`
	Currency             string             `json:"currency"`
	AmountMinor          int64              `json:"amount_minor"`
	Reason               *string            `json:"reason"`
	Status               string             `json:"status"`
	RequestedBy          *uuid.UUID         `json:"requested_by"`
	ProcessedAt          pgtype.Timestamptz `json:"processed_at"`
	ResponsePayload      []byte             `json:"response_payload"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type BillingWalletAccount struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	UserID       uuid.UUID          `json:"user_id"`
	AssetCode    string             `json:"asset_code"`
	AccountType  string             `json:"account_type"`
	BalanceMinor int64              `json:"balance_minor"`
	FrozenMinor  int64              `json:"frozen_minor"`
	LockVersion  int32              `json:"lock_version"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Immutable wallet/points ledger. Corrections are compensating entries, never UPDATE or DELETE.
type BillingWalletLedgerEntry struct {
	ID              uuid.UUID          `json:"id"`
	WalletAccountID uuid.UUID          `json:"wallet_account_id"`
	EntryNumber     string             `json:"entry_number"`
	EntryType       string             `json:"entry_type"`
	Direction       string             `json:"direction"`
	AmountMinor     int64              `json:"amount_minor"`
	BalanceBefore   int64              `json:"balance_before"`
	BalanceAfter    int64              `json:"balance_after"`
	BusinessType    string             `json:"business_type"`
	BusinessID      *uuid.UUID         `json:"business_id"`
	IdempotencyKey  string             `json:"idempotency_key"`
	Remark          *string            `json:"remark"`
	OperatorUserID  *uuid.UUID         `json:"operator_user_id"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

type BillingWithdrawal struct {
	ID               uuid.UUID          `json:"id"`
	WalletAccountID  uuid.UUID          `json:"wallet_account_id"`
	WithdrawalNumber string             `json:"withdrawal_number"`
	AmountMinor      int64              `json:"amount_minor"`
	FeeMinor         int64              `json:"fee_minor"`
	PayoutMinor      *int64             `json:"payout_minor"`
	PayoutMethod     string             `json:"payout_method"`
	PayoutTargetEnc  []byte             `json:"payout_target_enc"`
	PayoutKeyVersion int32              `json:"payout_key_version"`
	Status           string             `json:"status"`
	Reason           *string            `json:"reason"`
	HandledBy        *uuid.UUID         `json:"handled_by"`
	HandledAt        pgtype.Timestamptz `json:"handled_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ContentArticle struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	CategoryID           *uuid.UUID         `json:"category_id"`
	Slug                 string             `json:"slug"`
	Status               string             `json:"status"`
	Featured             bool               `json:"featured"`
	SortOrder            int32              `json:"sort_order"`
	CoverFileID          *uuid.UUID         `json:"cover_file_id"`
	ReadingMinutes       int16              `json:"reading_minutes"`
	LockVersion          int32              `json:"lock_version"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	CreatedBy            *uuid.UUID         `json:"created_by"`
	UpdatedBy            *uuid.UUID         `json:"updated_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	AppID                uuid.UUID          `json:"app_id"`
	ContentType          string             `json:"content_type"`
	TopicID              *uuid.UUID         `json:"topic_id"`
	AllowComments        bool               `json:"allow_comments"`
	Pinned               bool               `json:"pinned"`
	IsLatest             bool               `json:"is_latest"`
	VideoSourceType      *string            `json:"video_source_type"`
	VideoFileID          *uuid.UUID         `json:"video_file_id"`
	VideoExternalUrl     *string            `json:"video_external_url"`
	VideoDurationSeconds *int32             `json:"video_duration_seconds"`
}

type ContentArticleBookmark struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	UserID    uuid.UUID          `json:"user_id"`
	ArticleID uuid.UUID          `json:"article_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	AppID     uuid.UUID          `json:"app_id"`
}

type ContentArticleCategory struct {
	TenantID   uuid.UUID          `json:"tenant_id"`
	AppID      uuid.UUID          `json:"app_id"`
	ArticleID  uuid.UUID          `json:"article_id"`
	CategoryID uuid.UUID          `json:"category_id"`
	SortOrder  int16              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ContentArticleMediaTranslation struct {
	MediaID uuid.UUID `json:"media_id"`
	Locale  string    `json:"locale"`
	AltText string    `json:"alt_text"`
}

type ContentArticleMedium struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	AppID     uuid.UUID          `json:"app_id"`
	ArticleID uuid.UUID          `json:"article_id"`
	FileID    uuid.UUID          `json:"file_id"`
	Role      string             `json:"role"`
	SortOrder int16              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ContentArticleTag struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	AppID     uuid.UUID          `json:"app_id"`
	ArticleID uuid.UUID          `json:"article_id"`
	TagID     uuid.UUID          `json:"tag_id"`
	SortOrder int16              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ContentArticleTranslation struct {
	ArticleID  uuid.UUID `json:"article_id"`
	Locale     string    `json:"locale"`
	Title      string    `json:"title"`
	Summary    string    `json:"summary"`
	BodyFormat string    `json:"body_format"`
	Body       []byte    `json:"body"`
	SearchText string    `json:"search_text"`
}

type ContentBlockedUser struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	AppID     uuid.UUID          `json:"app_id"`
	BlockerID uuid.UUID          `json:"blocker_id"`
	BlockedID uuid.UUID          `json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ContentCategory struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Slug        string             `json:"slug"`
	Status      string             `json:"status"`
	SortOrder   int32              `json:"sort_order"`
	LockVersion int32              `json:"lock_version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AppID       uuid.UUID          `json:"app_id"`
	ParentID    *uuid.UUID         `json:"parent_id"`
	ImageFileID *uuid.UUID         `json:"image_file_id"`
}

type ContentCategoryTranslation struct {
	CategoryID  uuid.UUID `json:"category_id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type ContentComment struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	AppID            uuid.UUID          `json:"app_id"`
	ArticleID        uuid.UUID          `json:"article_id"`
	AuthorID         uuid.UUID          `json:"author_id"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	RootID           *uuid.UUID         `json:"root_id"`
	Status           string             `json:"status"`
	Body             string             `json:"body"`
	BodyFingerprint  []byte             `json:"body_fingerprint"`
	ModerationReason *string            `json:"moderation_reason"`
	ModeratedBy      *uuid.UUID         `json:"moderated_by"`
	ModeratedAt      pgtype.Timestamptz `json:"moderated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ContentCommentReport struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	AppID      uuid.UUID          `json:"app_id"`
	CommentID  uuid.UUID          `json:"comment_id"`
	ReporterID uuid.UUID          `json:"reporter_id"`
	Reason     string             `json:"reason"`
	Details    string             `json:"details"`
	Status     string             `json:"status"`
	Resolution string             `json:"resolution"`
	ResolvedBy *uuid.UUID         `json:"resolved_by"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ContentPage struct {
	ID                uuid.UUID          `json:"id"`
	AppID             uuid.UUID          `json:"app_id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	Slug              string             `json:"slug"`
	PageType          string             `json:"page_type"`
	Status            string             `json:"status"`
	CurrentRevisionID *uuid.UUID         `json:"current_revision_id"`
	LockVersion       int32              `json:"lock_version"`
	CreatedBy         *uuid.UUID         `json:"created_by"`
	UpdatedBy         *uuid.UUID         `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ContentPageRevision struct {
	ID             uuid.UUID          `json:"id"`
	PageID         uuid.UUID          `json:"page_id"`
	AppID          uuid.UUID          `json:"app_id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	RevisionNumber int32              `json:"revision_number"`
	ContentHash    []byte             `json:"content_hash"`
	Status         string             `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedBy      *uuid.UUID         `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ContentPageRevisionTranslation struct {
	RevisionID uuid.UUID `json:"revision_id"`
	Locale     string    `json:"locale"`
	Title      string    `json:"title"`
	BodyFormat string    `json:"body_format"`
	Body       []byte    `json:"body"`
}

type ContentSensitiveWord struct {
	TenantID       uuid.UUID          `json:"tenant_id"`
	AppID          uuid.UUID          `json:"app_id"`
	Word           string             `json:"word"`
	NormalizedWord string             `json:"normalized_word"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ContentTag struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	AppID          uuid.UUID          `json:"app_id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	Status         string             `json:"status"`
	LockVersion    int32              `json:"lock_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ContentTopic struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	AppID       uuid.UUID          `json:"app_id"`
	Slug        string             `json:"slug"`
	Status      string             `json:"status"`
	SortOrder   int32              `json:"sort_order"`
	CoverFileID *uuid.UUID         `json:"cover_file_id"`
	LockVersion int32              `json:"lock_version"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ContentTopicTranslation struct {
	TopicID     uuid.UUID `json:"topic_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type ContentVideoExternalHost struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	AppID     uuid.UUID          `json:"app_id"`
	Hostname  string             `json:"hostname"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// App-scoped external identities for Mobile; independent from Admin iam.oauth_accounts.
type IamAppOauthAccount struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	AppID               uuid.UUID          `json:"app_id"`
	UserID              uuid.UUID          `json:"user_id"`
	ProviderCode        string             `json:"provider_code"`
	Issuer              string             `json:"issuer"`
	ExternalClientID    string             `json:"external_client_id"`
	Subject             string             `json:"subject"`
	UnionSubject        *string            `json:"union_subject"`
	ProviderUsername    *string            `json:"provider_username"`
	ProviderProfile     []byte             `json:"provider_profile"`
	Status              string             `json:"status"`
	BoundAt             pgtype.Timestamptz `json:"bound_at"`
	LastAuthenticatedAt pgtype.Timestamptz `json:"last_authenticated_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type IamBlockRule struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     *uuid.UUID         `json:"tenant_id"`
	SubjectType  string             `json:"subject_type"`
	SubjectValue string             `json:"subject_value"`
	Action       string             `json:"action"`
	Reason       *string            `json:"reason"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Status       string             `json:"status"`
	CreatedBy    *uuid.UUID         `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type IamDevice struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	DeviceKey    string             `json:"device_key"`
	DeviceName   *string            `json:"device_name"`
	Platform     string             `json:"platform"`
	Model        *string            `json:"model"`
	OsVersion    *string            `json:"os_version"`
	AppVersion   *string            `json:"app_version"`
	TrustedUntil pgtype.Timestamptz `json:"trusted_until"`
	LastIp       *netip.Addr        `json:"last_ip"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type IamLoginCaptchaChallenge struct {
	ID           uuid.UUID          `json:"id"`
	ScopeHash    []byte             `json:"scope_hash"`
	AttemptCount int16              `json:"attempt_count"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CaptchaType  string             `json:"captcha_type"`
	ProofHash    []byte             `json:"proof_hash"`
}

type IamLoginFailureState struct {
	ScopeHash    []byte             `json:"scope_hash"`
	FailureCount int32              `json:"failure_count"`
	LastFailedAt pgtype.Timestamptz `json:"last_failed_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type IamMfaFactor struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	FactorType      string             `json:"factor_type"`
	DisplayName     *string            `json:"display_name"`
	SecretEncrypted []byte             `json:"secret_encrypted"`
	CredentialID    []byte             `json:"credential_id"`
	PublicKey       []byte             `json:"public_key"`
	SignCount       int64              `json:"sign_count"`
	Status          string             `json:"status"`
	VerifiedAt      pgtype.Timestamptz `json:"verified_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type IamMfaRecoveryCode struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CodeHash  []byte             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IamOauthAccount struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Provider         string             `json:"provider"`
	Subject          string             `json:"subject"`
	UnionSubject     *string            `json:"union_subject"`
	ProviderUsername *string            `json:"provider_username"`
	ProviderProfile  []byte             `json:"provider_profile"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Short-lived hash/encrypted OAuth state with single-consumption semantics.
type IamOauthAuthorizationFlow struct {
	ID                         uuid.UUID          `json:"id"`
	TenantID                   uuid.UUID          `json:"tenant_id"`
	AppID                      uuid.UUID          `json:"app_id"`
	LoginProviderConfigID      uuid.UUID          `json:"login_provider_config_id"`
	ProviderCode               string             `json:"provider_code"`
	Mode                       string             `json:"mode"`
	Platform                   string             `json:"platform"`
	BuildVariant               string             `json:"build_variant"`
	UserID                     *uuid.UUID         `json:"user_id"`
	SessionID                  *uuid.UUID         `json:"session_id"`
	ReauthPurpose              *string            `json:"reauth_purpose"`
	TargetOauthAccountID       *uuid.UUID         `json:"target_oauth_account_id"`
	StateHash                  []byte             `json:"state_hash"`
	NonceHash                  []byte             `json:"nonce_hash"`
	PkceVerifierCiphertext     []byte             `json:"pkce_verifier_ciphertext"`
	PkceKeyVersion             *int32             `json:"pkce_key_version"`
	DeviceKeyHash              []byte             `json:"device_key_hash"`
	VerifiedIdentityCiphertext []byte             `json:"verified_identity_ciphertext"`
	VerifiedIdentityKeyVersion *int32             `json:"verified_identity_key_version"`
	CompletionTicketHash       []byte             `json:"completion_ticket_hash"`
	CompletionTicketExpiresAt  pgtype.Timestamptz `json:"completion_ticket_expires_at"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
	ProviderVerifiedAt         pgtype.Timestamptz `json:"provider_verified_at"`
	ConsumedAt                 pgtype.Timestamptz `json:"consumed_at"`
	FailureCount               int32              `json:"failure_count"`
	LastFailureCode            *string            `json:"last_failure_code"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type IamOauthBindingChallenge struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	Provider              string             `json:"provider"`
	StateHash             []byte             `json:"state_hash"`
	AuthorizationCodeHash []byte             `json:"authorization_code_hash"`
	PkceVerifierEncrypted []byte             `json:"pkce_verifier_encrypted"`
	PkceChallenge         string             `json:"pkce_challenge"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt            pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type IamPasswordHistory struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	PasswordHash      string             `json:"password_hash"`
	PasswordAlgorithm string             `json:"password_algorithm"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

// Stable permission catalog. Backend route code references permission codes; database route fields are documentation only.
type IamPermission struct {
	ID             uuid.UUID          `json:"id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	ModuleCode     string             `json:"module_code"`
	ResourceName   string             `json:"resource_name"`
	ActionName     string             `json:"action_name"`
	PermissionKind string             `json:"permission_kind"`
	HttpMethods    []string           `json:"http_methods"`
	RoutePattern   *string            `json:"route_pattern"`
	Description    *string            `json:"description"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Opaque rotating refresh tokens stored only as SHA-256 hashes; reuse revokes the session family.
type IamRefreshToken struct {
	ID                uuid.UUID          `json:"id"`
	SessionID         uuid.UUID          `json:"session_id"`
	TokenHash         []byte             `json:"token_hash"`
	ParentTokenID     *uuid.UUID         `json:"parent_token_id"`
	ReplacedByTokenID *uuid.UUID         `json:"replaced_by_token_id"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	ReuseDetectedAt   pgtype.Timestamptz `json:"reuse_detected_at"`
	CreatedIp         *netip.Addr        `json:"created_ip"`
}

type IamRole struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	ParentID    *uuid.UUID         `json:"parent_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	RoleType    string             `json:"role_type"`
	DataScope   string             `json:"data_scope"`
	SortOrder   int32              `json:"sort_order"`
	IsDefault   bool               `json:"is_default"`
	IsSystem    bool               `json:"is_system"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type IamRolePermission struct {
	TenantID     uuid.UUID          `json:"tenant_id"`
	RoleID       uuid.UUID          `json:"role_id"`
	PermissionID uuid.UUID          `json:"permission_id"`
	GrantedBy    *uuid.UUID         `json:"granted_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Custom organization data scope assigned to a role.
type IamRoleScopeUnit struct {
	TenantID           uuid.UUID          `json:"tenant_id"`
	RoleID             uuid.UUID          `json:"role_id"`
	UnitID             uuid.UUID          `json:"unit_id"`
	IncludeDescendants bool               `json:"include_descendants"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

// Revocable login session for mobile, admin web or machine API audiences.
type IamSession struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	TenantID           *uuid.UUID         `json:"tenant_id"`
	DeviceID           *uuid.UUID         `json:"device_id"`
	Audience           string             `json:"audience"`
	Status             string             `json:"status"`
	AccessTokenVersion int32              `json:"access_token_version"`
	MfaLevel           int16              `json:"mfa_level"`
	IpAddress          *netip.Addr        `json:"ip_address"`
	UserAgent          *string            `json:"user_agent"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	IdleExpiresAt      pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt  pgtype.Timestamptz `json:"absolute_expires_at"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason       *string            `json:"revoke_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	AppID              *uuid.UUID         `json:"app_id"`
}

type IamTenant struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	PlanCode  *string            `json:"plan_code"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type IamTenantMember struct {
	TenantID     uuid.UUID          `json:"tenant_id"`
	UserID       uuid.UUID          `json:"user_id"`
	MemberNumber *string            `json:"member_number"`
	DisplayName  *string            `json:"display_name"`
	Status       string             `json:"status"`
	InvitedBy    *uuid.UUID         `json:"invited_by"`
	InvitedAt    pgtype.Timestamptz `json:"invited_at"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
	LeftAt       pgtype.Timestamptz `json:"left_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Global user identity; tenant membership, credentials and OAuth accounts are normalized into separate tables.
type IamUser struct {
	ID               uuid.UUID          `json:"id"`
	Username         *string            `json:"username"`
	Email            *string            `json:"email"`
	Mobile           *string            `json:"mobile"`
	DisplayName      string             `json:"display_name"`
	RealName         *string            `json:"real_name"`
	AvatarFileID     *uuid.UUID         `json:"avatar_file_id"`
	Gender           string             `json:"gender"`
	Birthday         pgtype.Date        `json:"birthday"`
	Bio              *string            `json:"bio"`
	Locale           string             `json:"locale"`
	TimeZone         string             `json:"time_zone"`
	Status           string             `json:"status"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	MobileVerifiedAt pgtype.Timestamptz `json:"mobile_verified_at"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
	LockVersion      int32              `json:"lock_version"`
	IsSystem         bool               `json:"is_system"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type IamUserCredential struct {
	UserID              uuid.UUID          `json:"user_id"`
	PasswordHash        string             `json:"password_hash"`
	PasswordAlgorithm   string             `json:"password_algorithm"`
	PasswordVersion     int32              `json:"password_version"`
	PasswordChangedAt   pgtype.Timestamptz `json:"password_changed_at"`
	ForcePasswordChange bool               `json:"force_password_change"`
	FailedAttempts      int32              `json:"failed_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type IamUserPreference struct {
	UserID                  uuid.UUID          `json:"user_id"`
	Appearance              string             `json:"appearance"`
	NotificationPreferences []byte             `json:"notification_preferences"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	AppID                   uuid.UUID          `json:"app_id"`
	Locale                  string             `json:"locale"`
}

type IamUserRole struct {
	TenantID   uuid.UUID          `json:"tenant_id"`
	UserID     uuid.UUID          `json:"user_id"`
	RoleID     uuid.UUID          `json:"role_id"`
	ValidFrom  pgtype.Timestamptz `json:"valid_from"`
	ValidUntil pgtype.Timestamptz `json:"valid_until"`
	GrantedBy  *uuid.UUID         `json:"granted_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type IamVerificationChallenge struct {
	ID            uuid.UUID          `json:"id"`
	UserID        *uuid.UUID         `json:"user_id"`
	ChallengeType string             `json:"challenge_type"`
	TargetHash    []byte             `json:"target_hash"`
	TargetHint    *string            `json:"target_hint"`
	SecretHash    []byte             `json:"secret_hash"`
	Attempts      int32              `json:"attempts"`
	MaxAttempts   int32              `json:"max_attempts"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	CreatedIp     *netip.Addr        `json:"created_ip"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type JobsInboxEvent struct {
	ConsumerName string             `json:"consumer_name"`
	EventID      uuid.UUID          `json:"event_id"`
	EventType    string             `json:"event_type"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	Result       []byte             `json:"result"`
}

// Transactional outbox for external event publication. Internal background work is enqueued transactionally through River.
type JobsOutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      *uuid.UUID         `json:"tenant_id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   *uuid.UUID         `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	EventVersion  int32              `json:"event_version"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AttemptCount  int32              `json:"attempt_count"`
	LastError     *string            `json:"last_error"`
}

// Admin-managed schedules. handler_key must resolve to a worker registered in compiled Go code; no arbitrary shell command or code execution.
type JobsSchedule struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       *uuid.UUID         `json:"tenant_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	HandlerKey     string             `json:"handler_key"`
	CronExpression string             `json:"cron_expression"`
	TimeZone       string             `json:"time_zone"`
	Payload        []byte             `json:"payload"`
	QueueName      string             `json:"queue_name"`
	OverlapPolicy  string             `json:"overlap_policy"`
	MisfirePolicy  string             `json:"misfire_policy"`
	TimeoutSeconds int32              `json:"timeout_seconds"`
	MaxAttempts    int32              `json:"max_attempts"`
	Status         string             `json:"status"`
	LastEnqueuedAt pgtype.Timestamptz `json:"last_enqueued_at"`
	NextRunAt      pgtype.Timestamptz `json:"next_run_at"`
	CreatedBy      *uuid.UUID         `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type JobsScheduleRun struct {
	ID           uuid.UUID          `json:"id"`
	ScheduleID   uuid.UUID          `json:"schedule_id"`
	RiverJobID   *int64             `json:"river_job_id"`
	TriggerType  string             `json:"trigger_type"`
	Status       string             `json:"status"`
	Attempt      int32              `json:"attempt"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	WorkerID     *string            `json:"worker_id"`
	Output       []byte             `json:"output"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	// Opaque client idempotency key for manual execution; never reused as executable input.
	IdempotencyKey *string `json:"idempotency_key"`
}

type JobsTaskAttempt struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	AppID             *uuid.UUID         `json:"app_id"`
	TaskRunID         uuid.UUID          `json:"task_run_id"`
	AttemptNumber     int32              `json:"attempt_number"`
	Status            string             `json:"status"`
	ResultClass       *string            `json:"result_class"`
	ErrorCode         *string            `json:"error_code"`
	ErrorSummary      *string            `json:"error_summary"`
	ExternalRequestID *string            `json:"external_request_id"`
	TraceID           *string            `json:"trace_id"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	DurationMs        *int64             `json:"duration_ms"`
	NextRetryAt       pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type JobsTaskRun struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	AppID            *uuid.UUID         `json:"app_id"`
	ModuleCode       string             `json:"module_code"`
	TaskKind         string             `json:"task_kind"`
	QueueName        string             `json:"queue_name"`
	ResourceType     string             `json:"resource_type"`
	ResourceID       *uuid.UUID         `json:"resource_id"`
	CorrelationID    *uuid.UUID         `json:"correlation_id"`
	RiverJobID       *int64             `json:"river_job_id"`
	Status           string             `json:"status"`
	ScheduledAt      pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinalizedAt      pgtype.Timestamptz `json:"finalized_at"`
	NextRetryAt      pgtype.Timestamptz `json:"next_retry_at"`
	AttemptCount     int32              `json:"attempt_count"`
	MaxAttempts      int32              `json:"max_attempts"`
	LastResultClass  *string            `json:"last_result_class"`
	LastErrorCode    *string            `json:"last_error_code"`
	LastErrorSummary *string            `json:"last_error_summary"`
	TraceID          *string            `json:"trace_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type NotifyDelivery struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	MessageID           *uuid.UUID         `json:"message_id"`
	UserID              *uuid.UUID         `json:"user_id"`
	TemplateID          *uuid.UUID         `json:"template_id"`
	Channel             string             `json:"channel"`
	TargetCiphertext    []byte             `json:"target_ciphertext"`
	TargetHash          []byte             `json:"target_hash"`
	TargetHint          *string            `json:"target_hint"`
	TargetKeyVersion    int32              `json:"target_key_version"`
	Provider            *string            `json:"provider"`
	ProviderMessageID   *string            `json:"provider_message_id"`
	RenderedSubject     *string            `json:"rendered_subject"`
	RenderedBody        *string            `json:"rendered_body"`
	Status              string             `json:"status"`
	AttemptCount        int32              `json:"attempt_count"`
	MaxAttempts         int32              `json:"max_attempts"`
	ScheduledAt         pgtype.Timestamptz `json:"scheduled_at"`
	NextAttemptAt       pgtype.Timestamptz `json:"next_attempt_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	LastError           *string            `json:"last_error"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DedupeKey           *string            `json:"dedupe_key"`
	PayloadCiphertext   []byte             `json:"payload_ciphertext"`
	PayloadKeyVersion   *int32             `json:"payload_key_version"`
	Retryable           bool               `json:"retryable"`
	RetryRisk           string             `json:"retry_risk"`
	AppID               *uuid.UUID         `json:"app_id"`
	PushDeviceID        *uuid.UUID         `json:"push_device_id"`
	AcceptedAt          pgtype.Timestamptz `json:"accepted_at"`
	OpenedAt            pgtype.Timestamptz `json:"opened_at"`
	ProviderResult      *string            `json:"provider_result"`
	ErrorCode           *string            `json:"error_code"`
	MessageRunID        *uuid.UUID         `json:"message_run_id"`
	TaskRunID           *uuid.UUID         `json:"task_run_id"`
	DeliveryEnvironment string             `json:"delivery_environment"`
}

type NotifyDeliveryDailyMetric struct {
	MetricDate      pgtype.Date        `json:"metric_date"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	AppID           uuid.UUID          `json:"app_id"`
	Environment     string             `json:"environment"`
	Channel         string             `json:"channel"`
	Provider        string             `json:"provider"`
	MessageCategory string             `json:"message_category"`
	Outcome         string             `json:"outcome"`
	SkipReason      string             `json:"skip_reason"`
	EventCount      int64              `json:"event_count"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type NotifyMessage struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	SenderUserID    *uuid.UUID         `json:"sender_user_id"`
	MessageType     string             `json:"message_type"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	BodyFormat      string             `json:"body_format"`
	Status          string             `json:"status"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	AppID           uuid.UUID          `json:"app_id"`
	PushCategory    string             `json:"push_category"`
	PushTtlSeconds  int32              `json:"push_ttl_seconds"`
	PushCollapseKey *string            `json:"push_collapse_key"`
	PushRouteKey    *string            `json:"push_route_key"`
	PushRouteParams []byte             `json:"push_route_params"`
}

type NotifyMessageRun struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	AppID             uuid.UUID          `json:"app_id"`
	MessageID         uuid.UUID          `json:"message_id"`
	TriggerType       string             `json:"trigger_type"`
	Status            string             `json:"status"`
	RecipientCount    int64              `json:"recipient_count"`
	EvaluatedCount    int64              `json:"evaluated_count"`
	DeliveryCount     int64              `json:"delivery_count"`
	AcceptedCount     int64              `json:"accepted_count"`
	FailedCount       int64              `json:"failed_count"`
	InvalidTokenCount int64              `json:"invalid_token_count"`
	OpenedCount       int64              `json:"opened_count"`
	SkippedCount      int64              `json:"skipped_count"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type NotifyPushDevice struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	DeviceID        *uuid.UUID         `json:"device_id"`
	Provider        string             `json:"provider"`
	TokenHash       []byte             `json:"token_hash"`
	TokenCiphertext []byte             `json:"token_ciphertext"`
	KeyVersion      int32              `json:"key_version"`
	Status          string             `json:"status"`
	LastSuccessAt   pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt   pgtype.Timestamptz `json:"last_failure_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AppID           uuid.UUID          `json:"app_id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	Platform        string             `json:"platform"`
	BuildVariant    string             `json:"build_variant"`
	Locale          string             `json:"locale"`
	SdkVersion      string             `json:"sdk_version"`
	AppVersion      string             `json:"app_version"`
	RegisteredAt    pgtype.Timestamptz `json:"registered_at"`
	TokenUpdatedAt  pgtype.Timestamptz `json:"token_updated_at"`
	InvalidatedAt   pgtype.Timestamptz `json:"invalidated_at"`
	InvalidReason   *string            `json:"invalid_reason"`
}

type NotifyPushProviderConfig struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	AppID                 uuid.UUID          `json:"app_id"`
	Environment           string             `json:"environment"`
	Provider              string             `json:"provider"`
	ConfigSchemaVersion   int32              `json:"config_schema_version"`
	PublicConfig          []byte             `json:"public_config"`
	SecretCiphertext      []byte             `json:"secret_ciphertext"`
	SecretKeyVersion      *int32             `json:"secret_key_version"`
	SecretFieldNames      []string           `json:"secret_field_names"`
	CredentialFingerprint *string            `json:"credential_fingerprint"`
	Status                string             `json:"status"`
	LastPreflightAt       pgtype.Timestamptz `json:"last_preflight_at"`
	LastPreflightStatus   *string            `json:"last_preflight_status"`
	LastPreflightIssues   []byte             `json:"last_preflight_issues"`
	LockVersion           int32              `json:"lock_version"`
	CreatedBy             *uuid.UUID         `json:"created_by"`
	UpdatedBy             *uuid.UUID         `json:"updated_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type NotifyRecipient struct {
	TenantID        uuid.UUID          `json:"tenant_id"`
	MessageID       uuid.UUID          `json:"message_id"`
	UserID          uuid.UUID          `json:"user_id"`
	DeliveryStatus  string             `json:"delivery_status"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
	ReadAt          pgtype.Timestamptz `json:"read_at"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AppID           uuid.UUID          `json:"app_id"`
	PushSkipReason  *string            `json:"push_skip_reason"`
	PushEvaluatedAt pgtype.Timestamptz `json:"push_evaluated_at"`
	PushEnvironment *string            `json:"push_environment"`
}

type NotifySmsTemplateBinding struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	TemplateID         uuid.UUID          `json:"template_id"`
	Provider           string             `json:"provider"`
	ExternalTemplateID string             `json:"external_template_id"`
	SignName           *string            `json:"sign_name"`
	ParameterOrder     []byte             `json:"parameter_order"`
	Status             string             `json:"status"`
	Version            int32              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type NotifyTemplate struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        *uuid.UUID         `json:"tenant_id"`
	Code            string             `json:"code"`
	Name            string             `json:"name"`
	Channel         string             `json:"channel"`
	Locale          *string            `json:"locale"`
	SubjectTemplate *string            `json:"subject_template"`
	BodyTemplate    string             `json:"body_template"`
	VariablesSchema []byte             `json:"variables_schema"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	BodyFormat      string             `json:"body_format"`
	PushCategory    string             `json:"push_category"`
	PushTtlSeconds  int32              `json:"push_ttl_seconds"`
	PushCollapseKey *string            `json:"push_collapse_key"`
	PushRouteKey    *string            `json:"push_route_key"`
}

type OrgPosition struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

// Organization tree stored as an adjacency list. Descendant queries use PostgreSQL recursive CTEs; no duplicated level/tree strings.
type OrgUnit struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	ParentID     *uuid.UUID         `json:"parent_id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	UnitType     string             `json:"unit_type"`
	LeaderUserID *uuid.UUID         `json:"leader_user_id"`
	Phone        *string            `json:"phone"`
	Email        *string            `json:"email"`
	SortOrder    int32              `json:"sort_order"`
	Status       string             `json:"status"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type OrgUserPosition struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	UserID     uuid.UUID          `json:"user_id"`
	PositionID uuid.UUID          `json:"position_id"`
	UnitID     *uuid.UUID         `json:"unit_id"`
	IsPrimary  bool               `json:"is_primary"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OrgUserUnit struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	UserID    uuid.UUID          `json:"user_id"`
	UnitID    uuid.UUID          `json:"unit_id"`
	IsPrimary bool               `json:"is_primary"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Object storage metadata. Uploads use presigned URLs and post-upload validation/virus scanning.
type StorageFile struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	OwnerUserID  *uuid.UUID         `json:"owner_user_id"`
	Provider     string             `json:"provider"`
	BucketName   string             `json:"bucket_name"`
	ObjectKey    string             `json:"object_key"`
	OriginalName string             `json:"original_name"`
	MediaType    *string            `json:"media_type"`
	Extension    *string            `json:"extension"`
	SizeBytes    int64              `json:"size_bytes"`
	Sha256       []byte             `json:"sha256"`
	Etag         *string            `json:"etag"`
	Visibility   string             `json:"visibility"`
	Status       string             `json:"status"`
	ScanStatus   string             `json:"scan_status"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	AppID        *uuid.UUID         `json:"app_id"`
}

type StorageFileUsage struct {
	ID         uuid.UUID          `json:"id"`
	FileID     uuid.UUID          `json:"file_id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	ModuleCode string             `json:"module_code"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	FieldName  string             `json:"field_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type StorageUploadPart struct {
	UploadSessionID uuid.UUID          `json:"upload_session_id"`
	PartNumber      int32              `json:"part_number"`
	Etag            string             `json:"etag"`
	SizeBytes       int64              `json:"size_bytes"`
	ChecksumSha256  []byte             `json:"checksum_sha256"`
	UploadedAt      pgtype.Timestamptz `json:"uploaded_at"`
}

type StorageUploadSession struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	UserID           uuid.UUID          `json:"user_id"`
	FileID           *uuid.UUID         `json:"file_id"`
	Provider         string             `json:"provider"`
	ProviderUploadID *string            `json:"provider_upload_id"`
	BucketName       string             `json:"bucket_name"`
	ObjectKey        string             `json:"object_key"`
	OriginalName     string             `json:"original_name"`
	MediaType        *string            `json:"media_type"`
	ExpectedSize     int64              `json:"expected_size"`
	ExpectedSha256   []byte             `json:"expected_sha256"`
	PartSize         *int64             `json:"part_size"`
	Status           string             `json:"status"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AppID            *uuid.UUID         `json:"app_id"`
	Purpose          string             `json:"purpose"`
}

type SysApiClient struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	ClientID     string             `json:"client_id"`
	Name         string             `json:"name"`
	Description  *string            `json:"description"`
	AllowedCidrs []netip.Prefix     `json:"allowed_cidrs"`
	Status       string             `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedBy    *uuid.UUID         `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SysApiClientApp struct {
	TenantID    uuid.UUID          `json:"tenant_id"`
	ApiClientID uuid.UUID          `json:"api_client_id"`
	AppID       uuid.UUID          `json:"app_id"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SysApiClientPermission struct {
	TenantID     uuid.UUID          `json:"tenant_id"`
	ApiClientID  uuid.UUID          `json:"api_client_id"`
	PermissionID uuid.UUID          `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SysApiClientSecret struct {
	ID           uuid.UUID          `json:"id"`
	ApiClientID  uuid.UUID          `json:"api_client_id"`
	SecretPrefix string             `json:"secret_prefix"`
	SecretHash   []byte             `json:"secret_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
}

// Typed global or tenant configuration; secret values must be envelope-encrypted and never stored in value_json.
type SysConfigItem struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         *uuid.UUID         `json:"tenant_id"`
	ModuleCode       string             `json:"module_code"`
	ConfigGroup      string             `json:"config_group"`
	ConfigKey        string             `json:"config_key"`
	DisplayName      string             `json:"display_name"`
	ValueType        string             `json:"value_type"`
	ValueJson        []byte             `json:"value_json"`
	DefaultValueJson []byte             `json:"default_value_json"`
	IsSecret         bool               `json:"is_secret"`
	SecretCiphertext []byte             `json:"secret_ciphertext"`
	SecretKeyVersion *int32             `json:"secret_key_version"`
	IsPublic         bool               `json:"is_public"`
	ValidationSchema []byte             `json:"validation_schema"`
	Description      *string            `json:"description"`
	SortOrder        int32              `json:"sort_order"`
	Status           string             `json:"status"`
	Version          int32              `json:"version"`
	CreatedBy        *uuid.UUID         `json:"created_by"`
	UpdatedBy        *uuid.UUID         `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SysDictItem struct {
	ID         uuid.UUID          `json:"id"`
	DictTypeID uuid.UUID          `json:"dict_type_id"`
	ItemValue  string             `json:"item_value"`
	Label      string             `json:"label"`
	Locale     *string            `json:"locale"`
	Color      *string            `json:"color"`
	CssClass   *string            `json:"css_class"`
	SortOrder  int32              `json:"sort_order"`
	IsDefault  bool               `json:"is_default"`
	Extra      []byte             `json:"extra"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	TenantID   *uuid.UUID         `json:"tenant_id"`
}

type SysDictType struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        *uuid.UUID         `json:"tenant_id"`
	Code            string             `json:"code"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	IsSystem        bool               `json:"is_system"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	NameKey         *string            `json:"name_key"`
	DescriptionKey  *string            `json:"description_key"`
	Visibility      string             `json:"visibility"`
	ExtensionPolicy string             `json:"extension_policy"`
}

type SysIdempotencyKey struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	IdentityType    string             `json:"identity_type"`
	IdentityID      uuid.UUID          `json:"identity_id"`
	IdempotencyKey  string             `json:"idempotency_key"`
	RequestHash     []byte             `json:"request_hash"`
	ResponseStatus  *int32             `json:"response_status"`
	ResponseHeaders []byte             `json:"response_headers"`
	ResponseBody    []byte             `json:"response_body"`
	LockedUntil     pgtype.Timestamptz `json:"locked_until"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

// Tenant-owned, code-registered third-party login configurations; secret plaintext is never returned or logged.
type SysLoginProviderConfig struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	Name                  string             `json:"name"`
	Description           string             `json:"description"`
	ProviderCode          string             `json:"provider_code"`
	ExternalClientID      string             `json:"external_client_id"`
	ConfigSchemaVersion   int32              `json:"config_schema_version"`
	PublicConfig          []byte             `json:"public_config"`
	SecretCiphertext      []byte             `json:"secret_ciphertext"`
	SecretKeyVersion      *int32             `json:"secret_key_version"`
	SecretFieldNames      []string           `json:"secret_field_names"`
	CredentialFingerprint *string            `json:"credential_fingerprint"`
	Status                string             `json:"status"`
	LastPreflightAt       pgtype.Timestamptz `json:"last_preflight_at"`
	LastPreflightStatus   *string            `json:"last_preflight_status"`
	LastPreflightIssues   []byte             `json:"last_preflight_issues"`
	LockVersion           int32              `json:"lock_version"`
	CreatedBy             *uuid.UUID         `json:"created_by"`
	UpdatedBy             *uuid.UUID         `json:"updated_by"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Admin navigation metadata. UI actions and API authorization are represented by iam.permissions, not encoded as menu rows.
type SysMenu struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       *uuid.UUID         `json:"tenant_id"`
	ParentID       *uuid.UUID         `json:"parent_id"`
	PermissionID   *uuid.UUID         `json:"permission_id"`
	Code           string             `json:"code"`
	Title          string             `json:"title"`
	MenuType       string             `json:"menu_type"`
	RouteName      *string            `json:"route_name"`
	RoutePath      *string            `json:"route_path"`
	ComponentKey   *string            `json:"component_key"`
	RedirectPath   *string            `json:"redirect_path"`
	Icon           *string            `json:"icon"`
	ExternalUrl    *string            `json:"external_url"`
	OpenMode       string             `json:"open_mode"`
	ActiveMenuCode *string            `json:"active_menu_code"`
	KeepAlive      bool               `json:"keep_alive"`
	Hidden         bool               `json:"hidden"`
	Affix          bool               `json:"affix"`
	AlwaysShow     bool               `json:"always_show"`
	SortOrder      int32              `json:"sort_order"`
	Status         string             `json:"status"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type SysMobileRelease struct {
	ID                   uuid.UUID          `json:"id"`
	Platform             string             `json:"platform"`
	CurrentVersion       string             `json:"current_version"`
	MinimumVersion       string             `json:"minimum_version"`
	UpgradeUrl           *string            `json:"upgrade_url"`
	ReleaseNotes         []byte             `json:"release_notes"`
	Active               bool               `json:"active"`
	LockVersion          int32              `json:"lock_version"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	AppID                uuid.UUID          `json:"app_id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	PackageType          string             `json:"package_type"`
	Version              string             `json:"version"`
	MinimumNativeVersion *string            `json:"minimum_native_version"`
	PackageFileID        *uuid.UUID         `json:"package_file_id"`
	ExternalUrl          *string            `json:"external_url"`
	CreateEnv            string             `json:"create_env"`
	IsSilently           bool               `json:"is_silently"`
	IsMandatory          bool               `json:"is_mandatory"`
	CreatedBy            *uuid.UUID         `json:"created_by"`
	EverPublishedAt      pgtype.Timestamptz `json:"ever_published_at"`
	LastPublishedAt      pgtype.Timestamptz `json:"last_published_at"`
	UnpublishedAt        pgtype.Timestamptz `json:"unpublished_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type SysMobileReleasePublication struct {
	TenantID    uuid.UUID          `json:"tenant_id"`
	AppID       uuid.UUID          `json:"app_id"`
	PackageType string             `json:"package_type"`
	Platform    string             `json:"platform"`
	ReleaseID   uuid.UUID          `json:"release_id"`
	PublishedBy *uuid.UUID         `json:"published_by"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type SysMobileReleaseStoreListing struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	AppID          uuid.UUID `json:"app_id"`
	ReleaseID      uuid.UUID `json:"release_id"`
	StoreListingID uuid.UUID `json:"store_listing_id"`
}

type SysMobileReleaseTarget struct {
	TenantID    uuid.UUID          `json:"tenant_id"`
	AppID       uuid.UUID          `json:"app_id"`
	ReleaseID   uuid.UUID          `json:"release_id"`
	PackageType string             `json:"package_type"`
	Platform    string             `json:"platform"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SysMobileReleaseTranslation struct {
	ReleaseID uuid.UUID `json:"release_id"`
	Locale    string    `json:"locale"`
	Title     string    `json:"title"`
	Contents  string    `json:"contents"`
}

// Compile-time module registry. AK does not load or uninstall arbitrary Go code at runtime.
type SysModule struct {
	ID             uuid.UUID          `json:"id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Version        string             `json:"version"`
	Description    *string            `json:"description"`
	Capabilities   []byte             `json:"capabilities"`
	ConfigSchema   []byte             `json:"config_schema"`
	Status         string             `json:"status"`
	InstalledAt    pgtype.Timestamptz `json:"installed_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	NameKey        string             `json:"name_key"`
	DescriptionKey string             `json:"description_key"`
}

type SysRegion struct {
	Code              string             `json:"code"`
	ParentCode        *string            `json:"parent_code"`
	Level             int16              `json:"level"`
	Name              string             `json:"name"`
	FullName          *string            `json:"full_name"`
	PostalCode        *string            `json:"postal_code"`
	Longitude         pgtype.Numeric     `json:"longitude"`
	Latitude          pgtype.Numeric     `json:"latitude"`
	Status            string             `json:"status"`
	Metadata          []byte             `json:"metadata"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Version           int32              `json:"version"`
	IsManuallyManaged bool               `json:"is_manually_managed"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type SysRoleMenu struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	RoleID    uuid.UUID          `json:"role_id"`
	MenuID    uuid.UUID          `json:"menu_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SysShareConfig struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	ProviderCode        string             `json:"provider_code"`
	ExternalAppID       string             `json:"external_app_id"`
	ConfigSchemaVersion int32              `json:"config_schema_version"`
	PublicConfig        []byte             `json:"public_config"`
	SecretCiphertext    []byte             `json:"secret_ciphertext"`
	SecretKeyVersion    *int32             `json:"secret_key_version"`
	SecretFieldNames    []string           `json:"secret_field_names"`
	Status              string             `json:"status"`
	LockVersion         int32              `json:"lock_version"`
	CreatedBy           *uuid.UUID         `json:"created_by"`
	UpdatedBy           *uuid.UUID         `json:"updated_by"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type SysWebhookDelivery struct {
	ID             uuid.UUID          `json:"id"`
	EndpointID     uuid.UUID          `json:"endpoint_id"`
	EventID        uuid.UUID          `json:"event_id"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	ResponseStatus *int32             `json:"response_status"`
	ResponseBody   *string            `json:"response_body"`
	LastError      *string            `json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SysWebhookEndpoint struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	Name             string             `json:"name"`
	EndpointUrl      string             `json:"endpoint_url"`
	EventTypes       []string           `json:"event_types"`
	SecretCiphertext []byte             `json:"secret_ciphertext"`
	SecretKeyVersion int32              `json:"secret_key_version"`
	MaxAttempts      int32              `json:"max_attempts"`
	TimeoutSeconds   int32              `json:"timeout_seconds"`
	Status           string             `json:"status"`
	CreatedBy        *uuid.UUID         `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
