// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgPositionMembers = `-- name: CountOrgPositionMembers :one
SELECT count(*) FROM org.user_positions
WHERE tenant_id = $1 AND position_id = $2
`

type CountOrgPositionMembersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) CountOrgPositionMembers(ctx context.Context, arg CountOrgPositionMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgPositionMembers, arg.TenantID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrgPosition = `-- name: CreateOrgPosition :one
INSERT INTO org.positions (tenant_id, code, name, description, sort_order, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code::text AS code, name, description, sort_order, status, updated_at
`

type CreateOrgPositionParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SortOrder   int32     `json:"sort_order"`
	Status      string    `json:"status"`
}

type CreateOrgPositionRow struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	Status      string             `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrgPosition(ctx context.Context, arg CreateOrgPositionParams) (CreateOrgPositionRow, error) {
	row := q.db.QueryRow(ctx, createOrgPosition,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.Status,
	)
	var i CreateOrgPositionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrgUnit = `-- name: CreateOrgUnit :one
INSERT INTO org.units (tenant_id, parent_id, code, name, unit_type, phone, email, sort_order, status)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8, $9)
RETURNING id, parent_id, code::text AS code, name, unit_type, phone, coalesce(email::text, '') AS email,
          sort_order, status, updated_at
`

type CreateOrgUnitParams struct {
	TenantID  uuid.UUID  `json:"tenant_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Code      string     `json:"code"`
	Name      string     `json:"name"`
	UnitType  string     `json:"unit_type"`
	Phone     *string    `json:"phone"`
	Email     *string    `json:"email"`
	SortOrder int32      `json:"sort_order"`
	Status    string     `json:"status"`
}

type CreateOrgUnitRow struct {
	ID        uuid.UUID          `json:"id"`
	ParentID  *uuid.UUID         `json:"parent_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	UnitType  string             `json:"unit_type"`
	Phone     *string            `json:"phone"`
	Email     interface{}        `json:"email"`
	SortOrder int32              `json:"sort_order"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrgUnit(ctx context.Context, arg CreateOrgUnitParams) (CreateOrgUnitRow, error) {
	row := q.db.QueryRow(ctx, createOrgUnit,
		arg.TenantID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.UnitType,
		arg.Phone,
		arg.Email,
		arg.SortOrder,
		arg.Status,
	)
	var i CreateOrgUnitRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.UnitType,
		&i.Phone,
		&i.Email,
		&i.SortOrder,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgPositionForUpdate = `-- name: GetOrgPositionForUpdate :one
SELECT id, code::text AS code, name, description, sort_order, status, updated_at
FROM org.positions
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetOrgPositionForUpdateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

type GetOrgPositionForUpdateRow struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	Status      string             `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrgPositionForUpdate(ctx context.Context, arg GetOrgPositionForUpdateParams) (GetOrgPositionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrgPositionForUpdate, arg.TenantID, arg.ID)
	var i GetOrgPositionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgUnitForUpdate = `-- name: GetOrgUnitForUpdate :one
SELECT id, parent_id, code::text AS code, name, unit_type, phone, coalesce(email::text, '') AS email,
       sort_order, status, updated_at
FROM org.units
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetOrgUnitForUpdateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

type GetOrgUnitForUpdateRow struct {
	ID        uuid.UUID          `json:"id"`
	ParentID  *uuid.UUID         `json:"parent_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	UnitType  string             `json:"unit_type"`
	Phone     *string            `json:"phone"`
	Email     interface{}        `json:"email"`
	SortOrder int32              `json:"sort_order"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrgUnitForUpdate(ctx context.Context, arg GetOrgUnitForUpdateParams) (GetOrgUnitForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrgUnitForUpdate, arg.TenantID, arg.ID)
	var i GetOrgUnitForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.UnitType,
		&i.Phone,
		&i.Email,
		&i.SortOrder,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgUnitOccupancy = `-- name: GetOrgUnitOccupancy :one
SELECT
  (SELECT count(*) FROM org.units child WHERE child.tenant_id = $1 AND child.parent_id = $2 AND child.deleted_at IS NULL) AS child_count,
  (SELECT count(*) FROM org.user_units member WHERE member.tenant_id = $1 AND member.unit_id = $2) AS member_count
`

type GetOrgUnitOccupancyParams struct {
	TenantID uuid.UUID  `json:"tenant_id"`
	ID       *uuid.UUID `json:"id"`
}

type GetOrgUnitOccupancyRow struct {
	ChildCount  int64 `json:"child_count"`
	MemberCount int64 `json:"member_count"`
}

func (q *Queries) GetOrgUnitOccupancy(ctx context.Context, arg GetOrgUnitOccupancyParams) (GetOrgUnitOccupancyRow, error) {
	row := q.db.QueryRow(ctx, getOrgUnitOccupancy, arg.TenantID, arg.ID)
	var i GetOrgUnitOccupancyRow
	err := row.Scan(&i.ChildCount, &i.MemberCount)
	return i, err
}

const insertOrgOperationAudit = `-- name: InsertOrgOperationAudit :exec
INSERT INTO audit.operation_logs (
  tenant_id, user_id, session_id, request_id, module_code, action_name, resource_type,
  resource_id, http_method, request_path, response_status, client_ip, user_agent,
  before_data, after_data, succeeded
)
VALUES (
  $1, $2, $3, $4,
  'org', $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13::jsonb,
  $14::jsonb, true
)
`

type InsertOrgOperationAuditParams struct {
	TenantID       *uuid.UUID  `json:"tenant_id"`
	UserID         *uuid.UUID  `json:"user_id"`
	SessionID      *uuid.UUID  `json:"session_id"`
	RequestID      string      `json:"request_id"`
	ActionName     string      `json:"action_name"`
	ResourceType   *string     `json:"resource_type"`
	ResourceID     *string     `json:"resource_id"`
	HttpMethod     *string     `json:"http_method"`
	RequestPath    *string     `json:"request_path"`
	ResponseStatus *int32      `json:"response_status"`
	ClientIp       *netip.Addr `json:"client_ip"`
	UserAgent      *string     `json:"user_agent"`
	BeforeData     []byte      `json:"before_data"`
	AfterData      []byte      `json:"after_data"`
}

func (q *Queries) InsertOrgOperationAudit(ctx context.Context, arg InsertOrgOperationAuditParams) error {
	_, err := q.db.Exec(ctx, insertOrgOperationAudit,
		arg.TenantID,
		arg.UserID,
		arg.SessionID,
		arg.RequestID,
		arg.ActionName,
		arg.ResourceType,
		arg.ResourceID,
		arg.HttpMethod,
		arg.RequestPath,
		arg.ResponseStatus,
		arg.ClientIp,
		arg.UserAgent,
		arg.BeforeData,
		arg.AfterData,
	)
	return err
}

const listOrgPositions = `-- name: ListOrgPositions :many
SELECT p.id, p.code::text AS code, p.name, p.description, p.sort_order, p.status, p.updated_at,
       (SELECT count(*) FROM org.user_positions up WHERE up.tenant_id = p.tenant_id AND up.position_id = p.id) AS member_count
FROM org.positions p
WHERE p.tenant_id = $1 AND p.deleted_at IS NULL
  AND ($2::text = '' OR p.code ILIKE '%' || $2::text || '%' OR p.name ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR p.status = $3::text)
  AND ($4::uuid IS NULL OR EXISTS (
      SELECT 1 FROM org.user_positions up
      WHERE up.tenant_id = p.tenant_id AND up.position_id = p.id AND up.unit_id = $4::uuid
  ))
ORDER BY p.sort_order, p.name, p.id
`

type ListOrgPositionsParams struct {
	TenantID uuid.UUID  `json:"tenant_id"`
	Query    string     `json:"query"`
	Status   string     `json:"status"`
	UnitID   *uuid.UUID `json:"unit_id"`
}

type ListOrgPositionsRow struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	Status      string             `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MemberCount int64              `json:"member_count"`
}

func (q *Queries) ListOrgPositions(ctx context.Context, arg ListOrgPositionsParams) ([]ListOrgPositionsRow, error) {
	rows, err := q.db.Query(ctx, listOrgPositions,
		arg.TenantID,
		arg.Query,
		arg.Status,
		arg.UnitID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgPositionsRow{}
	for rows.Next() {
		var i ListOrgPositionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.Status,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgUnits = `-- name: ListOrgUnits :many
SELECT u.id, u.parent_id, u.code::text AS code, u.name, u.unit_type, u.phone,
       coalesce(u.email::text, '') AS email, u.sort_order, u.status, u.updated_at,
       (SELECT count(*) FROM org.user_units uu WHERE uu.tenant_id = u.tenant_id AND uu.unit_id = u.id) AS direct_member_count,
       (SELECT count(*) FROM org.units child WHERE child.tenant_id = u.tenant_id AND child.parent_id = u.id AND child.deleted_at IS NULL) AS child_count
FROM org.units u
WHERE u.tenant_id = $1 AND u.deleted_at IS NULL
ORDER BY u.sort_order, u.name, u.id
`

type ListOrgUnitsRow struct {
	ID                uuid.UUID          `json:"id"`
	ParentID          *uuid.UUID         `json:"parent_id"`
	Code              string             `json:"code"`
	Name              string             `json:"name"`
	UnitType          string             `json:"unit_type"`
	Phone             *string            `json:"phone"`
	Email             interface{}        `json:"email"`
	SortOrder         int32              `json:"sort_order"`
	Status            string             `json:"status"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DirectMemberCount int64              `json:"direct_member_count"`
	ChildCount        int64              `json:"child_count"`
}

func (q *Queries) ListOrgUnits(ctx context.Context, tenantID uuid.UUID) ([]ListOrgUnitsRow, error) {
	rows, err := q.db.Query(ctx, listOrgUnits, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgUnitsRow{}
	for rows.Next() {
		var i ListOrgUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.UnitType,
			&i.Phone,
			&i.Email,
			&i.SortOrder,
			&i.Status,
			&i.UpdatedAt,
			&i.DirectMemberCount,
			&i.ChildCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveOrgUnit = `-- name: MoveOrgUnit :one
UPDATE org.units
SET parent_id = $1, sort_order = $2
WHERE tenant_id = $3 AND id = $4 AND deleted_at IS NULL
RETURNING id, parent_id, code::text AS code, name, unit_type, phone, coalesce(email::text, '') AS email,
          sort_order, status, updated_at
`

type MoveOrgUnitParams struct {
	ParentID  *uuid.UUID `json:"parent_id"`
	SortOrder int32      `json:"sort_order"`
	TenantID  uuid.UUID  `json:"tenant_id"`
	ID        uuid.UUID  `json:"id"`
}

type MoveOrgUnitRow struct {
	ID        uuid.UUID          `json:"id"`
	ParentID  *uuid.UUID         `json:"parent_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	UnitType  string             `json:"unit_type"`
	Phone     *string            `json:"phone"`
	Email     interface{}        `json:"email"`
	SortOrder int32              `json:"sort_order"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MoveOrgUnit(ctx context.Context, arg MoveOrgUnitParams) (MoveOrgUnitRow, error) {
	row := q.db.QueryRow(ctx, moveOrgUnit,
		arg.ParentID,
		arg.SortOrder,
		arg.TenantID,
		arg.ID,
	)
	var i MoveOrgUnitRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.UnitType,
		&i.Phone,
		&i.Email,
		&i.SortOrder,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const orgUnitParentExists = `-- name: OrgUnitParentExists :one
SELECT EXISTS(
    SELECT 1 FROM org.units
    WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
)
`

type OrgUnitParentExistsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ParentID uuid.UUID `json:"parent_id"`
}

func (q *Queries) OrgUnitParentExists(ctx context.Context, arg OrgUnitParentExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, orgUnitParentExists, arg.TenantID, arg.ParentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteOrgPosition = `-- name: SoftDeleteOrgPosition :execrows
UPDATE org.positions SET deleted_at = now()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteOrgPositionParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteOrgPosition(ctx context.Context, arg SoftDeleteOrgPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOrgPosition, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteOrgUnit = `-- name: SoftDeleteOrgUnit :execrows
UPDATE org.units SET deleted_at = now()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteOrgUnitParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteOrgUnit(ctx context.Context, arg SoftDeleteOrgUnitParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOrgUnit, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrgPosition = `-- name: UpdateOrgPosition :one
UPDATE org.positions
SET code = $1, name = $2, description = $3,
    sort_order = $4, status = $5
WHERE tenant_id = $6 AND id = $7 AND deleted_at IS NULL
RETURNING id, code::text AS code, name, description, sort_order, status, updated_at
`

type UpdateOrgPositionParams struct {
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SortOrder   int32     `json:"sort_order"`
	Status      string    `json:"status"`
	TenantID    uuid.UUID `json:"tenant_id"`
	ID          uuid.UUID `json:"id"`
}

type UpdateOrgPositionRow struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	Status      string             `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrgPosition(ctx context.Context, arg UpdateOrgPositionParams) (UpdateOrgPositionRow, error) {
	row := q.db.QueryRow(ctx, updateOrgPosition,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.Status,
		arg.TenantID,
		arg.ID,
	)
	var i UpdateOrgPositionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrgUnit = `-- name: UpdateOrgUnit :one
UPDATE org.units
SET code = $1, name = $2, unit_type = $3,
    phone = $4, email = $5, sort_order = $6, status = $7
WHERE tenant_id = $8 AND id = $9 AND deleted_at IS NULL
RETURNING id, parent_id, code::text AS code, name, unit_type, phone, coalesce(email::text, '') AS email,
          sort_order, status, updated_at
`

type UpdateOrgUnitParams struct {
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	UnitType  string    `json:"unit_type"`
	Phone     *string   `json:"phone"`
	Email     *string   `json:"email"`
	SortOrder int32     `json:"sort_order"`
	Status    string    `json:"status"`
	TenantID  uuid.UUID `json:"tenant_id"`
	ID        uuid.UUID `json:"id"`
}

type UpdateOrgUnitRow struct {
	ID        uuid.UUID          `json:"id"`
	ParentID  *uuid.UUID         `json:"parent_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	UnitType  string             `json:"unit_type"`
	Phone     *string            `json:"phone"`
	Email     interface{}        `json:"email"`
	SortOrder int32              `json:"sort_order"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrgUnit(ctx context.Context, arg UpdateOrgUnitParams) (UpdateOrgUnitRow, error) {
	row := q.db.QueryRow(ctx, updateOrgUnit,
		arg.Code,
		arg.Name,
		arg.UnitType,
		arg.Phone,
		arg.Email,
		arg.SortOrder,
		arg.Status,
		arg.TenantID,
		arg.ID,
	)
	var i UpdateOrgUnitRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.UnitType,
		&i.Phone,
		&i.Email,
		&i.SortOrder,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
