// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_web.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const publicWebAsset = `-- name: PublicWebAsset :one
SELECT f.id,f.provider,f.bucket_name,f.object_key,COALESCE(f.media_type,'')::text AS media_type,f.size_bytes
FROM storage.files f JOIN app.applications a ON a.tenant_id=f.tenant_id AND a.id=$2
WHERE f.tenant_id=$1 AND f.id=$3 AND a.status='active' AND a.deleted_at IS NULL
 AND f.deleted_at IS NULL AND f.status='ready' AND f.scan_status IN ('clean','skipped')
 AND COALESCE(f.metadata->>'purpose','')<>'feedback' AND f.media_type IN ('image/png','image/jpeg','image/webp')
 AND (a.icon_file_id=f.id OR EXISTS (
 SELECT 1 FROM app.application_assets asset JOIN app.application_public_web_configs c ON c.tenant_id=asset.tenant_id AND c.app_id=asset.app_id
 WHERE asset.tenant_id=a.tenant_id AND asset.app_id=a.id AND asset.file_id=f.id AND asset.asset_type='screenshot' AND c.enabled))
`

type PublicWebAssetParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
	ID_2     uuid.UUID `json:"id_2"`
}

type PublicWebAssetRow struct {
	ID         uuid.UUID `json:"id"`
	Provider   string    `json:"provider"`
	BucketName string    `json:"bucket_name"`
	ObjectKey  string    `json:"object_key"`
	MediaType  string    `json:"media_type"`
	SizeBytes  int64     `json:"size_bytes"`
}

func (q *Queries) PublicWebAsset(ctx context.Context, arg PublicWebAssetParams) (PublicWebAssetRow, error) {
	row := q.db.QueryRow(ctx, publicWebAsset, arg.TenantID, arg.ID, arg.ID_2)
	var i PublicWebAssetRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BucketName,
		&i.ObjectKey,
		&i.MediaType,
		&i.SizeBytes,
	)
	return i, err
}

const publicWebGetConfig = `-- name: PublicWebGetConfig :one
SELECT a.id AS app_id, COALESCE(c.enabled,false)::boolean AS enabled, COALESCE(c.apk_enabled,false)::boolean AS apk_enabled,
 COALESCE(c.promotion_enabled,true)::boolean AS promotion_enabled, COALESCE(c.lock_version,0)::integer AS lock_version
FROM app.applications a LEFT JOIN app.application_public_web_configs c ON c.tenant_id=a.tenant_id AND c.app_id=a.id
WHERE a.tenant_id=$1 AND a.id=$2 AND a.deleted_at IS NULL
`

type PublicWebGetConfigParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

type PublicWebGetConfigRow struct {
	AppID            uuid.UUID `json:"app_id"`
	Enabled          bool      `json:"enabled"`
	ApkEnabled       bool      `json:"apk_enabled"`
	PromotionEnabled bool      `json:"promotion_enabled"`
	LockVersion      int32     `json:"lock_version"`
}

func (q *Queries) PublicWebGetConfig(ctx context.Context, arg PublicWebGetConfigParams) (PublicWebGetConfigRow, error) {
	row := q.db.QueryRow(ctx, publicWebGetConfig, arg.TenantID, arg.ID)
	var i PublicWebGetConfigRow
	err := row.Scan(
		&i.AppID,
		&i.Enabled,
		&i.ApkEnabled,
		&i.PromotionEnabled,
		&i.LockVersion,
	)
	return i, err
}

const publicWebLockApp = `-- name: PublicWebLockApp :one
SELECT id FROM app.applications WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL FOR UPDATE
`

type PublicWebLockAppParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) PublicWebLockApp(ctx context.Context, arg PublicWebLockAppParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, publicWebLockApp, arg.TenantID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const publicWebPageImageCandidates = `-- name: PublicWebPageImageCandidates :many
SELECT t.body,t.body_format FROM content.pages p
JOIN content.page_revisions r ON r.id=p.current_revision_id AND r.app_id=p.app_id AND r.status='published'
JOIN content.page_revision_translations t ON t.revision_id=r.id
WHERE p.tenant_id=$1 AND p.app_id=$2 AND p.status='published' AND strpos(t.body::text,$3::text)>0
`

type PublicWebPageImageCandidatesParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	AppID      uuid.UUID `json:"app_id"`
	FileIDText string    `json:"file_id_text"`
}

type PublicWebPageImageCandidatesRow struct {
	Body       []byte `json:"body"`
	BodyFormat string `json:"body_format"`
}

func (q *Queries) PublicWebPageImageCandidates(ctx context.Context, arg PublicWebPageImageCandidatesParams) ([]PublicWebPageImageCandidatesRow, error) {
	rows, err := q.db.Query(ctx, publicWebPageImageCandidates, arg.TenantID, arg.AppID, arg.FileIDText)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicWebPageImageCandidatesRow{}
	for rows.Next() {
		var i PublicWebPageImageCandidatesRow
		if err := rows.Scan(&i.Body, &i.BodyFormat); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicWebPageImageFile = `-- name: PublicWebPageImageFile :one
SELECT f.id,f.provider,f.bucket_name,f.object_key,COALESCE(f.media_type,'')::text AS media_type,f.size_bytes
FROM storage.files f WHERE f.tenant_id=$1 AND f.id=$2
AND f.deleted_at IS NULL AND f.status='ready' AND f.scan_status IN ('clean','skipped')
AND COALESCE(f.metadata->>'purpose','')<>'feedback' AND f.media_type IN ('image/png','image/jpeg','image/webp')
`

type PublicWebPageImageFileParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

type PublicWebPageImageFileRow struct {
	ID         uuid.UUID `json:"id"`
	Provider   string    `json:"provider"`
	BucketName string    `json:"bucket_name"`
	ObjectKey  string    `json:"object_key"`
	MediaType  string    `json:"media_type"`
	SizeBytes  int64     `json:"size_bytes"`
}

func (q *Queries) PublicWebPageImageFile(ctx context.Context, arg PublicWebPageImageFileParams) (PublicWebPageImageFileRow, error) {
	row := q.db.QueryRow(ctx, publicWebPageImageFile, arg.TenantID, arg.ID)
	var i PublicWebPageImageFileRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BucketName,
		&i.ObjectKey,
		&i.MediaType,
		&i.SizeBytes,
	)
	return i, err
}

const publicWebPageLinks = `-- name: PublicWebPageLinks :many
SELECT p.slug,t.title FROM content.pages p JOIN content.page_revision_translations t ON t.revision_id=p.current_revision_id AND t.locale=$3
WHERE p.tenant_id=$1 AND p.app_id=$2 AND p.status='published' ORDER BY p.slug
`

type PublicWebPageLinksParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	AppID    uuid.UUID `json:"app_id"`
	Locale   string    `json:"locale"`
}

type PublicWebPageLinksRow struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

func (q *Queries) PublicWebPageLinks(ctx context.Context, arg PublicWebPageLinksParams) ([]PublicWebPageLinksRow, error) {
	rows, err := q.db.Query(ctx, publicWebPageLinks, arg.TenantID, arg.AppID, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicWebPageLinksRow{}
	for rows.Next() {
		var i PublicWebPageLinksRow
		if err := rows.Scan(&i.Slug, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicWebScreenshots = `-- name: PublicWebScreenshots :many
SELECT asset.file_id FROM app.application_assets asset JOIN storage.files f ON f.tenant_id=asset.tenant_id AND f.id=asset.file_id
WHERE asset.tenant_id=$1 AND asset.app_id=$2 AND asset.asset_type='screenshot'
 AND f.deleted_at IS NULL AND f.status='ready' AND f.scan_status IN ('clean','skipped') AND COALESCE(f.metadata->>'purpose','')<>'feedback' AND f.media_type IN ('image/png','image/jpeg','image/webp')
ORDER BY asset.position,asset.id
`

type PublicWebScreenshotsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	AppID    uuid.UUID `json:"app_id"`
}

func (q *Queries) PublicWebScreenshots(ctx context.Context, arg PublicWebScreenshotsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, publicWebScreenshots, arg.TenantID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var file_id uuid.UUID
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicWebStores = `-- name: PublicWebStores :many
SELECT id,name,scheme,enabled,priority,COALESCE(platform,'')::text AS platform,web_url
FROM app.application_store_listings WHERE tenant_id=$1 AND app_id=$2 ORDER BY priority DESC,id
`

type PublicWebStoresParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	AppID    uuid.UUID `json:"app_id"`
}

type PublicWebStoresRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Scheme   string    `json:"scheme"`
	Enabled  bool      `json:"enabled"`
	Priority int32     `json:"priority"`
	Platform string    `json:"platform"`
	WebUrl   string    `json:"web_url"`
}

func (q *Queries) PublicWebStores(ctx context.Context, arg PublicWebStoresParams) ([]PublicWebStoresRow, error) {
	rows, err := q.db.Query(ctx, publicWebStores, arg.TenantID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicWebStoresRow{}
	for rows.Next() {
		var i PublicWebStoresRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scheme,
			&i.Enabled,
			&i.Priority,
			&i.Platform,
			&i.WebUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicWebTranslations = `-- name: PublicWebTranslations :many
SELECT locale,name,introduction,promotion_title,promotion_description,promotion_button_label FROM app.application_public_web_translations WHERE tenant_id=$1 AND app_id=$2 ORDER BY locale
`

type PublicWebTranslationsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	AppID    uuid.UUID `json:"app_id"`
}

type PublicWebTranslationsRow struct {
	Locale               string `json:"locale"`
	Name                 string `json:"name"`
	Introduction         string `json:"introduction"`
	PromotionTitle       string `json:"promotion_title"`
	PromotionDescription string `json:"promotion_description"`
	PromotionButtonLabel string `json:"promotion_button_label"`
}

func (q *Queries) PublicWebTranslations(ctx context.Context, arg PublicWebTranslationsParams) ([]PublicWebTranslationsRow, error) {
	rows, err := q.db.Query(ctx, publicWebTranslations, arg.TenantID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicWebTranslationsRow{}
	for rows.Next() {
		var i PublicWebTranslationsRow
		if err := rows.Scan(
			&i.Locale,
			&i.Name,
			&i.Introduction,
			&i.PromotionTitle,
			&i.PromotionDescription,
			&i.PromotionButtonLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicWebWriteConfig = `-- name: PublicWebWriteConfig :exec
INSERT INTO app.application_public_web_configs(tenant_id,app_id,enabled,apk_enabled,promotion_enabled)
VALUES($1,$2,$3,$4,$5) ON CONFLICT(tenant_id,app_id) DO UPDATE SET enabled=EXCLUDED.enabled,apk_enabled=EXCLUDED.apk_enabled,promotion_enabled=EXCLUDED.promotion_enabled,lock_version=app.application_public_web_configs.lock_version+1,updated_at=now()
`

type PublicWebWriteConfigParams struct {
	TenantID         uuid.UUID `json:"tenant_id"`
	AppID            uuid.UUID `json:"app_id"`
	Enabled          bool      `json:"enabled"`
	ApkEnabled       bool      `json:"apk_enabled"`
	PromotionEnabled bool      `json:"promotion_enabled"`
}

func (q *Queries) PublicWebWriteConfig(ctx context.Context, arg PublicWebWriteConfigParams) error {
	_, err := q.db.Exec(ctx, publicWebWriteConfig,
		arg.TenantID,
		arg.AppID,
		arg.Enabled,
		arg.ApkEnabled,
		arg.PromotionEnabled,
	)
	return err
}

const publicWebWriteStore = `-- name: PublicWebWriteStore :execrows
UPDATE app.application_store_listings SET platform=NULLIF($1::text,''),web_url=$2
WHERE tenant_id=$3 AND app_id=$4 AND id=$5
`

type PublicWebWriteStoreParams struct {
	Platform string    `json:"platform"`
	WebUrl   string    `json:"web_url"`
	TenantID uuid.UUID `json:"tenant_id"`
	AppID    uuid.UUID `json:"app_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) PublicWebWriteStore(ctx context.Context, arg PublicWebWriteStoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, publicWebWriteStore,
		arg.Platform,
		arg.WebUrl,
		arg.TenantID,
		arg.AppID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const publicWebWriteTranslation = `-- name: PublicWebWriteTranslation :exec
INSERT INTO app.application_public_web_translations(tenant_id,app_id,locale,name,introduction,promotion_title,promotion_description,promotion_button_label) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT(tenant_id,app_id,locale) DO UPDATE SET name=EXCLUDED.name,introduction=EXCLUDED.introduction,promotion_title=EXCLUDED.promotion_title,promotion_description=EXCLUDED.promotion_description,promotion_button_label=EXCLUDED.promotion_button_label
`

type PublicWebWriteTranslationParams struct {
	TenantID             uuid.UUID `json:"tenant_id"`
	AppID                uuid.UUID `json:"app_id"`
	Locale               string    `json:"locale"`
	Name                 string    `json:"name"`
	Introduction         string    `json:"introduction"`
	PromotionTitle       string    `json:"promotion_title"`
	PromotionDescription string    `json:"promotion_description"`
	PromotionButtonLabel string    `json:"promotion_button_label"`
}

func (q *Queries) PublicWebWriteTranslation(ctx context.Context, arg PublicWebWriteTranslationParams) error {
	_, err := q.db.Exec(ctx, publicWebWriteTranslation,
		arg.TenantID,
		arg.AppID,
		arg.Locale,
		arg.Name,
		arg.Introduction,
		arg.PromotionTitle,
		arg.PromotionDescription,
		arg.PromotionButtonLabel,
	)
	return err
}
