// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_admin.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const sessionAdminCount = `-- name: SessionAdminCount :one
SELECT count(*)
FROM iam.sessions s
JOIN iam.users u ON u.id = s.user_id
LEFT JOIN iam.devices d ON d.id = s.device_id
WHERE s.tenant_id = $1
  AND s.last_seen_at >= $2 AND s.last_seen_at <= $3
  AND ($4::text = '' OR u.display_name ILIKE '%' || $4 || '%' OR u.email ILIKE '%' || $4 || '%')
  AND ($5::text = '' OR s.audience = $5)
  AND ($6::text = '' OR COALESCE(d.platform, CASE s.audience WHEN 'ak-admin' THEN 'web' ELSE 'unknown' END) = $6)
  AND ($7::text = '' OR COALESCE(host(s.ip_address), '') ILIKE '%' || $7 || '%')
  AND ($8::text = '' OR CASE WHEN s.status = 'active' AND s.absolute_expires_at <= now() THEN 'expired' ELSE s.status END = $8)
`

type SessionAdminCountParams struct {
	TenantID *uuid.UUID         `json:"tenant_id"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
	Query    string             `json:"query"`
	Audience string             `json:"audience"`
	Platform string             `json:"platform"`
	Ip       string             `json:"ip"`
	Status   string             `json:"status"`
}

func (q *Queries) SessionAdminCount(ctx context.Context, arg SessionAdminCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, sessionAdminCount,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Query,
		arg.Audience,
		arg.Platform,
		arg.Ip,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sessionAdminInsertAudit = `-- name: SessionAdminInsertAudit :exec
INSERT INTO audit.operation_logs (
  tenant_id,user_id,session_id,request_id,module_code,action_name,permission_code,resource_type,resource_id,http_method,request_path,response_status,client_ip,user_agent,request_summary,after_data,succeeded
) VALUES (
  $1,$2,$3,$4,'iam','iam.session.revoke','iam.session.revoke','session',$5,'DELETE','/admin-api/v1/online-sessions/{id}',200,$6,$7,'{}'::jsonb,jsonb_build_object('revoked',true,'current',$8::boolean),true
)
`

type SessionAdminInsertAuditParams struct {
	TenantID       *uuid.UUID  `json:"tenant_id"`
	ActorID        *uuid.UUID  `json:"actor_id"`
	ActorSessionID *uuid.UUID  `json:"actor_session_id"`
	RequestID      string      `json:"request_id"`
	ResourceID     *string     `json:"resource_id"`
	ClientIp       *netip.Addr `json:"client_ip"`
	UserAgent      *string     `json:"user_agent"`
	Current        bool        `json:"current"`
}

func (q *Queries) SessionAdminInsertAudit(ctx context.Context, arg SessionAdminInsertAuditParams) error {
	_, err := q.db.Exec(ctx, sessionAdminInsertAudit,
		arg.TenantID,
		arg.ActorID,
		arg.ActorSessionID,
		arg.RequestID,
		arg.ResourceID,
		arg.ClientIp,
		arg.UserAgent,
		arg.Current,
	)
	return err
}

const sessionAdminList = `-- name: SessionAdminList :many
SELECT s.id, s.user_id, COALESCE(u.email, '') AS email, u.display_name, s.audience,
       COALESCE(d.platform, CASE s.audience WHEN 'ak-mobile' THEN 'unknown' WHEN 'ak-admin' THEN 'web' ELSE 'unknown' END) AS platform,
       COALESCE(NULLIF(d.device_name, ''), NULLIF(d.model, ''), '')::text AS device_hint,
       COALESCE(host(s.ip_address), '')::text AS ip_address,
       (CASE WHEN s.status = 'active' AND s.absolute_expires_at <= now() THEN 'expired' ELSE s.status END)::text AS effective_status,
       s.id = $1 AS current,
       s.last_seen_at, s.absolute_expires_at, s.revoked_at
FROM iam.sessions s
JOIN iam.users u ON u.id = s.user_id
LEFT JOIN iam.devices d ON d.id = s.device_id
WHERE s.tenant_id = $2
  AND s.last_seen_at >= $3 AND s.last_seen_at <= $4
  AND ($5::text = '' OR u.display_name ILIKE '%' || $5 || '%' OR u.email ILIKE '%' || $5 || '%')
  AND ($6::text = '' OR s.audience = $6)
  AND ($7::text = '' OR COALESCE(d.platform, CASE s.audience WHEN 'ak-admin' THEN 'web' ELSE 'unknown' END) = $7)
  AND ($8::text = '' OR COALESCE(host(s.ip_address), '') ILIKE '%' || $8 || '%')
  AND ($9::text = '' OR CASE WHEN s.status = 'active' AND s.absolute_expires_at <= now() THEN 'expired' ELSE s.status END = $9)
ORDER BY s.last_seen_at DESC, s.id DESC
LIMIT $11 OFFSET $10
`

type SessionAdminListParams struct {
	CurrentSessionID uuid.UUID          `json:"current_session_id"`
	TenantID         *uuid.UUID         `json:"tenant_id"`
	FromAt           pgtype.Timestamptz `json:"from_at"`
	ToAt             pgtype.Timestamptz `json:"to_at"`
	Query            string             `json:"query"`
	Audience         string             `json:"audience"`
	Platform         string             `json:"platform"`
	Ip               string             `json:"ip"`
	Status           string             `json:"status"`
	PageOffset       int32              `json:"page_offset"`
	PageSize         int32              `json:"page_size"`
}

type SessionAdminListRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	Audience          string             `json:"audience"`
	Platform          string             `json:"platform"`
	DeviceHint        string             `json:"device_hint"`
	IpAddress         string             `json:"ip_address"`
	EffectiveStatus   string             `json:"effective_status"`
	Current           bool               `json:"current"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) SessionAdminList(ctx context.Context, arg SessionAdminListParams) ([]SessionAdminListRow, error) {
	rows, err := q.db.Query(ctx, sessionAdminList,
		arg.CurrentSessionID,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Query,
		arg.Audience,
		arg.Platform,
		arg.Ip,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionAdminListRow{}
	for rows.Next() {
		var i SessionAdminListRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Audience,
			&i.Platform,
			&i.DeviceHint,
			&i.IpAddress,
			&i.EffectiveStatus,
			&i.Current,
			&i.LastSeenAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionAdminLockForRevoke = `-- name: SessionAdminLockForRevoke :one
SELECT id, id = $1 AS current
FROM iam.sessions
WHERE id = $2 AND tenant_id = $3 AND status = 'active' AND revoked_at IS NULL AND absolute_expires_at > now()
FOR UPDATE
`

type SessionAdminLockForRevokeParams struct {
	CurrentSessionID uuid.UUID  `json:"current_session_id"`
	ID               uuid.UUID  `json:"id"`
	TenantID         *uuid.UUID `json:"tenant_id"`
}

type SessionAdminLockForRevokeRow struct {
	ID      uuid.UUID `json:"id"`
	Current bool      `json:"current"`
}

func (q *Queries) SessionAdminLockForRevoke(ctx context.Context, arg SessionAdminLockForRevokeParams) (SessionAdminLockForRevokeRow, error) {
	row := q.db.QueryRow(ctx, sessionAdminLockForRevoke, arg.CurrentSessionID, arg.ID, arg.TenantID)
	var i SessionAdminLockForRevokeRow
	err := row.Scan(&i.ID, &i.Current)
	return i, err
}

const sessionAdminRevoke = `-- name: SessionAdminRevoke :execrows
UPDATE iam.sessions SET status='revoked', revoked_at=now(), revoke_reason='admin_force_logout', access_token_version=access_token_version+1
WHERE id=$1 AND tenant_id=$2 AND status='active' AND revoked_at IS NULL
`

type SessionAdminRevokeParams struct {
	ID       uuid.UUID  `json:"id"`
	TenantID *uuid.UUID `json:"tenant_id"`
}

func (q *Queries) SessionAdminRevoke(ctx context.Context, arg SessionAdminRevokeParams) (int64, error) {
	result, err := q.db.Exec(ctx, sessionAdminRevoke, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionAdminRevokeRefreshTokens = `-- name: SessionAdminRevokeRefreshTokens :exec
UPDATE iam.refresh_tokens SET revoked_at=COALESCE(revoked_at, now()) WHERE session_id=$1 AND revoked_at IS NULL
`

func (q *Queries) SessionAdminRevokeRefreshTokens(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, sessionAdminRevokeRefreshTokens, sessionID)
	return err
}
