// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeSelfAvatarUploadSession = `-- name: CompleteSelfAvatarUploadSession :exec
UPDATE storage.upload_sessions
SET file_id = $1, status = 'completed', completed_at = now()
WHERE id = $2 AND tenant_id = $3 AND user_id = $4
`

type CompleteSelfAvatarUploadSessionParams struct {
	FileID   *uuid.UUID `json:"file_id"`
	ID       uuid.UUID  `json:"id"`
	TenantID uuid.UUID  `json:"tenant_id"`
	UserID   uuid.UUID  `json:"user_id"`
}

func (q *Queries) CompleteSelfAvatarUploadSession(ctx context.Context, arg CompleteSelfAvatarUploadSessionParams) error {
	_, err := q.db.Exec(ctx, completeSelfAvatarUploadSession,
		arg.FileID,
		arg.ID,
		arg.TenantID,
		arg.UserID,
	)
	return err
}

const createSelfAvatarUploadSession = `-- name: CreateSelfAvatarUploadSession :one
INSERT INTO storage.upload_sessions (
    tenant_id, user_id, provider, bucket_name, object_key, original_name,
    media_type, expected_size, status, expires_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, 'initiated', $9
)
RETURNING id, provider, bucket_name, object_key, expires_at
`

type CreateSelfAvatarUploadSessionParams struct {
	TenantID     uuid.UUID          `json:"tenant_id"`
	UserID       uuid.UUID          `json:"user_id"`
	Provider     string             `json:"provider"`
	BucketName   string             `json:"bucket_name"`
	ObjectKey    string             `json:"object_key"`
	OriginalName string             `json:"original_name"`
	MediaType    *string            `json:"media_type"`
	ExpectedSize int64              `json:"expected_size"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type CreateSelfAvatarUploadSessionRow struct {
	ID         uuid.UUID          `json:"id"`
	Provider   string             `json:"provider"`
	BucketName string             `json:"bucket_name"`
	ObjectKey  string             `json:"object_key"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSelfAvatarUploadSession(ctx context.Context, arg CreateSelfAvatarUploadSessionParams) (CreateSelfAvatarUploadSessionRow, error) {
	row := q.db.QueryRow(ctx, createSelfAvatarUploadSession,
		arg.TenantID,
		arg.UserID,
		arg.Provider,
		arg.BucketName,
		arg.ObjectKey,
		arg.OriginalName,
		arg.MediaType,
		arg.ExpectedSize,
		arg.ExpiresAt,
	)
	var i CreateSelfAvatarUploadSessionRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BucketName,
		&i.ObjectKey,
		&i.ExpiresAt,
	)
	return i, err
}

const deletePreviousSelfAvatarUsage = `-- name: DeletePreviousSelfAvatarUsage :exec
DELETE FROM storage.file_usages
WHERE tenant_id = $1
  AND module_code = 'iam'
  AND entity_type = 'iam.user'
  AND entity_id = $2
  AND field_name = 'avatar_file_id'
`

type DeletePreviousSelfAvatarUsageParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePreviousSelfAvatarUsage(ctx context.Context, arg DeletePreviousSelfAvatarUsageParams) error {
	_, err := q.db.Exec(ctx, deletePreviousSelfAvatarUsage, arg.TenantID, arg.UserID)
	return err
}

const getSelfAvatarFileIDForUpdate = `-- name: GetSelfAvatarFileIDForUpdate :one
SELECT avatar_file_id
FROM iam.users
WHERE id = $1 AND status = 'active' AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetSelfAvatarFileIDForUpdate(ctx context.Context, userID uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSelfAvatarFileIDForUpdate, userID)
	var avatar_file_id *uuid.UUID
	err := row.Scan(&avatar_file_id)
	return avatar_file_id, err
}

const getSelfAvatarObject = `-- name: GetSelfAvatarObject :one
SELECT f.id, f.provider, f.bucket_name, f.object_key, f.media_type, f.size_bytes, f.sha256, f.updated_at
FROM iam.users AS u
JOIN storage.files AS f ON f.id = u.avatar_file_id
WHERE u.id = $1
  AND f.tenant_id = $2
  AND f.owner_user_id = $1
  AND u.status = 'active'
  AND u.deleted_at IS NULL
  AND f.status = 'ready'
  AND f.scan_status IN ('clean', 'skipped')
  AND f.deleted_at IS NULL
`

type GetSelfAvatarObjectParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetSelfAvatarObjectRow struct {
	ID         uuid.UUID          `json:"id"`
	Provider   string             `json:"provider"`
	BucketName string             `json:"bucket_name"`
	ObjectKey  string             `json:"object_key"`
	MediaType  *string            `json:"media_type"`
	SizeBytes  int64              `json:"size_bytes"`
	Sha256     []byte             `json:"sha256"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSelfAvatarObject(ctx context.Context, arg GetSelfAvatarObjectParams) (GetSelfAvatarObjectRow, error) {
	row := q.db.QueryRow(ctx, getSelfAvatarObject, arg.UserID, arg.TenantID)
	var i GetSelfAvatarObjectRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BucketName,
		&i.ObjectKey,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.UpdatedAt,
	)
	return i, err
}

const getSelfAvatarUploadSession = `-- name: GetSelfAvatarUploadSession :one
SELECT id, tenant_id, user_id, provider, bucket_name, object_key, original_name, media_type, expected_size, expires_at
FROM storage.upload_sessions
WHERE id = $1
  AND tenant_id = $2
  AND user_id = $3
  AND status = 'initiated'
  AND expires_at > now()
`

type GetSelfAvatarUploadSessionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type GetSelfAvatarUploadSessionRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	UserID       uuid.UUID          `json:"user_id"`
	Provider     string             `json:"provider"`
	BucketName   string             `json:"bucket_name"`
	ObjectKey    string             `json:"object_key"`
	OriginalName string             `json:"original_name"`
	MediaType    *string            `json:"media_type"`
	ExpectedSize int64              `json:"expected_size"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetSelfAvatarUploadSession(ctx context.Context, arg GetSelfAvatarUploadSessionParams) (GetSelfAvatarUploadSessionRow, error) {
	row := q.db.QueryRow(ctx, getSelfAvatarUploadSession, arg.ID, arg.TenantID, arg.UserID)
	var i GetSelfAvatarUploadSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Provider,
		&i.BucketName,
		&i.ObjectKey,
		&i.OriginalName,
		&i.MediaType,
		&i.ExpectedSize,
		&i.ExpiresAt,
	)
	return i, err
}

const insertReadySelfAvatarFile = `-- name: InsertReadySelfAvatarFile :one
INSERT INTO storage.files (
    tenant_id, owner_user_id, provider, bucket_name, object_key, original_name,
    media_type, extension, size_bytes, sha256, visibility, status, scan_status,
    metadata
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, 'private',
    'ready', 'skipped', jsonb_build_object('purpose', 'avatar', 'adapter', $3::varchar)
)
ON CONFLICT (tenant_id, sha256, size_bytes)
    WHERE sha256 IS NOT NULL AND status = 'ready' AND deleted_at IS NULL
DO UPDATE SET updated_at = storage.files.updated_at
RETURNING id, provider, bucket_name, object_key
`

type InsertReadySelfAvatarFileParams struct {
	TenantID     uuid.UUID  `json:"tenant_id"`
	UserID       *uuid.UUID `json:"user_id"`
	Provider     string     `json:"provider"`
	BucketName   string     `json:"bucket_name"`
	ObjectKey    string     `json:"object_key"`
	OriginalName string     `json:"original_name"`
	MediaType    *string    `json:"media_type"`
	Extension    *string    `json:"extension"`
	SizeBytes    int64      `json:"size_bytes"`
	Sha256       []byte     `json:"sha256"`
}

type InsertReadySelfAvatarFileRow struct {
	ID         uuid.UUID `json:"id"`
	Provider   string    `json:"provider"`
	BucketName string    `json:"bucket_name"`
	ObjectKey  string    `json:"object_key"`
}

func (q *Queries) InsertReadySelfAvatarFile(ctx context.Context, arg InsertReadySelfAvatarFileParams) (InsertReadySelfAvatarFileRow, error) {
	row := q.db.QueryRow(ctx, insertReadySelfAvatarFile,
		arg.TenantID,
		arg.UserID,
		arg.Provider,
		arg.BucketName,
		arg.ObjectKey,
		arg.OriginalName,
		arg.MediaType,
		arg.Extension,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i InsertReadySelfAvatarFileRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BucketName,
		&i.ObjectKey,
	)
	return i, err
}

const insertSelfAvatarAudit = `-- name: InsertSelfAvatarAudit :exec
INSERT INTO audit.operation_logs (
    tenant_id, user_id, session_id, request_id, module_code, action_name,
    resource_type, resource_id, http_method, request_path, response_status,
    client_ip, user_agent, before_data, after_data, succeeded
)
VALUES (
    $1, $2, $3,
    $4, 'storage', 'iam.me.avatar.update', 'iam.user',
    $5, $6,
    $7, 200,
    $8, $9,
    jsonb_build_object('avatar_file_id', $10::uuid),
    jsonb_build_object('avatar_file_id', $11::uuid), true
)
`

type InsertSelfAvatarAuditParams struct {
	TenantID     *uuid.UUID  `json:"tenant_id"`
	UserID       *uuid.UUID  `json:"user_id"`
	SessionID    *uuid.UUID  `json:"session_id"`
	RequestID    string      `json:"request_id"`
	ResourceID   *string     `json:"resource_id"`
	HttpMethod   *string     `json:"http_method"`
	RequestPath  *string     `json:"request_path"`
	ClientIp     *netip.Addr `json:"client_ip"`
	UserAgent    *string     `json:"user_agent"`
	BeforeFileID *uuid.UUID  `json:"before_file_id"`
	AfterFileID  uuid.UUID   `json:"after_file_id"`
}

func (q *Queries) InsertSelfAvatarAudit(ctx context.Context, arg InsertSelfAvatarAuditParams) error {
	_, err := q.db.Exec(ctx, insertSelfAvatarAudit,
		arg.TenantID,
		arg.UserID,
		arg.SessionID,
		arg.RequestID,
		arg.ResourceID,
		arg.HttpMethod,
		arg.RequestPath,
		arg.ClientIp,
		arg.UserAgent,
		arg.BeforeFileID,
		arg.AfterFileID,
	)
	return err
}

const insertSelfAvatarUsage = `-- name: InsertSelfAvatarUsage :exec
INSERT INTO storage.file_usages (
    file_id, tenant_id, module_code, entity_type, entity_id, field_name
)
VALUES (
    $1, $2, 'iam', 'iam.user',
    $3, 'avatar_file_id'
)
`

type InsertSelfAvatarUsageParams struct {
	FileID   uuid.UUID `json:"file_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) InsertSelfAvatarUsage(ctx context.Context, arg InsertSelfAvatarUsageParams) error {
	_, err := q.db.Exec(ctx, insertSelfAvatarUsage, arg.FileID, arg.TenantID, arg.UserID)
	return err
}

const lockSelfAvatarUploadSession = `-- name: LockSelfAvatarUploadSession :one
SELECT id, tenant_id, user_id, provider, bucket_name, object_key, original_name, media_type, expected_size, expires_at
FROM storage.upload_sessions
WHERE id = $1
  AND tenant_id = $2
  AND user_id = $3
  AND status = 'initiated'
  AND expires_at > now()
FOR UPDATE
`

type LockSelfAvatarUploadSessionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type LockSelfAvatarUploadSessionRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	UserID       uuid.UUID          `json:"user_id"`
	Provider     string             `json:"provider"`
	BucketName   string             `json:"bucket_name"`
	ObjectKey    string             `json:"object_key"`
	OriginalName string             `json:"original_name"`
	MediaType    *string            `json:"media_type"`
	ExpectedSize int64              `json:"expected_size"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) LockSelfAvatarUploadSession(ctx context.Context, arg LockSelfAvatarUploadSessionParams) (LockSelfAvatarUploadSessionRow, error) {
	row := q.db.QueryRow(ctx, lockSelfAvatarUploadSession, arg.ID, arg.TenantID, arg.UserID)
	var i LockSelfAvatarUploadSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Provider,
		&i.BucketName,
		&i.ObjectKey,
		&i.OriginalName,
		&i.MediaType,
		&i.ExpectedSize,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSelfAvatarFile = `-- name: UpdateSelfAvatarFile :exec
UPDATE iam.users
SET avatar_file_id = $1
WHERE id = $2 AND status = 'active' AND deleted_at IS NULL
`

type UpdateSelfAvatarFileParams struct {
	FileID *uuid.UUID `json:"file_id"`
	UserID uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateSelfAvatarFile(ctx context.Context, arg UpdateSelfAvatarFileParams) error {
	_, err := q.db.Exec(ctx, updateSelfAvatarFile, arg.FileID, arg.UserID)
	return err
}
