// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDictItem = `-- name: CreateDictItem :one
INSERT INTO sys.dict_items (dict_type_id,item_value,label,locale,color,css_class,sort_order,is_default,extra,status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, dict_type_id, item_value, label, locale, color, css_class, sort_order, is_default, extra, status, created_at, updated_at
`

type CreateDictItemParams struct {
	DictTypeID uuid.UUID `json:"dict_type_id"`
	ItemValue  string    `json:"item_value"`
	Label      string    `json:"label"`
	Locale     *string   `json:"locale"`
	Color      *string   `json:"color"`
	CssClass   *string   `json:"css_class"`
	SortOrder  int32     `json:"sort_order"`
	IsDefault  bool      `json:"is_default"`
	Extra      []byte    `json:"extra"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateDictItem(ctx context.Context, arg CreateDictItemParams) (SysDictItem, error) {
	row := q.db.QueryRow(ctx, createDictItem,
		arg.DictTypeID,
		arg.ItemValue,
		arg.Label,
		arg.Locale,
		arg.Color,
		arg.CssClass,
		arg.SortOrder,
		arg.IsDefault,
		arg.Extra,
		arg.Status,
	)
	var i SysDictItem
	err := row.Scan(
		&i.ID,
		&i.DictTypeID,
		&i.ItemValue,
		&i.Label,
		&i.Locale,
		&i.Color,
		&i.CssClass,
		&i.SortOrder,
		&i.IsDefault,
		&i.Extra,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantConfig = `-- name: CreateTenantConfig :one
INSERT INTO sys.config_items (tenant_id, module_code, config_group, config_key, display_name, value_type, value_json, default_value_json, is_secret, secret_ciphertext, secret_key_version, is_public, validation_schema, description, sort_order, status, created_by, updated_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$17) RETURNING id, tenant_id, module_code, config_group, config_key, display_name, value_type, value_json, default_value_json, is_secret, secret_ciphertext, secret_key_version, is_public, validation_schema, description, sort_order, status, version, created_by, updated_by, created_at, updated_at
`

type CreateTenantConfigParams struct {
	TenantID         *uuid.UUID `json:"tenant_id"`
	ModuleCode       string     `json:"module_code"`
	ConfigGroup      string     `json:"config_group"`
	ConfigKey        string     `json:"config_key"`
	DisplayName      string     `json:"display_name"`
	ValueType        string     `json:"value_type"`
	ValueJson        []byte     `json:"value_json"`
	DefaultValueJson []byte     `json:"default_value_json"`
	IsSecret         bool       `json:"is_secret"`
	SecretCiphertext []byte     `json:"secret_ciphertext"`
	SecretKeyVersion *int32     `json:"secret_key_version"`
	IsPublic         bool       `json:"is_public"`
	ValidationSchema []byte     `json:"validation_schema"`
	Description      *string    `json:"description"`
	SortOrder        int32      `json:"sort_order"`
	Status           string     `json:"status"`
	CreatedBy        *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateTenantConfig(ctx context.Context, arg CreateTenantConfigParams) (SysConfigItem, error) {
	row := q.db.QueryRow(ctx, createTenantConfig,
		arg.TenantID,
		arg.ModuleCode,
		arg.ConfigGroup,
		arg.ConfigKey,
		arg.DisplayName,
		arg.ValueType,
		arg.ValueJson,
		arg.DefaultValueJson,
		arg.IsSecret,
		arg.SecretCiphertext,
		arg.SecretKeyVersion,
		arg.IsPublic,
		arg.ValidationSchema,
		arg.Description,
		arg.SortOrder,
		arg.Status,
		arg.CreatedBy,
	)
	var i SysConfigItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleCode,
		&i.ConfigGroup,
		&i.ConfigKey,
		&i.DisplayName,
		&i.ValueType,
		&i.ValueJson,
		&i.DefaultValueJson,
		&i.IsSecret,
		&i.SecretCiphertext,
		&i.SecretKeyVersion,
		&i.IsPublic,
		&i.ValidationSchema,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantDictType = `-- name: CreateTenantDictType :one
INSERT INTO sys.dict_types (tenant_id, code, name, description, is_system, status)
VALUES ($1,$2,$3,$4,false,$5) RETURNING id, tenant_id, code, name, description, is_system, status, created_at, updated_at
`

type CreateTenantDictTypeParams struct {
	TenantID    *uuid.UUID `json:"tenant_id"`
	Code        string     `json:"code"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Status      string     `json:"status"`
}

func (q *Queries) CreateTenantDictType(ctx context.Context, arg CreateTenantDictTypeParams) (SysDictType, error) {
	row := q.db.QueryRow(ctx, createTenantDictType,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i SysDictType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDictItem = `-- name: DeleteDictItem :execrows
DELETE FROM sys.dict_items WHERE id=$1
`

func (q *Queries) DeleteDictItem(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDictItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDictItemForUpdate = `-- name: GetDictItemForUpdate :one
SELECT i.id, i.dict_type_id, i.item_value, i.label, i.locale, i.color, i.css_class, i.sort_order, i.is_default, i.extra, i.status, i.created_at, i.updated_at FROM sys.dict_items i JOIN sys.dict_types d ON d.id=i.dict_type_id
WHERE (d.tenant_id IS NULL OR d.tenant_id=$1) AND i.id=$2 FOR UPDATE OF i
`

type GetDictItemForUpdateParams struct {
	TenantID *uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID  `json:"id"`
}

func (q *Queries) GetDictItemForUpdate(ctx context.Context, arg GetDictItemForUpdateParams) (SysDictItem, error) {
	row := q.db.QueryRow(ctx, getDictItemForUpdate, arg.TenantID, arg.ID)
	var i SysDictItem
	err := row.Scan(
		&i.ID,
		&i.DictTypeID,
		&i.ItemValue,
		&i.Label,
		&i.Locale,
		&i.Color,
		&i.CssClass,
		&i.SortOrder,
		&i.IsDefault,
		&i.Extra,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantConfigForUpdate = `-- name: GetTenantConfigForUpdate :one
SELECT id, tenant_id, module_code, config_group, config_key, display_name, value_type, value_json, default_value_json, is_secret, secret_ciphertext, secret_key_version, is_public, validation_schema, description, sort_order, status, version, created_by, updated_by, created_at, updated_at FROM sys.config_items WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetTenantConfigForUpdateParams struct {
	TenantID *uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID  `json:"id"`
}

func (q *Queries) GetTenantConfigForUpdate(ctx context.Context, arg GetTenantConfigForUpdateParams) (SysConfigItem, error) {
	row := q.db.QueryRow(ctx, getTenantConfigForUpdate, arg.TenantID, arg.ID)
	var i SysConfigItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleCode,
		&i.ConfigGroup,
		&i.ConfigKey,
		&i.DisplayName,
		&i.ValueType,
		&i.ValueJson,
		&i.DefaultValueJson,
		&i.IsSecret,
		&i.SecretCiphertext,
		&i.SecretKeyVersion,
		&i.IsPublic,
		&i.ValidationSchema,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisibleDictType = `-- name: GetVisibleDictType :one
SELECT id, tenant_id, code, name, description, is_system, status, created_at, updated_at FROM sys.dict_types WHERE (tenant_id IS NULL OR tenant_id = $1) AND id = $2
`

type GetVisibleDictTypeParams struct {
	TenantID *uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID  `json:"id"`
}

func (q *Queries) GetVisibleDictType(ctx context.Context, arg GetVisibleDictTypeParams) (SysDictType, error) {
	row := q.db.QueryRow(ctx, getVisibleDictType, arg.TenantID, arg.ID)
	var i SysDictType
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDictItems = `-- name: ListDictItems :many
SELECT id, dict_type_id, item_value, label, locale, color, css_class, sort_order, is_default, extra, status, created_at, updated_at FROM sys.dict_items WHERE dict_type_id = $1 ORDER BY sort_order, id
`

func (q *Queries) ListDictItems(ctx context.Context, dictTypeID uuid.UUID) ([]SysDictItem, error) {
	rows, err := q.db.Query(ctx, listDictItems, dictTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysDictItem{}
	for rows.Next() {
		var i SysDictItem
		if err := rows.Scan(
			&i.ID,
			&i.DictTypeID,
			&i.ItemValue,
			&i.Label,
			&i.Locale,
			&i.Color,
			&i.CssClass,
			&i.SortOrder,
			&i.IsDefault,
			&i.Extra,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleConfigs = `-- name: ListVisibleConfigs :many
SELECT id, tenant_id, module_code, config_group, config_key, display_name, value_type, value_json, default_value_json, is_secret, secret_ciphertext, secret_key_version, is_public, validation_schema, description, sort_order, status, version, created_by, updated_by, created_at, updated_at FROM sys.config_items WHERE tenant_id IS NULL OR tenant_id = $1 ORDER BY sort_order, config_key
`

func (q *Queries) ListVisibleConfigs(ctx context.Context, tenantID *uuid.UUID) ([]SysConfigItem, error) {
	rows, err := q.db.Query(ctx, listVisibleConfigs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysConfigItem{}
	for rows.Next() {
		var i SysConfigItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ModuleCode,
			&i.ConfigGroup,
			&i.ConfigKey,
			&i.DisplayName,
			&i.ValueType,
			&i.ValueJson,
			&i.DefaultValueJson,
			&i.IsSecret,
			&i.SecretCiphertext,
			&i.SecretKeyVersion,
			&i.IsPublic,
			&i.ValidationSchema,
			&i.Description,
			&i.SortOrder,
			&i.Status,
			&i.Version,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleDictTypes = `-- name: ListVisibleDictTypes :many
SELECT id, tenant_id, code, name, description, is_system, status, created_at, updated_at FROM sys.dict_types WHERE tenant_id IS NULL OR tenant_id = $1 ORDER BY name, id
`

func (q *Queries) ListVisibleDictTypes(ctx context.Context, tenantID *uuid.UUID) ([]SysDictType, error) {
	rows, err := q.db.Query(ctx, listVisibleDictTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysDictType{}
	for rows.Next() {
		var i SysDictType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
