// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: useradmin.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const tenantManagedUserExists = `-- name: TenantManagedUserExists :one
SELECT EXISTS (
    SELECT 1
    FROM iam.tenant_members AS tm
    JOIN iam.users AS u ON u.id = tm.user_id
    WHERE tm.tenant_id = $1
      AND tm.user_id = $2
      AND u.deleted_at IS NULL
)
`

type TenantManagedUserExistsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) TenantManagedUserExists(ctx context.Context, arg TenantManagedUserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantManagedUserExists, arg.TenantID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
