import { describe, expect, it } from "vitest";
import { publicWebSchema } from "./public-web";
const config = () => ({ enabled:true, apk_enabled:false,promotion_enabled:true,lock_version:0,translations:{"zh-CN":{name:"应用",introduction:"中文介绍",promotion_title:"下载应用",promotion_description:"发现更多内容",promotion_button_label:"立即下载"},"en-US":{name:"App",introduction:"English description",promotion_title:"Get the app",promotion_description:"Discover more",promotion_button_label:"Download"}},stores:[{id:"13ec836e-1c57-4c67-a8e2-8ab90ce58b8e",name:"Store",enabled:true,priority:1,platform:"ios",web_url:"https://apps.apple.com/app/example"}] as [{id:string;name:string;enabled:boolean;priority:number;platform:string;web_url:string}] });
describe("public web configuration",()=>{
 it("requires both translated publication fields",()=>{const v=config();expect(publicWebSchema.safeParse(v).success).toBe(true);v.translations["en-US"].introduction=" ";expect(publicWebSchema.safeParse(v).success).toBe(false);v.enabled=false;expect(publicWebSchema.safeParse(v).success).toBe(true)});
 it.each(["javascript:alert(1)","http://example.test","https://user:password@example.test","https://example.test/with space"])("rejects unsafe store URL %s",url=>{const v=config();v.stores[0].web_url=url;expect(publicWebSchema.safeParse(v).success).toBe(false)});
 it("rejects unknown platform and duplicate store IDs",()=>{const v=config();v.stores[0].platform="other";expect(publicWebSchema.safeParse(v).success).toBe(false);v.stores[0].platform="ios";v.stores.push(v.stores[0]);expect(publicWebSchema.safeParse(v).success).toBe(false)});
 it("bounds optional promotion copy while allowing built-in fallbacks",()=>{const v=config();v.translations["zh-CN"].promotion_title="";v.translations["zh-CN"].promotion_description="";v.translations["zh-CN"].promotion_button_label="";expect(publicWebSchema.safeParse(v).success).toBe(true);v.translations["en-US"].promotion_description="x".repeat(501);expect(publicWebSchema.safeParse(v).success).toBe(false)});
});
