import { Alert, Button, Card, Checkbox, Descriptions, Drawer, Form, Input, InputNumber, Modal, Select, Space, Table, Tag, Typography, type TableColumnsType } from "antd";
import { useMemo, useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { useTranslation } from "react-i18next";
import { z } from "zod";
import type { AdminWebhook, AdminWebhookDelivery, AdminWebhookRequest } from "../generated/api/types.gen";
import { useAuthStore } from "../features/auth/store";
import { useWebhookDeliveries, useWebhookMutations, useWebhooks } from "../features/webhooks/hooks";

interface Filters { q:string; event_type:string; status:string; page:number; page_size:number }
interface Values { name:string; endpoint_url:string; event_types:string; max_attempts:number; timeout_seconds:number; status:"active"|"disabled" }
const empty:Values={name:"",endpoint_url:"",event_types:"",max_attempts:8,timeout_seconds:10,status:"active"};
const schema=z.object({name:z.string().trim().min(1).max(160),endpoint_url:z.url().startsWith("https://"),event_types:z.string().min(1),max_attempts:z.number().int().min(1).max(100),timeout_seconds:z.number().int().min(1).max(60),status:z.enum(["active","disabled"])});
const readFilters=():Filters=>{const p=new URLSearchParams(location.search);return{q:p.get("q")??"",event_type:p.get("event_type")??"",status:p.get("status")??"",page:Number(p.get("page")??1),page_size:Number(p.get("page_size")??20)}};
function persist(f:Filters){const p=new URLSearchParams();Object.entries(f).forEach(([k,v])=>{if(v!==""&&!(k==="page"&&v===1)&&!(k==="page_size"&&v===20))p.set(k,String(v))});history.replaceState(history.state,"",`${location.pathname}${p.size?`?${p}`:""}`)}

export function AdminWebhooksPage(){
  const{t,i18n}=useTranslation();const permissions=new Set(useAuthStore(s=>s.context?.permissions??[]));const[filters,setState]=useState(readFilters);const setFilters=(f:Filters)=>{setState(f);persist(f)};const query=useWebhooks(filters);const mutations=useWebhookMutations();const[editing,setEditing]=useState<AdminWebhook|"new"|null>(null);const[secret,setSecret]=useState<string|null>(null);const[ack,setAck]=useState(false);const[deliveriesFor,setDeliveriesFor]=useState<AdminWebhook|null>(null);const[feedback,setFeedback]=useState<{key:string;error?:boolean}|null>(null);const form=useForm<Values>({defaultValues:empty});const formatter=useMemo(()=>new Intl.DateTimeFormat(i18n.language,{dateStyle:"medium",timeStyle:"short"}),[i18n.language]);
  const open=(item:AdminWebhook|"new")=>{setEditing(item);form.reset(item==="new"?empty:{name:item.name,endpoint_url:item.endpoint_url,event_types:item.event_types.join("\n"),max_attempts:item.max_attempts,timeout_seconds:item.timeout_seconds,status:item.status})};
  const save=form.handleSubmit(async(raw)=>{const parsed=schema.safeParse(raw);if(!parsed.success){setFeedback({key:"webhooks.feedback.validation",error:true});return}const input:AdminWebhookRequest={...parsed.data,event_types:parsed.data.event_types.split(/[,\n]/).map(v=>v.trim().toLowerCase()).filter(Boolean)};try{if(editing==="new"){const out=await mutations.create.mutateAsync(input);setSecret(out.signing_secret);setAck(false)}else if(editing){await mutations.update.mutateAsync({id:editing.id,input})}setEditing(null);setFeedback({key:"webhooks.feedback.saved"})}catch{setFeedback({key:"webhooks.feedback.error",error:true})}});
  const test=(item:AdminWebhook)=>{Modal.confirm({title:t("webhooks.test.title"),content:t("webhooks.test.confirm",{name:item.name,event:item.event_types[0]??""}),okText:t("webhooks.actions.test"),cancelText:t("common.actions.cancel"),onOk:async()=>{try{const key=`admin-${crypto.randomUUID()}`;const delivery=await mutations.test.mutateAsync({id:item.id,key,input:{event_type:item.event_types[0]??"",payload:{source:"admin-console"}}});setFeedback({key:delivery.status==="succeeded"?"webhooks.feedback.test_succeeded":"webhooks.feedback.test_failed",error:delivery.status!=="succeeded"})}catch{setFeedback({key:"webhooks.feedback.test_failed",error:true})}}})};
  const columns:TableColumnsType<AdminWebhook>=[{title:t("webhooks.columns.name"),render:(_,x)=><><strong>{x.name}</strong><div className="ak-table-secondary">{x.endpoint_url}</div></>},{title:t("webhooks.columns.events"),render:(_,x)=><Space wrap>{x.event_types.slice(0,3).map(v=><Tag key={v}>{v}</Tag>)}</Space>,responsive:["md"]},{title:t("webhooks.columns.status"),dataIndex:"status",render:(v:string)=><Tag className={v==="active"?"ak-status-success":"ak-status-error"}>{t(`webhooks.status.${v}`)}</Tag>},{title:t("webhooks.columns.delivery"),render:(_,x)=>t("webhooks.columns.delivery_value",{attempts:x.max_attempts,seconds:x.timeout_seconds}),responsive:["lg"]},{title:t("webhooks.columns.actions"),render:(_,x)=><Space wrap>{permissions.has("sys.webhook.update")&&<Button size="small" onClick={()=>{open(x)}}>{t("common.actions.edit")}</Button>}{permissions.has("sys.webhook.test")&&<Button size="small" onClick={()=>{test(x)}}>{t("webhooks.actions.test")}</Button>}{permissions.has("sys.webhook.delivery.read")&&<Button size="small" onClick={()=>{setDeliveriesFor(x)}}>{t("webhooks.actions.deliveries")}</Button>}</Space>}];
  return <div className="ak-page-container"><header className="ak-page-heading ak-org-heading"><div><Typography.Title level={1}>{t("webhooks.title")}</Typography.Title><Typography.Paragraph type="secondary">{t("webhooks.description")}</Typography.Paragraph></div>{permissions.has("sys.webhook.create")&&<Button type="primary" onClick={()=>{open("new")}}>{t("webhooks.actions.create")}</Button>}</header>{feedback&&<div className={feedback.error?"ak-form-error":"ak-org-feedback"} role="status">{t(feedback.key)}</div>}<Alert showIcon type="warning" title={t("webhooks.safety.title")} description={t("webhooks.safety.description")} className="ak-schedule-safety"/><Card><div className="ak-settings-filters" role="search" aria-label={t("webhooks.filters.landmark")}><Input.Search aria-label={t("webhooks.filters.query")} value={filters.q} onChange={e=>{setFilters({...filters,q:e.target.value,page:1})}}/><Input aria-label={t("webhooks.filters.event_type")} value={filters.event_type} onChange={e=>{setFilters({...filters,event_type:e.target.value,page:1})}}/><Select allowClear aria-label={t("webhooks.filters.status")} value={filters.status||undefined} onChange={v=>{setFilters({...filters,status:v??"",page:1})}} options={["active","disabled"].map(v=>({value:v,label:t(`webhooks.status.${v}`)}))}/></div><Table rowKey="id" columns={columns} dataSource={query.data?.items??[]} loading={query.isPending} locale={{emptyText:t("webhooks.empty")}} pagination={{current:filters.page,pageSize:filters.page_size,total:query.data?.total??0,onChange:(page,page_size)=>{setFilters({...filters,page,page_size})}}}/></Card>
  <Drawer destroyOnHidden size="large" open={editing!==null} title={t(editing==="new"?"webhooks.editor.create":"webhooks.editor.edit")} onClose={()=>{setEditing(null)}} extra={<Button type="primary" loading={mutations.create.isPending||mutations.update.isPending} onClick={()=>void save()}>{t("common.actions.save")}</Button>}><Form layout="vertical" onFinish={()=>void save()}><Controller name="name" control={form.control} render={({field})=><Form.Item label={t("webhooks.editor.name")}><Input {...field} aria-label={t("webhooks.editor.name")}/></Form.Item>}/><Controller name="endpoint_url" control={form.control} render={({field})=><Form.Item label={t("webhooks.editor.url")} extra={t("webhooks.editor.url_help")}><Input {...field} aria-label={t("webhooks.editor.url")}/></Form.Item>}/><Controller name="event_types" control={form.control} render={({field})=><Form.Item label={t("webhooks.editor.events")} extra={t("webhooks.editor.events_help")}><Input.TextArea {...field} aria-label={t("webhooks.editor.events")} rows={4}/></Form.Item>}/><Controller name="max_attempts" control={form.control} render={({field})=><Form.Item label={t("webhooks.editor.max_attempts")}><InputNumber {...field} aria-label={t("webhooks.editor.max_attempts")} min={1} max={100}/></Form.Item>}/><Controller name="timeout_seconds" control={form.control} render={({field})=><Form.Item label={t("webhooks.editor.timeout")}><InputNumber {...field} aria-label={t("webhooks.editor.timeout")} min={1} max={60}/></Form.Item>}/><Controller name="status" control={form.control} render={({field})=><Form.Item label={t("webhooks.editor.status")}><Select {...field} aria-label={t("webhooks.editor.status")} options={["active","disabled"].map(v=>({value:v,label:t(`webhooks.status.${v}`)}))}/></Form.Item>}/></Form></Drawer>
  <Modal open={secret!==null} closable={false} mask={{closable:false}} title={t("webhooks.secret.title")} okButtonProps={{disabled:!ack}} okText={t("webhooks.secret.close")} cancelButtonProps={{style:{display:"none"}}} onOk={()=>{setSecret(null);setAck(false)}}><Alert type="error" showIcon title={t("webhooks.secret.warning")}/><Input.TextArea className="ak-code-input" value={secret??""} readOnly rows={3} aria-label={t("webhooks.secret.value")}/><Space orientation="vertical"><Button onClick={()=>void navigator.clipboard.writeText(secret??"")}>{t("common.actions.copy")}</Button><Checkbox checked={ack} onChange={e=>{setAck(e.target.checked)}}>{t("webhooks.secret.ack")}</Checkbox></Space></Modal>
  {deliveriesFor&&<WebhookDeliveriesDrawer endpoint={deliveriesFor} open onClose={()=>{setDeliveriesFor(null)}} formatter={formatter}/>}</div>
}

function WebhookDeliveriesDrawer({endpoint,open,onClose,formatter}:{endpoint:AdminWebhook;open:boolean;onClose:()=>void;formatter:Intl.DateTimeFormat}){const{t}=useTranslation();const[page,setPage]=useState(1);const query=useWebhookDeliveries(endpoint.id,page,20);const[selected,setSelected]=useState<AdminWebhookDelivery|null>(null);const columns:TableColumnsType<AdminWebhookDelivery>=[{title:t("webhooks.deliveries.columns.event"),render:(_,x)=><><strong>{x.event_type}</strong><div className="ak-table-secondary"><code>{x.event_id}</code></div></>},{title:t("webhooks.deliveries.columns.status"),dataIndex:"status",render:(v:string)=><Tag className={v==="succeeded"?"ak-status-success":v==="failed"?"ak-status-error":"ak-status-warning"}>{t(`webhooks.delivery_status.${v}`)}</Tag>},{title:t("webhooks.deliveries.columns.attempts"),dataIndex:"attempt_count"},{title:t("webhooks.deliveries.columns.created"),dataIndex:"created_at",render:(v:string)=>formatter.format(new Date(v)),responsive:["md"]},{title:t("webhooks.columns.actions"),render:(_,x)=><Button size="small" onClick={()=>{setSelected(x)}}>{t("common.actions.view")}</Button>}];const summary=selected?.last_error??selected?.response_body??t("common.not_available");return <Drawer size="large" open={open} title={t("webhooks.deliveries.title",{name:endpoint.name})} onClose={onClose}><Table rowKey="id" columns={columns} dataSource={query.data?.items??[]} loading={query.isPending} locale={{emptyText:t("webhooks.deliveries.empty")}} pagination={{current:page,pageSize:20,total:query.data?.total??0,onChange:setPage}}/><Drawer open={selected!==null} title={t("webhooks.deliveries.detail")} onClose={()=>{setSelected(null)}}><Descriptions column={1} bordered items={selected?[{key:"event",label:t("webhooks.deliveries.fields.event_id"),children:<code>{selected.event_id}</code>},{key:"status",label:t("webhooks.deliveries.fields.status"),children:t(`webhooks.delivery_status.${selected.status}`)},{key:"http",label:t("webhooks.deliveries.fields.response_status"),children:selected.response_status??t("common.not_available")},{key:"summary",label:t("webhooks.deliveries.fields.summary"),children:summary},{key:"payload",label:t("webhooks.deliveries.fields.payload"),children:<pre className="ak-json-preview">{JSON.stringify(selected.payload,null,2)}</pre>}]:[]}/></Drawer></Drawer>}

export function AdminWebhookDeliveriesPage({webhookId}:{webhookId:string}){const{t,i18n}=useTranslation();const query=useWebhooks({page:1,page_size:100});const endpoint=query.data?.items.find(v=>v.id===webhookId);const formatter=useMemo(()=>new Intl.DateTimeFormat(i18n.language,{dateStyle:"medium",timeStyle:"short"}),[i18n.language]);if(query.isPending)return <Card loading/>;if(!endpoint)return <Alert type="error" showIcon title={t("webhooks.deliveries.not_found")}/>;return <div className="ak-page-container"><Typography.Title level={1}>{t("webhooks.deliveries.title",{name:endpoint.name})}</Typography.Title><WebhookDeliveriesDrawer endpoint={endpoint} open onClose={()=>{ history.back(); }} formatter={formatter}/></div>}
