import { Alert, Button, Card, Checkbox, Drawer, Form, Grid, Input, Modal, Select, Space, Table, Tag, Typography, type TableColumnsType } from "antd";
import { Controller, useForm } from "react-hook-form";
import { useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { z } from "zod";
import type { AdminApiClient, AdminApiClientRequest } from "../generated/api/types.gen";
import { useAuthStore } from "../features/auth/store";
import { useAdminPermissions } from "../features/access/hooks";
import { useApiClientMutations, useApiClients } from "../features/api-clients/hooks";
import { useManagedApplications } from "../features/apps/hooks";
import { useAdminUsers } from "../features/users/hooks";

interface Values {name:string;description:string;allowed_cidrs:string;status:"active"|"disabled";expires_at:string;bound_user_id:string}
const schema=z.object({name:z.string().trim().min(1).max(160),description:z.string().max(500),allowed_cidrs:z.string(),status:z.enum(["active","disabled"]),expires_at:z.string(),bound_user_id:z.string()});
const empty:Values={name:"",description:"",allowed_cidrs:"",status:"active",expires_at:"",bound_user_id:""};
const filters=()=>{const p=new URLSearchParams(location.search);return{q:p.get("q")??"",status:p.get("status")??"",page:Number(p.get("page")??1),page_size:Number(p.get("page_size")??20)}};
export function AdminApiClientsPage(){const{t}=useTranslation();const navigate=useNavigate();const screens=Grid.useBreakpoint();const permissions=new Set(useAuthStore(s=>s.context?.permissions??[]));const[f,setF]=useState(filters);const persist=(n:typeof f)=>{setF(n);const p=new URLSearchParams();Object.entries(n).forEach(([k,v])=>{if(v!==""&&!(k==="page"&&v===1)&&!(k==="page_size"&&v===20))p.set(k,String(v))});history.replaceState(history.state,"",`${location.pathname}${p.size?`?${p}`:""}`)};const query=useApiClients(f);const mutations=useApiClientMutations();const catalog=useAdminPermissions({status:"active"});const applications=useManagedApplications({q:"",page:1,page_size:100});const users=useAdminUsers({status:"active",page:1,page_size:100,sort:"name_asc"});const[editing,setEditing]=useState<AdminApiClient|"new"|null>(null);const[permissionClient,setPermissionClient]=useState<AdminApiClient|null>(null);const[appClient,setAppClient]=useState<AdminApiClient|null>(null);const[secretClient,setSecretClient]=useState<AdminApiClient|null>(null);const[selectedPermissions,setSelectedPermissions]=useState<string[]>([]);const[selectedApps,setSelectedApps]=useState<string[]>([]);const[secret,setSecret]=useState<string|null>(null);const[ack,setAck]=useState(false);const[feedback,setFeedback]=useState<string|null>(null);const form=useForm<Values>({defaultValues:empty});
const open=(c:AdminApiClient|"new")=>{setEditing(c);form.reset(c==="new"?empty:{name:c.name,description:c.description,allowed_cidrs:c.allowed_cidrs.join("\n"),status:c.status,expires_at:c.expires_at?.slice(0,16)??"",bound_user_id:c.bound_user_id??""})};const save=form.handleSubmit(async raw=>{const parsed=schema.safeParse(raw);if(!parsed.success)return;const expiresAt=parsed.data.expires_at?new Date(parsed.data.expires_at).toISOString():null;const input:AdminApiClientRequest={name:parsed.data.name,description:parsed.data.description,allowed_cidrs:parsed.data.allowed_cidrs.split(/[,\n]/).map(v=>v.trim()).filter(Boolean),status:parsed.data.status,bound_user_id:parsed.data.bound_user_id||null,...(expiresAt?{expires_at:expiresAt}:{})};try{if(editing==="new")await mutations.create.mutateAsync(input);else if(editing)await mutations.update.mutateAsync({id:editing.id,input});setEditing(null);setFeedback("api_clients.feedback.saved")}catch{setFeedback("api_clients.feedback.error")}});
const rotate=async(c:AdminApiClient)=>{try{const out=await mutations.secret.mutateAsync({id:c.id,input:{}});setSecretClient(current=>current?.id===c.id?{...current,secrets:[out.metadata,...current.secrets]}:current);setSecret(out.secret);setAck(false)}catch{setFeedback("api_clients.feedback.error")}};
const allColumns:TableColumnsType<AdminApiClient>=[{title:t("api_clients.columns.name"),key:"name",render:(_,c)=><><strong>{c.name}</strong><div className="ak-table-secondary"><code>{c.client_id}</code></div></>},{title:t("api_clients.columns.status"),dataIndex:"status",render:(v:string)=><Tag className={v==="active"?"ak-status-success":"ak-status-error"}>{t(`api_clients.status.${v}`)}</Tag>},{title:t("api_clients.columns.bound_user"),render:(_,c)=>c.bound_user?<><strong>{c.bound_user.display_name}</strong>{c.bound_user.email?<div className="ak-table-secondary">{c.bound_user.email}</div>:null}</>:t("api_clients.bound_user.unbound")},{title:t("api_clients.columns.apps"),render:(_,c)=>c.app_ids.length},{title:t("api_clients.columns.cidrs"),render:(_,c)=>c.allowed_cidrs.length>0?c.allowed_cidrs.length:t("api_clients.cidrs.any")},{title:t("api_clients.columns.secrets"),render:(_,c)=>c.secrets.filter(s=>!s.revoked_at).length},{title:t("api_clients.columns.actions"),width:screens.md?330:150,render:(_,c)=><Space wrap><Button size="small" onClick={()=>{void navigate({to:"/system/integrations/api-clients/$clientId",params:{clientId:c.id}})}}>{t("common.actions.view")}</Button>{permissions.has("sys.api_client.update")&&<Button size="small" onClick={()=>{ open(c); }}>{t("common.actions.edit")}</Button>}{permissions.has("sys.api_client.update")&&<Button size="small" onClick={()=>{setAppClient(c);setSelectedApps(c.app_ids)}}>{t("api_clients.actions.apps")}</Button>}{(permissions.has("sys.api_client.rotate_secret")||permissions.has("sys.api_client.revoke_secret"))&&<Button size="small" onClick={()=>{setSecretClient(c)}}>{t("api_clients.actions.secrets")}</Button>}{permissions.has("sys.api_client.assign_permission")&&<Button size="small" onClick={()=>{setPermissionClient(c);setSelectedPermissions(c.permissions)}}>{t("api_clients.actions.permissions")}</Button>}</Space>}];
const compactColumns=allColumns.filter((_,index)=>index===0||index===6);
const columns:TableColumnsType<AdminApiClient>=screens.md?allColumns:compactColumns;
return <div className="ak-page-container"><header className="ak-page-heading ak-org-heading"><div><Typography.Title level={1}>{t("api_clients.title")}</Typography.Title><Typography.Paragraph type="secondary">{t("api_clients.description")}</Typography.Paragraph></div>{permissions.has("sys.api_client.create")&&<Button type="primary" onClick={()=>{ open("new"); }}>{t("api_clients.actions.create")}</Button>}</header>{feedback&&<div className={feedback.endsWith("error")?"ak-form-error":"ak-org-feedback"} role="status">{t(feedback)}</div>}<Alert showIcon type="warning" title={t("api_clients.safety.title")} description={t("api_clients.safety.description")} className="ak-schedule-safety"/><Card><div className="ak-settings-filters" role="search" aria-label={t("api_clients.filters.landmark")}><Input.Search aria-label={t("api_clients.filters.query")} value={f.q} onChange={e=>{ persist({...f,q:e.target.value,page:1}); }}/><Select allowClear aria-label={t("api_clients.filters.status")} value={f.status||undefined} onChange={v=>{ persist({...f,status:v??"",page:1}); }} options={["active","disabled"].map(v=>({value:v,label:t(`api_clients.status.${v}`)}))}/></div><Table rowKey="id" columns={columns} dataSource={query.data?.items??[]} loading={query.isPending} locale={{emptyText:t("api_clients.empty")}} pagination={{current:f.page,pageSize:f.page_size,total:query.data?.total??0,onChange:(page,page_size)=>{ persist({...f,page,page_size}); }}}/></Card>
<Drawer className="ak-api-client-editor-drawer" destroyOnHidden size="large" open={editing!==null} title={t(editing==="new"?"api_clients.editor.create":"api_clients.editor.edit")} onClose={()=>{ setEditing(null); }} extra={<Button type="primary" loading={mutations.create.isPending||mutations.update.isPending} onClick={()=>void save()}>{t("common.actions.save")}</Button>}><Form layout="vertical" onFinish={()=>void save()}>{(["name","description"] as const).map(name=><Controller key={name} name={name} control={form.control} render={({field})=><Form.Item label={t(`api_clients.editor.${name}`)}><Input {...field} aria-label={t(`api_clients.editor.${name}`)}/></Form.Item>}/>) }<Controller name="bound_user_id" control={form.control} render={({field})=><Form.Item label={t("api_clients.editor.bound_user")} extra={t("api_clients.editor.bound_user_help")}><Select {...field} allowClear showSearch={{optionFilterProp:"label"}} aria-label={t("api_clients.editor.bound_user")} loading={users.isPending} notFoundContent={t(users.isError?"api_clients.bound_user.load_error":"api_clients.bound_user.empty")} onChange={(value:string|undefined)=>{field.onChange(value??"")}} options={(users.data?.items??[]).map(user=>({value:user.id,label:user.email?`${user.display_name} · ${user.email}`:user.display_name}))} placeholder={t("api_clients.bound_user.unbound")} value={field.value===""?undefined:field.value}/></Form.Item>}/><Controller name="allowed_cidrs" control={form.control} render={({field})=><Form.Item label={t("api_clients.editor.cidrs")} extra={t("api_clients.editor.cidrs_help")}><Input.TextArea {...field} aria-label={t("api_clients.editor.cidrs")} rows={4}/></Form.Item>}/><Controller name="status" control={form.control} render={({field})=><Form.Item label={t("api_clients.editor.status")}><Select {...field} aria-label={t("api_clients.editor.status")} options={["active","disabled"].map(v=>({value:v,label:t(`api_clients.status.${v}`)}))}/></Form.Item>}/><Controller name="expires_at" control={form.control} render={({field})=><Form.Item label={t("api_clients.editor.expires")}><Input {...field} aria-label={t("api_clients.editor.expires")} type="datetime-local"/></Form.Item>}/></Form></Drawer>
<Modal open={secret!==null} closable={false} mask={{closable:false}} title={t("api_clients.secret.title")} okButtonProps={{disabled:!ack}} okText={t("api_clients.secret.close")} cancelButtonProps={{style:{display:"none"}}} onOk={()=>{setSecret(null);setAck(false)}}><Alert type="error" showIcon title={t("api_clients.secret.warning")}/><Input.TextArea aria-label={t("api_clients.secret.value")} className="ak-code-input" value={secret??""} readOnly rows={3}/><Button onClick={()=>void navigator.clipboard.writeText(secret??"")}>{t("common.actions.copy")}</Button><Checkbox checked={ack} onChange={e=>{ setAck(e.target.checked); }}>{t("api_clients.secret.ack")}</Checkbox></Modal>
<Drawer open={secretClient!==null} title={t("api_clients.secrets.title")} onClose={()=>{setSecretClient(null)}} extra={secretClient&&permissions.has("sys.api_client.rotate_secret")?<Button type="primary" onClick={()=>void rotate(secretClient)}>{t("api_clients.actions.rotate")}</Button>:null}><Alert showIcon type="info" title={t("api_clients.secrets.limit")}/><Space orientation="vertical" style={{width:"100%"}}>{secretClient?.secrets.map(item=><Card size="small" key={item.id}><Space wrap><code>{item.prefix}</code><Tag className={item.revoked_at?"ak-status-error":"ak-status-success"}>{t(item.revoked_at?"api_clients.secrets.revoked":"api_clients.secrets.active")}</Tag>{!item.revoked_at&&permissions.has("sys.api_client.revoke_secret")&&<Button danger size="small" onClick={()=>{Modal.confirm({title:t("api_clients.secrets.revoke_title"),content:t("api_clients.secrets.revoke_confirm",{prefix:item.prefix}),okText:t("api_clients.secrets.revoke"),cancelText:t("common.actions.cancel"),onOk:async()=>{await mutations.revoke.mutateAsync({id:secretClient.id,secretId:item.id});setSecretClient(null);setFeedback("api_clients.feedback.revoked")}})}}>{t("api_clients.secrets.revoke")}</Button>}</Space></Card>)}</Space></Drawer>
<Drawer open={permissionClient!==null} title={t("api_clients.permissions.title")} onClose={()=>{ setPermissionClient(null); }} extra={<Button type="primary" onClick={()=>{void (async()=>{if(!permissionClient)return;await mutations.permissions.mutateAsync({id:permissionClient.id,input:{permission_codes:selectedPermissions}});setPermissionClient(null)})()}}>{t("common.actions.save")}</Button>}><Select aria-label={t("api_clients.permissions.selector")} mode="multiple" style={{width:"100%"}} value={selectedPermissions} onChange={setSelectedPermissions} options={(catalog.data?.items??[]).map(p=>({value:p.code,label:p.code}))}/></Drawer>
<Drawer open={appClient!==null} title={t("api_clients.apps.title")} onClose={()=>{ setAppClient(null); }} extra={<Button type="primary" loading={mutations.apps.isPending} onClick={()=>{void (async()=>{if(!appClient)return;await mutations.apps.mutateAsync({id:appClient.id,input:{app_ids:selectedApps}});setAppClient(null);setFeedback("api_clients.feedback.apps_saved")})()}}>{t("common.actions.save")}</Button>}><Alert showIcon type="info" title={t("api_clients.apps.empty_denies")} /><Select aria-label={t("api_clients.apps.selector")} loading={applications.isPending} mode="multiple" style={{width:"100%",marginTop:16}} value={selectedApps} onChange={setSelectedApps} options={(applications.data?.items??[]).map(app=>({value:app.id,label:app.name}))}/></Drawer></div>}
