import { Button, Card, Grid, Input, Select, Table, Tag, Typography, type TableColumnsType } from 'antd'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'

import type { AdminPermission, AdminPermissionKind } from '../generated/api/types.gen'
import { useAdminPermissions } from '../features/access/hooks'

interface Filters{q:string;module_code:string;resource_name:string;action_name:string;permission_kind:''|AdminPermissionKind;status:''|'active'|'disabled'}
function initial():Filters{const p=new URLSearchParams(location.search);const kind=p.get('permission_kind');const status=p.get('status');return{q:p.get('q')??'',module_code:p.get('module_code')??'',resource_name:p.get('resource_name')??'',action_name:p.get('action_name')??'',permission_kind:kind==='api'||kind==='ui_action'||kind==='feature'?kind:'',status:status==='active'||status==='disabled'?status:''}}
export function AdminPermissionsPage(){const{t}=useTranslation();const screens=Grid.useBreakpoint();const[filters,setFilters]=useState(initial);const[feedback,setFeedback]=useState<string|null>(null);const query=useAdminPermissions(filters)
  useEffect(()=>{const p=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value)p.set(key,String(value))});history.replaceState(null,'',`${location.pathname}${p.size?`?${p}`:''}`)},[filters])
  const modules=[...new Set((query.data?.items??[]).map((item)=>item.module_code))].sort();const copy=async(code:string)=>{await navigator.clipboard.writeText(code);setFeedback(t('system.access.permissions.copied',{code}))}
  const columns:TableColumnsType<AdminPermission>=[{title:t('system.access.permissions.fields.code'),dataIndex:'code',render:(code:string)=><div><code className="ak-permission-code">{code}</code><Button type="link" onClick={()=>void copy(code)}>{t('system.access.permissions.copy')}</Button></div>},{title:t('system.access.permissions.fields.resource'),key:'resource',responsive:['md'],render:(_,item)=>`${item.module_code} / ${item.resource_name}`},{title:t('system.access.permissions.fields.action'),dataIndex:'action_name',responsive:['lg']},{title:t('system.access.permissions.fields.kind'),dataIndex:'permission_kind',responsive:['lg'],render:(value:string)=><Tag>{t(`system.access.permissions.kind.${value}`)}</Tag>},{title:t('system.access.permissions.fields.status'),dataIndex:'status',render:(value:string)=><Tag className={value==='active'?'ak-status-success':'ak-status-neutral'}>{t(`system.access.status.${value}`)}</Tag>}]
  return <div className="ak-page-container"><header className="ak-page-heading"><div><Typography.Title level={1}>{t('routes.system.access.permissions.title')}</Typography.Title><Typography.Paragraph type="secondary">{t('system.access.permissions.description')}</Typography.Paragraph></div><Tag>{t('system.access.permissions.read_only')}</Tag></header><Card><div className="ak-access-filters" role="search"><Input.Search allowClear aria-label={t('system.access.permissions.filters.query')} value={filters.q} onChange={(e)=>{ setFilters((x)=>({...x,q:e.target.value})); }}/><Select allowClear aria-label={t('system.access.permissions.filters.module')} placeholder={t('system.access.permissions.filters.module')} value={filters.module_code||undefined} onChange={(value)=>{ setFilters((x)=>({...x,module_code:value??''})); }} options={modules.map((value)=>({value,label:value}))}/><Select allowClear aria-label={t('system.access.permissions.filters.kind')} placeholder={t('system.access.permissions.filters.kind')} value={filters.permission_kind||undefined} onChange={(value)=>{ setFilters((x)=>({...x,permission_kind:value??''})); }} options={['api','ui_action','feature'].map((value)=>({value,label:t(`system.access.permissions.kind.${value}`)}))}/><Select allowClear aria-label={t('system.access.permissions.filters.status')} placeholder={t('system.access.permissions.filters.status')} value={filters.status||undefined} onChange={(value)=>{ setFilters((x)=>({...x,status:value??''})); }} options={['active','disabled'].map((value)=>({value,label:t(`system.access.status.${value}`)}))}/></div>{feedback?<div className="ak-org-feedback" role="status">{feedback}</div>:null}{query.isError?<div className="ak-form-error" role="alert">{t('system.access.load_error')} <Button onClick={()=>{void query.refetch()}}>{t('common.actions.retry')}</Button></div>:null}<Table columns={columns} dataSource={query.data?.items??[]} loading={query.isPending} locale={{emptyText:t('system.access.permissions.empty')}} pagination={{pageSize:20,showSizeChanger:true}} rowKey="id" scroll={{x:screens.md?900:430}}/></Card></div>}
