import { Alert, Button, Card, Descriptions, Modal, Tag, Typography } from 'antd'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'

import { useAuthStore } from '../features/auth/store'
import { useAuditSecurityEvent, useResolveAuditSecurityEvent } from '../features/audit/hooks'
import { ApiError } from '../shared/api/error'
import { useLocale } from '../shared/i18n'
import { AuditJSON, AuditRetry, formatAuditTime } from './AuditShared'

export function AdminSecurityEventDetailPage({ eventId }: { eventId: string }) {
  const { t } = useTranslation(); const { locale } = useLocale(); const permissions = new Set(useAuthStore((state) => state.context?.permissions ?? [])); const event = useAuditSecurityEvent(eventId); const resolve = useResolveAuditSecurityEvent(); const [feedback, setFeedback] = useState<{ key: string; error: boolean } | null>(null)
  const confirmResolve = () => { Modal.confirm({ title: t('system.audit.resolve.title'), content: t('system.audit.resolve.impact'), okText: t('system.audit.actions.resolve'), cancelText: t('common.actions.cancel'), onOk: async () => { try { await resolve.mutateAsync(eventId); setFeedback({ key: 'system.audit.resolve.success', error: false }) } catch (error) { setFeedback({ key: error instanceof ApiError ? error.messageKey : 'errors.common.unknown', error: true }) } } }) }
  if (event.isPending) return <div className="ak-centered-state" aria-live="polite"><span className="ak-loading-indicator"/><span>{t('common.states.loading')}</span></div>
  if (event.isError) return <div className="ak-page-container"><AuditRetry retry={() => { void event.refetch() }} t={t}/></div>
  const value = event.data
  return <div className="ak-page-container"><a className="ak-back-link" href="/system/security/events" onClick={(browserEvent) => { browserEvent.preventDefault(); history.back() }}>{t('system.audit.event_detail.back')}</a><header className="ak-page-heading"><div><Typography.Title level={1}>{t('routes.system.security.event-detail.title')}</Typography.Title><Typography.Paragraph type="secondary">{value.event_type}</Typography.Paragraph></div>{!value.resolved_at && permissions.has('audit.security.resolve') ? <Button type="primary" loading={resolve.isPending} onClick={confirmResolve}>{t('system.audit.actions.resolve')}</Button> : null}</header>{feedback ? <div className={feedback.error ? 'ak-form-error' : 'ak-org-feedback'} role={feedback.error ? 'alert' : 'status'}>{t(feedback.key)}</div> : null}<Card title={t('system.audit.event_detail.metadata')}><Descriptions bordered column={{ xs: 1, md: 2 }} items={[{ key: 'type', label: t('system.audit.fields.event_type'), children: value.event_type }, { key: 'severity', label: t('system.audit.fields.severity'), children: <Tag className={`ak-audit-severity-${value.severity}`}>{t(`system.audit.values.${value.severity}`)}</Tag> }, { key: 'source', label: t('system.audit.fields.source'), children: value.source }, { key: 'status', label: t('system.audit.fields.status'), children: <Tag className={value.resolved_at ? 'ak-status-success' : 'ak-status-warning'}>{t(`system.audit.values.${value.resolved_at ? 'resolved' : 'open'}`)}</Tag> }, { key: 'time', label: t('system.audit.fields.time'), children: formatAuditTime(value.occurred_at, locale) }, { key: 'ip', label: t('system.audit.fields.ip'), children: value.client_ip || t('system.audit.values.unknown') }, { key: 'user', label: t('system.audit.fields.user_id'), children: value.user_id ?? t('system.audit.values.unknown') }, { key: 'session', label: t('system.audit.fields.session_id'), children: value.session_id ?? t('system.audit.values.unknown') }, ...(value.resolved_by ? [{ key: 'resolved', label: t('system.audit.fields.resolved_by'), children: value.resolved_by }] : []) ]}/></Card><Card className="ak-audit-details-card" title={t('system.audit.event_detail.details')}><Alert showIcon type="info" title={t('system.audit.event_detail.redaction_notice')}/><AuditJSON value={value.details} empty={t('system.audit.operation_detail.empty_json')} label={t('system.audit.event_detail.details')}/></Card></div>
}
