import { Button, Card, Checkbox, Empty, Form, Input, InputNumber, Radio, Select, Space, Tabs, Tag, Tree, Typography } from 'antd'
import { useEffect, useMemo, useState } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { z } from 'zod'

import type { AdminMenuNode, AdminOrgUnit, AdminRoleRequest } from '../generated/api/types.gen'
import { useAdminMenus, useAdminPermissions, useAdminRoleMutations, useAdminRoles } from '../features/access/hooks'
import { useAuthStore } from '../features/auth/store'
import { useOrgUnits } from '../features/org/hooks'
import { ApiError } from '../shared/api/error'

const basicSchema=z.object({code:z.string().regex(/^[a-z][a-z0-9._-]{1,127}$/),name:z.string().trim().min(1).max(120),description:z.string().max(500),sort_order:z.number().int(),status:z.enum(['active','disabled'])})
type BasicValues=z.infer<typeof basicSchema>
const tabs=['basic','permissions','menus','data-scope','members'] as const;type Tab=(typeof tabs)[number]
interface MenuTreeNode{key:string;title:string;children:MenuTreeNode[]}
function menuTree(nodes:AdminMenuNode[],label:(node:AdminMenuNode)=>string):MenuTreeNode[]{return nodes.map((node)=>({key:node.id,title:`${label(node)} (${node.code})`,children:menuTree(node.children,label)}))}
function flatUnits(nodes:AdminOrgUnit[]):AdminOrgUnit[]{return nodes.flatMap((node)=>[node,...flatUnits(node.children)])}

export function AdminRoleDetailPage({roleId}:{roleId:string}){
  const {t,i18n}=useTranslation();const permissions=new Set(useAuthStore((state)=>state.context?.permissions??[]));const [feedback,setFeedback]=useState<string|null>(null)
  const initialTab=useMemo(()=>{const value=new URLSearchParams(location.search).get('tab');return tabs.includes(value as Tab)?value as Tab:'basic'},[]);const[tab,setTab]=useState<Tab>(initialTab)
  const roles=useAdminRoles({page:1,page_size:100});const catalog=useAdminPermissions({});const menus=useAdminMenus();const units=useOrgUnits('','');const mutations=useAdminRoleMutations();const role=roles.data?.items.find((item)=>item.id===roleId)
  const form=useForm<BasicValues>({defaultValues:{code:'',name:'',description:'',sort_order:0,status:'active'}});const[selectedPermissions,setSelectedPermissions]=useState<string[]>([]);const[selectedMenus,setSelectedMenus]=useState<string[]>([]);const[scope,setScope]=useState('self');const[scopeUnits,setScopeUnits]=useState<string[]>([])
  useEffect(()=>{if(role){form.reset({code:role.code,name:role.name,description:role.description,sort_order:role.sort_order,status:role.status});setSelectedPermissions(role.permission_ids);setSelectedMenus(role.menu_ids);setScope(role.data_scope);setScopeUnits(role.scope_unit_ids)}},[form,role])
  const errorText=(error:unknown)=>t(error instanceof ApiError?error.messageKey:'errors.common.unknown');const notifyError=(error:unknown)=>{ setFeedback(errorText(error)); }
  const changeTab=(key:string)=>{const next=key as Tab;setTab(next);const p=new URLSearchParams(location.search);if(next==='basic')p.delete('tab');else p.set('tab',next);history.replaceState(null,'',`${location.pathname}${p.size?`?${p}`:''}`)}
  const saveBasic=form.handleSubmit(async(values)=>{const parsed=basicSchema.safeParse(values);if(!parsed.success){setFeedback(t('validation.invalid',{name:t('system.access.roles.detail.basic')}));return}try{await mutations.update.mutateAsync({id:roleId,input:{...parsed.data,parent_id:role?.parent_id??null} satisfies AdminRoleRequest});setFeedback(t('system.access.roles.feedback.saved'))}catch(error){notifyError(error)}})
  const savePermissions=async()=>{try{await mutations.permissions.mutateAsync({id:roleId,input:{permission_ids:selectedPermissions}});setFeedback(t('system.access.roles.feedback.permissions_saved'))}catch(error){notifyError(error)}}
  const saveMenus=async()=>{try{await mutations.menus.mutateAsync({id:roleId,input:{menu_ids:selectedMenus}});setFeedback(t('system.access.roles.feedback.menus_saved'))}catch(error){notifyError(error)}}
  const saveScope=async()=>{try{await mutations.scope.mutateAsync({id:roleId,input:{data_scope:scope as 'all'|'tenant'|'department'|'department_tree'|'self'|'custom',unit_ids:scope==='custom'?scopeUnits:[]}});setFeedback(t('system.access.roles.feedback.scope_saved'))}catch(error){notifyError(error)}}
  if(roles.isPending)return <div className="ak-centered-state" aria-live="polite">{t('common.states.loading')}</div>
  if(roles.isError||!role)return <div className="ak-page-container"><div className="ak-form-error" role="alert">{t('system.access.load_error')} <Button onClick={()=>{void roles.refetch()}}>{t('common.actions.retry')}</Button></div></div>
  const immutable=role.is_system
  const basic=<Card><Form layout="vertical" onFinish={()=>void saveBasic()} requiredMark={false}><Controller control={form.control} name="code" render={({field})=><Form.Item label={t('system.access.roles.fields.code')}><Input {...field} aria-label={t('system.access.roles.fields.code')} disabled={immutable}/></Form.Item>}/><Controller control={form.control} name="name" render={({field})=><Form.Item label={t('system.access.roles.fields.name')}><Input {...field} aria-label={t('system.access.roles.fields.name')} disabled={immutable}/></Form.Item>}/><Controller control={form.control} name="description" render={({field})=><Form.Item label={t('system.access.roles.fields.description')}><Input.TextArea {...field} aria-label={t('system.access.roles.fields.description')} disabled={immutable}/></Form.Item>}/><div className="ak-access-form-row"><Controller control={form.control} name="sort_order" render={({field})=><Form.Item label={t('system.access.roles.fields.sort_order')}><InputNumber {...field} aria-label={t('system.access.roles.fields.sort_order')} disabled={immutable}/></Form.Item>}/><Controller control={form.control} name="status" render={({field})=><Form.Item label={t('system.access.roles.fields.status')}><Select {...field} aria-label={t('system.access.roles.fields.status')} disabled={immutable} options={['active','disabled'].map((value)=>({value,label:t(`system.access.status.${value}`)}))}/></Form.Item>}/></div>{permissions.has('iam.role.update')&&!immutable?<Button htmlType="submit" loading={mutations.update.isPending} type="primary">{t('common.actions.save')}</Button>:null}</Form></Card>
  const permissionPanel=<Card title={t('system.access.roles.detail.permissions')} extra={<Tag>{t('system.access.selected',{count:selectedPermissions.length})}</Tag>}>{catalog.isPending?<div aria-live="polite">{t('common.states.loading')}</div>:catalog.isError?<div className="ak-form-error" role="alert">{t('system.access.load_error')}</div>:<Checkbox.Group className="ak-permission-grid" value={selectedPermissions} onChange={(values)=>{ setSelectedPermissions(values); }} disabled={immutable||!permissions.has('iam.role.assign_permission')}>{catalog.data.items.map((item)=><Checkbox key={item.id} value={item.id}><span className="ak-permission-code">{item.code}</span><span className="ak-user-secondary">{item.module_code} / {item.resource_name} / {item.action_name}</span></Checkbox>)}</Checkbox.Group>}{permissions.has('iam.role.assign_permission')&&!immutable?<Button loading={mutations.permissions.isPending} onClick={()=>void savePermissions()} type="primary">{t('common.actions.save')}</Button>:null}</Card>
  const menuPanel=<Card title={t('system.access.roles.detail.menus')} extra={<Tag>{t('system.access.selected',{count:selectedMenus.length})}</Tag>}>{menus.isPending?<div aria-live="polite">{t('common.states.loading')}</div>:<Tree aria-label={t('system.access.roles.detail.menus')} checkable checkedKeys={selectedMenus} disabled={immutable||!permissions.has('iam.role.assign_menu')} onCheck={(keys)=>{ setSelectedMenus(keys as string[]); }} treeData={menuTree(menus.data?.items??[],(item)=>item.i18n_key&&i18n.exists(item.i18n_key)?t(item.i18n_key):item.title)}/>}<Typography.Paragraph type="secondary">{t('system.access.roles.menu_separation')}</Typography.Paragraph>{permissions.has('iam.role.assign_menu')&&!immutable?<Button loading={mutations.menus.isPending} onClick={()=>void saveMenus()} type="primary">{t('common.actions.save')}</Button>:null}</Card>
  const scopePanel=<Card title={t('system.access.roles.detail.data_scope')}><Radio.Group aria-label={t('system.access.roles.fields.scope')} value={scope} onChange={(e)=>{ setScope(e.target.value as string); }} disabled={immutable||!permissions.has('iam.role.update_data_scope')} options={['all','tenant','department','department_tree','self','custom'].map((value)=>({value,label:t(`system.access.roles.scope.${value}`)}))}/>{scope==='custom'?<Select aria-label={t('system.access.roles.fields.scope_units')} mode="multiple" showSearch={{optionFilterProp:'label'}} value={scopeUnits} onChange={setScopeUnits} options={flatUnits(units.data??[]).map((unit)=>({value:unit.id,label:unit.name}))}/>:null}{permissions.has('iam.role.update_data_scope')&&!immutable?<Button loading={mutations.scope.isPending} onClick={()=>void saveScope()} type="primary">{t('common.actions.save')}</Button>:null}</Card>
  const members=<Card><Empty description={t('system.access.roles.members.description')}/><a className="ak-back-link" href={`/system/users/accounts?role_id=${encodeURIComponent(role.id)}`}>{t('system.access.roles.members.open')}</a></Card>
  return <div className="ak-page-container"><a className="ak-back-link" href="/system/access/roles" onClick={(event)=>{event.preventDefault();history.back()}}>{t('system.access.roles.detail.back')}</a><header className="ak-page-heading"><div><Typography.Title level={1}>{role.name}</Typography.Title><Typography.Paragraph type="secondary">{role.code}</Typography.Paragraph></div><Space><Tag>{t(`system.access.roles.type.${role.role_type}`)}</Tag><Tag className={role.status==='active'?'ak-status-success':'ak-status-neutral'}>{t(`system.access.status.${role.status}`)}</Tag></Space></header>{immutable?<div className="ak-access-notice" role="note">{t('system.access.roles.system_immutable')}</div>:null}{feedback?<div className="ak-org-feedback" role="status">{feedback}</div>:null}<Tabs activeKey={tab} onChange={changeTab} items={[{key:'basic',label:t('system.access.roles.detail.basic'),children:basic},{key:'permissions',label:t('system.access.roles.detail.permissions'),children:permissionPanel},{key:'menus',label:t('system.access.roles.detail.menus'),children:menuPanel},{key:'data-scope',label:t('system.access.roles.detail.data_scope'),children:scopePanel},{key:'members',label:t('system.access.roles.detail.members'),children:members}]}/></div>
}
